# Generated by Django 5.0.14 on 2026-04-28 20:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaLaboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("BAIXO", "Baixo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Critico"),
                        ],
                        default="MEDIO",
                        max_length=20,
                        verbose_name="Impacto padrao",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria de ocorrencia do laboratorio",
                "verbose_name_plural": "Categorias de ocorrencia do laboratorio",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaLaboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                ("detalhamento", models.TextField(verbose_name="Detalhamento")),
                (
                    "consequencias",
                    models.TextField(blank=True, verbose_name="Consequencias"),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("BAIXO", "Baixo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Critico"),
                        ],
                        default="MEDIO",
                        max_length=20,
                        verbose_name="Impacto",
                    ),
                ),
                (
                    "data_abertura",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e hora da abertura",
                    ),
                ),
                (
                    "data_encerramento",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data e hora do encerramento",
                    ),
                ),
                (
                    "duracao",
                    models.DurationField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Duracao da ocorrencia",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias",
                        to="laboratorio.categorialaboratorio",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_laboratorio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsavel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrencia do laboratorio",
                "verbose_name_plural": "Ocorrencias do laboratorio",
                "ordering": ["-data_abertura"],
                "indexes": [
                    models.Index(
                        fields=["data_abertura"], name="laboratorio_data_ab_802b0c_idx"
                    ),
                    models.Index(
                        fields=["impacto"], name="laboratorio_impacto_04e023_idx"
                    ),
                ],
            },
        ),
    ]
