# Generated by Django 5.0.14 on 2026-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="anotacoes",
            field=models.TextField(blank=True, verbose_name="Anotacoes internas"),
        ),
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="horas_indisponibilidade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Horas de indisponibilidade",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="impacto_financeiro",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Impacto financeiro estimado",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="observacoes_encerramento",
            field=models.TextField(blank=True, verbose_name="Observacoes do encerramento"),
        ),
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="perda_producao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Perda de producao",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="unidade_perda_producao",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Unidade da perda de producao",
            ),
        ),
    ]