# Generated by Django 5.0.14 on 2026-04-29 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_occurrence_notes(apps, schema_editor):
    OcorrenciaLaboratorio = apps.get_model("laboratorio", "OcorrenciaLaboratorio")
    OcorrenciaLaboratorioAnotacao = apps.get_model("laboratorio", "OcorrenciaLaboratorioAnotacao")

    for ocorrencia in OcorrenciaLaboratorio.objects.exclude(anotacoes=""):
        texto = (ocorrencia.anotacoes or "").strip()
        if not texto:
            continue

        OcorrenciaLaboratorioAnotacao.objects.create(
            ocorrencia_id=ocorrencia.id,
            usuario_id=ocorrencia.responsavel_id,
            texto=texto,
            criado_em=ocorrencia.atualizado_em or ocorrencia.criado_em,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("laboratorio", "0002_ocorrencia_notes_and_close_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaLaboratorioAnotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Anotacao")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e hora da anotacao"),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotacoes_registradas",
                        to="laboratorio.ocorrencialaboratorio",
                        verbose_name="Ocorrencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anotacoes_ocorrencias_laboratorio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsavel pela anotacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anotacao da ocorrencia do laboratorio",
                "verbose_name_plural": "Anotacoes das ocorrencias do laboratorio",
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.RunPython(migrate_existing_occurrence_notes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="ocorrencialaboratorio",
            name="anotacoes",
        ),
    ]