# Generated by Django 5.0.14 on 2026-04-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_replace_occurrence_notes_with_log'),
        ('maquinas', '0002_categoriamaquina_maquina_categoria'),
        ('rh', '0018_colaborador_rh_colaborador_turno_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencialaboratorio',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_laboratorio_colaborador', to='rh.colaborador', verbose_name='Colaborador (se aplicável)'),
        ),
        migrations.AddField(
            model_name='ocorrencialaboratorio',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_laboratorio_maquina', to='maquinas.maquina', verbose_name='Máquina (se aplicável)'),
        ),
    ]
