# Generated by Django 5.0.14 on 2026-05-10 00:00

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_criado_por(apps, schema_editor):
    OcorrenciaLaboratorio = apps.get_model("laboratorio", "OcorrenciaLaboratorio")
    OcorrenciaLaboratorio.objects.filter(
        criado_por__isnull=True,
        responsavel__isnull=False,
    ).update(criado_por_id=F("responsavel_id"))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("laboratorio", "0004_ocorrencialaboratorio_colaborador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencialaboratorio",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias_laboratorio_criadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.RunPython(backfill_criado_por, migrations.RunPython.noop),
    ]