# Generated by Django 5.0.14 on 2026-07-23 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_ocorrencialaboratorio_criado_por'),
        ('maquinas', '0004_alter_maquina_options_maquina_fabricante_and_more'),
        ('rh', '0023_colaborador_posto_lideranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamentoAntiReflexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Tratamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tratamento Antirreflexo',
                'verbose_name_plural': 'Tratamentos Antirreflexo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Turno')),
                ('turno', models.CharField(choices=[('1', 'Turno 01'), ('2', 'Turno 02'), ('3', 'Turno 03')], max_length=1, verbose_name='Turno')),
                ('inicio', models.DateTimeField(verbose_name='Início do Turno')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Turno')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Fechamento')),
            ],
            options={
                'verbose_name': 'Turno de Coating',
                'verbose_name_plural': 'Turnos de Coating',
                'ordering': ['-data', '-turno'],
                'unique_together': {('data', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='RegistroCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.IntegerField(verbose_name='Número do Lote')),
                ('lado', models.CharField(choices=[('CC', 'Côncavo'), ('CX', 'Convexo')], max_length=2, verbose_name='Lado da Lente')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinas.maquina', verbose_name='Máquina')),
                ('montagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montagens_coating', to='rh.colaborador', verbose_name='Montagem')),
                ('preparacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparacoes_coating', to='rh.colaborador', verbose_name='Preparação')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.tratamentoantireflexo', verbose_name='Tratamento')),
                ('turno_coating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='laboratorio.turnocoating', verbose_name='Turno de Referência')),
            ],
            options={
                'verbose_name': 'Registro de Coating',
                'verbose_name_plural': 'Registros de Coating',
                'ordering': ['-turno_coating__data', '-hora_entrada', 'lote'],
            },
        ),
    ]
