# Generated by Django 5.0.14 on 2026-07-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_tratamentoantireflexo_turnocoating_registrocoating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraTurnoCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Regra (Ex: Turno 01)')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Regra de Turno de Coating',
                'verbose_name_plural': 'Regras de Turnos de Coating',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='turnocoating',
            options={'ordering': ['-data', 'regra__hora_inicio'], 'verbose_name': 'Turno Diário de Coating', 'verbose_name_plural': 'Turnos Diários de Coating'},
        ),
        migrations.AlterUniqueTogether(
            name='turnocoating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turnocoating',
            name='regra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorio.regraturnocoating', verbose_name='Regra de Turno'),
        ),
        migrations.AlterUniqueTogether(
            name='turnocoating',
            unique_together={('data', 'regra')},
        ),
        migrations.RemoveField(
            model_name='turnocoating',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='turnocoating',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='turnocoating',
            name='turno',
        ),
    ]
