# Generated by Django 5.0.14 on 2026-07-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_regraturnocoating_alter_turnocoating_options_and_more'),
        ('rh', '0023_colaborador_posto_lideranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocoating',
            name='montagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='montagens_coating', to='rh.colaborador', verbose_name='Montagem'),
        ),
        migrations.AlterField(
            model_name='registrocoating',
            name='preparacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparacoes_coating', to='rh.colaborador', verbose_name='Preparação'),
        ),
    ]
