# Generated by Django 5.0.14 on 2026-07-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_alter_registrocoating_montagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocoating',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada'),
        ),
    ]
