# Generated by Django 5.0.14 on 2026-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_alter_registrocoating_hora_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoating',
            name='limpeza',
            field=models.BooleanField(default=False, verbose_name='Limpeza Realizada'),
        ),
        migrations.AddField(
            model_name='registrocoating',
            name='troca',
            field=models.BooleanField(default=False, verbose_name='Troca Realizada'),
        ),
    ]
