# Generated by Django 5.0.14 on 2026-07-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_registrocoating_limpeza_registrocoating_troca'),
        ('maquinas', '0004_alter_maquina_options_maquina_fabricante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloManutencaoCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_limpeza', models.IntegerField(default=10, verbose_name='Limite para Limpeza (Lotes)')),
                ('limite_troca', models.IntegerField(default=50, verbose_name='Limite para Troca (Lotes)')),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_coating', to='maquinas.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Ciclo de Manutenção de Coating',
                'verbose_name_plural': 'Ciclos de Manutenção de Coating',
            },
        ),
    ]
