# Generated by Django 5.0.14 on 2026-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_ciclomanutencaocoating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocoating',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='registrocoating',
            name='hora_saida',
        ),
        migrations.AddField(
            model_name='registrocoating',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrada (Data e Hora)'),
        ),
        migrations.AddField(
            model_name='registrocoating',
            name='hora_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída (Data e Hora)'),
        ),
    ]
