# Generated by Django 5.0.14 on 2026-07-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_alter_registrocoating_hora_entrada_and_more'),
        ('rh', '0023_colaborador_posto_lideranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_preparar', models.BooleanField(default=True, verbose_name='Pode Preparar')),
                ('pode_montar', models.BooleanField(default=True, verbose_name='Pode Montar')),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Equipe de Coating',
                'verbose_name_plural': 'Equipe de Coating',
            },
        ),
    ]
