# Generated by Django 5.0.14 on 2026-07-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_equipecoating'),
        ('maquinas', '0004_alter_maquina_options_maquina_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclomanutencaocoating',
            options={'ordering': ['maquina', 'tipo', 'nome'], 'verbose_name': 'Ciclo de Manutenção de Coating', 'verbose_name_plural': 'Ciclos de Manutenção de Coating'},
        ),
        migrations.RemoveField(
            model_name='ciclomanutencaocoating',
            name='limite_limpeza',
        ),
        migrations.RemoveField(
            model_name='ciclomanutencaocoating',
            name='limite_troca',
        ),
        migrations.RemoveField(
            model_name='registrocoating',
            name='limpeza',
        ),
        migrations.RemoveField(
            model_name='registrocoating',
            name='troca',
        ),
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='limite_lotes',
            field=models.IntegerField(default=10, verbose_name='Limite de Lotes'),
        ),
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='nome',
            field=models.CharField(default='Manutenção Padrão', max_length=100, verbose_name='Nome da Manutenção'),
        ),
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='tipo',
            field=models.CharField(choices=[('LIMPEZA', 'Limpeza'), ('TROCA', 'Troca')], default='LIMPEZA', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ciclomanutencaocoating',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_coating', to='maquinas.maquina', verbose_name='Máquina'),
        ),
        migrations.CreateModel(
            name='ManutencaoRealizadaCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizacoes', to='laboratorio.ciclomanutencaocoating', verbose_name='Manutenção Realizada')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='laboratorio.registrocoating', verbose_name='Registro de Lote')),
            ],
            options={
                'verbose_name': 'Manutenção Realizada (Coating)',
                'verbose_name_plural': 'Manutenções Realizadas (Coating)',
                'unique_together': {('registro', 'ciclo')},
            },
        ),
    ]
