# Generated by Django 5.0.14 on 2026-07-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0014_alter_ciclomanutencaocoating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaorealizadacoating',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.CreateModel(
            name='ItemChecklistCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Descrição da Tarefa')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='laboratorio.ciclomanutencaocoating', verbose_name='Ciclo de Manutenção')),
            ],
            options={
                'verbose_name': 'Item de Checklist de Ciclo',
                'verbose_name_plural': 'Itens de Checklist de Ciclos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaChecklistManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feito', models.BooleanField(default=False, verbose_name='Feito?')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.itemchecklistciclo', verbose_name='Item do Checklist')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_checklist', to='laboratorio.manutencaorealizadacoating', verbose_name='Manutenção Realizada')),
            ],
            options={
                'verbose_name': 'Resposta de Checklist',
                'verbose_name_plural': 'Respostas de Checklist',
                'unique_together': {('manutencao', 'item')},
            },
        ),
    ]
