# Generated by Django 5.0.14 on 2026-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0015_manutencaorealizadacoating_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamentoantireflexo',
            name='cor',
            field=models.CharField(default='#0d6efd', help_text='Cor em formato HEX (ex: #ff0000 para vermelho)', max_length=7, verbose_name='Cor de Destaque'),
        ),
    ]
