# Generated by Django 5.0.14 on 2026-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0016_tratamentoantireflexo_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='criterio',
            field=models.CharField(choices=[('LOTES', 'Por Quantidade de Lotes'), ('DIAS', 'Por Tempo (Dias Corridos)')], default='LOTES', max_length=10, verbose_name='Critério de Alerta'),
        ),
        migrations.AlterField(
            model_name='ciclomanutencaocoating',
            name='limite_lotes',
            field=models.IntegerField(default=10, verbose_name='Limite (Lotes/Dias)'),
        ),
    ]
