# Generated by Django 5.0.14 on 2026-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0017_ciclomanutencaocoating_criterio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoating',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Lote'),
        ),
    ]
