# Generated by Django 5.0.14 on 2026-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0018_registrocoating_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclomanutencaocoating',
            name='criterio',
            field=models.CharField(choices=[('LOTES', 'Por Quantidade de Lotes'), ('DIAS', 'Por Tempo (Dias Corridos)'), ('DIARIO', 'Diário (1x ao Dia)'), ('SEMANAL', 'Semanal (1x na Semana)'), ('QUINZENAL', 'Quinzenal (1x na Quinzena)'), ('MENSAL', 'Mensal (1x no Mês)'), ('LIVRE', 'Sem Periodicidade (Livre)')], default='LOTES', max_length=10, verbose_name='Critério de Alerta'),
        ),
    ]
