# Generated by Django 5.0.14 on 2026-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0019_alter_ciclomanutencaocoating_criterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='valor_maximo',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Máximo Aceitável'),
        ),
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='valor_minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo Aceitável'),
        ),
        migrations.AddField(
            model_name='manutencaorealizadacoating',
            name='valor_aferido',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Aferido (Verificações)'),
        ),
        migrations.AlterField(
            model_name='ciclomanutencaocoating',
            name='limite_lotes',
            field=models.IntegerField(default=1, verbose_name='Limite de Lotes/Dias'),
        ),
        migrations.AlterField(
            model_name='ciclomanutencaocoating',
            name='tipo',
            field=models.CharField(choices=[('LIMPEZA', 'Limpeza'), ('TROCA', 'Troca'), ('VERIFICACAO', 'Verificação')], default='LIMPEZA', max_length=20, verbose_name='Tipo'),
        ),
    ]
