# Generated by Django 5.0.14 on 2026-07-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0020_ciclomanutencaocoating_valor_maximo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclomanutencaocoating',
            options={'ordering': ['maquina', 'ordem', 'tipo', 'nome'], 'verbose_name': 'Ciclo de Manutenção de Coating', 'verbose_name_plural': 'Ciclos de Manutenção de Coating'},
        ),
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='tratamentos_especificos',
            field=models.ManyToManyField(blank=True, help_text='Se selecionado, a manutenção só será cobrada e contará lotes que possuam estes tratamentos.', to='laboratorio.tratamentoantireflexo', verbose_name='Tratamentos Específicos (Opcional)'),
        ),
    ]
