# Generated by Django 5.0.14 on 2026-07-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0021_alter_ciclomanutencaocoating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclomanutencaocoating',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
