# Generated by Django 5.0.14 on 2026-09-30 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0022_ciclomanutencaocoating_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoating',
            name='mix_servico',
            field=models.BooleanField(default=False, verbose_name='Mix de serviço'),
        ),
        migrations.AddField(
            model_name='registrocoating',
            name='mix_servico_confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mix de serviço confirmado em'),
        ),
        migrations.AddField(
            model_name='registrocoating',
            name='mix_servico_confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Mix de serviço confirmado por'),
        ),
    ]
