# Generated by Django 5.0.14 on 2026-10-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0023_registrocoating_mix_servico'),
        ('maquinas', '0004_alter_maquina_options_maquina_fabricante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoProcessoTMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Fluxo / Linha de Produção')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código / Identificador')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Processo')),
                ('horas_trabalho_dia', models.DecimalField(decimal_places=2, default=8.8, help_text='Jornada diária líquida para cálculo da capacidade diária (ex: 8.80h)', max_digits=5, verbose_name='Horas de Trabalho por Dia / Turno')),
                ('dias_trabalho_mes', models.IntegerField(default=22, verbose_name='Dias Úteis no Mês')),
                ('unidade_medida', models.CharField(choices=[('PECAS', 'Peças / Unidades'), ('PARES', 'Pares'), ('LOTES', 'Lotes')], default='PECAS', max_length=20, verbose_name='Unidade Padrão')),
                ('fator_conversao_par', models.DecimalField(decimal_places=2, default=2.0, help_text='Ex: 2 peças por par de lentes', max_digits=5, verbose_name='Fator de Conversão Par (Peças por Par)')),
                ('tamanho_padrao_lote', models.IntegerField(default=1, help_text='Quantidade média de peças processadas por lote', verbose_name='Tamanho Padrão do Lote (Peças)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fluxo de Produção TMS',
                'verbose_name_plural': 'Fluxos de Produção TMS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProcessoTMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem / Sequência')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Etapa / Posto')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código da Etapa')),
                ('tipo_posto', models.CharField(choices=[('MANUAL', 'Manual / Operador'), ('MAQUINA', 'Máquina / Automatizado'), ('HIBRIDO', 'Híbrido (Máquina + Operador)')], default='MANUAL', max_length=20, verbose_name='Tipo de Posto')),
                ('tempo_ciclo_segundos', models.DecimalField(decimal_places=2, default=60.0, help_text='Tempo necessário para processar 1 unidade (em segundos)', max_digits=10, verbose_name='Tempo de Ciclo por Unidade (segundos)')),
                ('tempo_setup_minutos', models.DecimalField(decimal_places=2, default=0.0, help_text='Tempo de preparação ou troca de lote/ferramental', max_digits=8, verbose_name='Tempo de Setup / Troca (minutos)')),
                ('postos_paralelos', models.IntegerField(default=1, help_text='Número de postos ou máquinas trabalhando simultaneamente nesta etapa', verbose_name='Qtd de Postos / Operadores em Paralelo')),
                ('eficiencia_oee', models.DecimalField(decimal_places=2, default=85.0, help_text='Percentual de aproveitamento real (0 a 100%)', max_digits=5, verbose_name='Eficiência Operacional / OEE (%)')),
                ('perda_refugo_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual estimado de refugo ou retrabalho nesta etapa', max_digits=5, verbose_name='Taxa de Perda / Refugo (%)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Operacionais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_tms', to='maquinas.maquina', verbose_name='Máquina Associada (Opcional)')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='laboratorio.fluxoprocessotms', verbose_name='Fluxo de Produção')),
            ],
            options={
                'verbose_name': 'Etapa de Processo TMS',
                'verbose_name_plural': 'Etapas de Processo TMS',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
