from django.urls import path

from . import views

app_name = "auditoria"

urlpatterns = [
    path("", views.modulo_auditoria_view, name="modulo"),
    path("modelos/", views.modelos_list, name="modelos_list"),
    path("modelos/novo/", views.modelo_create, name="modelo_create"),
    path("modelos/<int:pk>/editar/", views.modelo_edit, name="modelo_edit"),
    path("modelos/<int:pk>/duplicar/", views.modelo_duplicate, name="modelo_duplicate"),
    path("modelos/<int:pk>/remover/", views.modelo_delete, name="modelo_delete"),
    path("modelos/<int:pk>/encerrar/", views.modelo_encerrar, name="modelo_encerrar"),
    path("modelos/<int:pk>/arquivar/", views.modelo_arquivar, name="modelo_arquivar"),
    path("modelos/<int:pk>/justificar-nao-execucao/", views.justificar_nao_execucao, name="justificar_nao_execucao"),
    
    path("modelos/<int:modelo_id>/categorias/", views.modelo_categorias, name="modelo_categorias"),
    path("modelos/topicos/<int:pk>/remover/", views.topico_delete, name="topico_delete"),
    path("topicos/reorder/", views.reorder_topicos, name="reorder_topicos"),

    path("perguntas/", views.perguntas_list, name="perguntas_list"),
    path("perguntas/next-ordem/", views.api_next_pergunta_ordem, name="api_next_pergunta_ordem"),
    path("modelos/topicos/", views.api_modelo_topicos, name="api_modelo_topicos"),
    path("perguntas/bulk-topico/", views.perguntas_bulk_set_topico, name="perguntas_bulk_set_topico"),
    path("perguntas/bulk-resposta/", views.perguntas_bulk_apply_resposta, name="perguntas_bulk_apply_resposta"),
    path("perguntas/nova/", views.pergunta_create, name="pergunta_create"),
    path("perguntas/<int:pk>/editar/", views.pergunta_edit, name="pergunta_edit"),
    path("perguntas/<int:pk>/duplicar/", views.pergunta_duplicate, name="pergunta_duplicate"),
    path("perguntas/<int:pk>/remover/", views.pergunta_delete, name="pergunta_delete"),
    path("registros/", views.registros_list, name="registros_list"),
    path("registros/selecionar-modelo/", views.selecionar_modelo_preenchimento, name="selecionar_modelo_preenchimento"),
    path("registros/novo/", views.registro_create, name="registro_create"),
    path("registros/novo/<int:modelo_id>/", views.registro_create, name="registro_create_modelo"),
    path("registros/<int:pk>/editar/", views.registro_edit, name="registro_edit"),
    path("registros/<int:pk>/remover/", views.registro_delete, name="registro_delete"),
    path("registros/<int:pk>/exportar-pdf/", views.registro_exportar_pdf, name="registro_exportar_pdf"),
    path("registros/<int:pk>/", views.registro_detail, name="registro_detail"),
    path("modelos/<int:modelo_id>/registros/", views.registros_por_modelo, name="registros_por_modelo"),
    path("modelos/<int:modelo_id>/registros/compartilhado/", views.registros_por_modelo, name="registros_por_modelo_compartilhado"),
    path(
        "modelos/<int:modelo_id>/comentarios/<int:pk>/editar/",
        views.comentario_edit,
        name="comentario_edit",
    ),
    path(
        "modelos/<int:modelo_id>/comentarios/<int:pk>/remover/",
        views.comentario_delete,
        name="comentario_delete",
    ),
    path(
        "modelos/<int:modelo_id>/registros/exportar-excel/",
        views.exportar_respostas_excel,
        name="exportar_respostas_excel",
    ),
    path("dashboard/", views.dashboard_auditoria, name="dashboard"),

    # ISO 13485 (Entrevista)
    path("iso/", views.iso_auditoria_list, name="iso_auditoria_list"),
    path("iso/<int:auditoria_id>/fechamento/", views.iso_fechamento_presentation_view, name="iso_fechamento_presentation"),
    path("iso/<int:auditoria_id>/entrevista/", views.iso_entrevista_view, name="iso_entrevista_view"),
    path("iso/<int:auditoria_id>/revisao/", views.iso_revisao_dashboard, name="iso_revisao_dashboard"),
    path("iso/api/revisao/reverter/", views.api_iso_revisao_reverter, name="api_iso_revisao_reverter"),
    path("iso/<int:auditoria_id>/matriz/", views.iso_matriz_view, name="iso_matriz_view"),
    path("iso/<int:auditoria_id>/cronograma/", views.iso_auditoria_cronograma, name="iso_auditoria_cronograma"),
    path("iso/<int:auditoria_id>/agenda/<int:pk>/concluir/", views.iso_agenda_toggle_conclusao, name="iso_agenda_toggle_conclusao"),
    path("iso/<int:auditoria_id>/exportar-excel/", views.iso_auditoria_export_excel, name="iso_auditoria_export_excel"),
    path("iso/<int:auditoria_id>/api/quick-edit/", views.api_iso_agenda_quick_edit, name="api_iso_agenda_quick_edit"),
    path("iso/<int:auditoria_id>/api/create-gap/", views.api_iso_agenda_create_gap, name="api_iso_agenda_create_gap"),
    path("iso/api/autosave/", views.api_iso_autosave_resposta, name="api_iso_autosave_resposta"),
    path("iso/api/solicitacoes/criar/", views.api_iso_solicitacao_create, name="api_iso_solicitacao_create"),
    path("iso/api/solicitacoes/<int:pk>/editar/", views.api_iso_solicitacao_update, name="api_iso_solicitacao_update"),
    path("iso/api/solicitacoes/<int:pk>/deletar/", views.api_iso_solicitacao_delete, name="api_iso_solicitacao_delete"),
    path("iso/api/solicitacoes/<int:pk>/transferir/", views.api_iso_solicitacao_transferir, name="api_iso_solicitacao_transferir"),
    path("iso/api/marcar-nao-aplicavel/", views.api_iso_marcar_nao_aplicavel, name="api_iso_marcar_nao_aplicavel"),
    # ISO 13485 (Setup CRUD)
    path("iso/setup/", views.iso_setup_dashboard, name="iso_setup_dashboard"),
    
    path("iso/setup/normas/nova/", views.iso_norma_create, name="iso_norma_create"),
    path("iso/setup/normas/<int:pk>/", views.iso_norma_detail, name="iso_norma_detail"),
    path("iso/setup/normas/<int:pk>/regras/salvar/", views.iso_norma_regras_salvar, name="iso_norma_regras_salvar"),
    path("iso/setup/normas/<int:pk>/editar/", views.iso_norma_edit, name="iso_norma_edit"),
    path("iso/setup/normas/<int:pk>/arquivar/", views.iso_norma_archive, name="iso_norma_archive"),
    path("iso/setup/normas/<int:pk>/remover/", views.iso_norma_delete, name="iso_norma_delete"),
    
    path("iso/setup/itens/<int:pk>/json/", views.iso_item_detail_api, name="iso_item_detail_api"),
    path("iso/setup/itens/novo/", views.iso_item_create, name="iso_item_create"),
    path("iso/setup/itens/<int:pk>/editar/", views.iso_item_edit, name="iso_item_edit"),
    path("iso/setup/itens/<int:pk>/remover/", views.iso_item_delete, name="iso_item_delete"),
    
    path("iso/setup/perguntas/nova/", views.iso_pergunta_create, name="iso_pergunta_create"),
    path("iso/setup/perguntas/<int:pk>/editar/", views.iso_pergunta_edit, name="iso_pergunta_edit"),
    path("iso/setup/perguntas/<int:pk>/remover/", views.iso_pergunta_delete, name="iso_pergunta_delete"),
    
    path("iso/setup/modelos/novo/", views.iso_modelo_create, name="iso_modelo_create"),
    path("iso/setup/modelos/<int:pk>/", views.iso_modelo_detail, name="iso_modelo_detail"),
    path("iso/setup/modelos/<int:pk>/editar/", views.iso_modelo_edit, name="iso_modelo_edit"),
    path("iso/setup/modelos/<int:pk>/arquivar/", views.iso_modelo_archive, name="iso_modelo_archive"),
    path("iso/setup/modelos/<int:pk>/remover/", views.iso_modelo_delete, name="iso_modelo_delete"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/novo/", views.iso_modelo_bloco_create, name="iso_modelo_bloco_create"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/<int:pk>/editar/", views.iso_modelo_bloco_edit, name="iso_modelo_bloco_edit"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/<int:pk>/remover/", views.iso_modelo_bloco_delete, name="iso_modelo_bloco_delete"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/<int:pk>/perguntas/", views.iso_modelo_bloco_perguntas, name="iso_modelo_bloco_perguntas"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/<int:pk>/perguntas/nova/", views.iso_modelo_bloco_pergunta_create, name="iso_modelo_bloco_pergunta_create"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/<int:pk>/sincronizar/", views.iso_modelo_bloco_sincronizar, name="iso_modelo_bloco_sincronizar"),
    path("iso/setup/modelos/<int:modelo_id>/blocos/<int:pk>/alvo/", views.iso_modelo_bloco_alvo_update, name="iso_modelo_bloco_alvo_update"),
    path("iso/setup/perguntas/<int:pk>/editar/", views.iso_pergunta_edit, name="iso_pergunta_edit"),
    
    path("iso/setup/auditorias/nova/", views.iso_auditoria_create, name="iso_auditoria_create"),
    path("iso/setup/auditorias/<int:pk>/", views.iso_auditoria_detail, name="iso_auditoria_detail"),
    path("iso/setup/auditorias/<int:pk>/importar-modelo/", views.iso_auditoria_import_modelo, name="iso_auditoria_import_modelo"),
    path("iso/setup/auditorias/<int:pk>/editar/", views.iso_auditoria_edit, name="iso_auditoria_edit"),
    path("iso/setup/auditorias/<int:pk>/arquivar/", views.iso_auditoria_archive, name="iso_auditoria_archive"),
    path("iso/setup/auditorias/<int:pk>/remover/", views.iso_auditoria_delete, name="iso_auditoria_delete"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/nova/", views.iso_agenda_create, name="iso_agenda_create"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/", views.iso_agenda_detail, name="iso_agenda_detail"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/editar/", views.iso_agenda_edit, name="iso_agenda_edit"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/arquivar/", views.iso_agenda_archive, name="iso_agenda_archive"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/remover/", views.iso_agenda_delete, name="iso_agenda_delete"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/perguntas/", views.iso_agenda_perguntas_edit, name="iso_agenda_perguntas_edit"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/perguntas/nova/", views.iso_agenda_pergunta_create, name="iso_agenda_pergunta_create"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/alvo/", views.iso_agenda_alvo_update, name="iso_agenda_alvo_update"),
    path("iso/setup/auditorias/<int:auditoria_id>/agendas/<int:pk>/sincronizar/", views.iso_agenda_sincronizar_modelo, name="iso_agenda_sincronizar_modelo"),
]
