# Generated by Django 5.0.14 on 2026-02-17 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('objeto_auditoria', models.TextField(verbose_name='Objeto da Auditoria')),
                ('link_sharepoint', models.URLField(blank=True, verbose_name='Link SharePoint')),
                ('periodicidade', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Auditoria',
                'verbose_name_plural': 'Modelos de Auditoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('tipo_resposta', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número inteiro'), ('DECIMAL', 'Número decimal'), ('DATA', 'Data'), ('BOOLEANO', 'Sim/Não')], default='TEXTO', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='auditoria.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Pergunta da Auditoria',
                'verbose_name_plural': 'Perguntas da Auditoria',
                'ordering': ['modelo__nome', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_auditoria', models.DateField(verbose_name='Data da Auditoria')),
                ('periodo_inicio', models.DateField(verbose_name='Período Inicial')),
                ('periodo_fim', models.DateField(verbose_name='Período Final')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='auditoria.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_auditoria', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='auditoria.perguntaauditoria')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='auditoria.registroauditoria')),
            ],
            options={
                'verbose_name': 'Resposta de Auditoria',
                'verbose_name_plural': 'Respostas de Auditoria',
                'ordering': ['registro', 'pergunta__ordem', 'id'],
                'unique_together': {('registro', 'pergunta')},
            },
        ),
    ]
