# Generated by Django 5.0.14 on 2026-02-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloauditoria',
            name='periodicidade',
            field=models.CharField(choices=[('UNICA', 'Aplicação Única'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20),
        ),
    ]
