# Generated by Django 5.0.14 on 2026-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_modeloauditoria_periodicidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloauditoria',
            name='dia_mes',
            field=models.IntegerField(blank=True, help_text='Dia do mês para execução (1-31)', null=True, verbose_name='Dia do Mês'),
        ),
        migrations.AddField(
            model_name='modeloauditoria',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Para periodicidade semanal', max_length=10, null=True, verbose_name='Dia da Semana'),
        ),
        migrations.AddField(
            model_name='modeloauditoria',
            name='dias_quinzenal',
            field=models.CharField(blank=True, help_text='Dois dias do mês separados por vírgula (ex: 1,16)', max_length=10, null=True, verbose_name='Dias da Quinzena'),
        ),
    ]
