# Generated by Django 5.0.14 on 2026-02-18 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_modeloauditoria_dia_mes_modeloauditoria_dia_semana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloauditoria',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela realização da auditoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_auditoria_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Auditoria'),
        ),
    ]
