# Generated by Django 5.0.14 on 2026-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_modeloauditoria_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='tipo_resposta',
            field=models.CharField(choices=[('SIM_NAO', 'Sim/Não'), ('NUMERO', 'Número inteiro'), ('DECIMAL', 'Número decimal')], default='SIM_NAO', max_length=20),
        ),
    ]
