# Generated by Django 5.0.14 on 2026-02-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_pergunta_preenchimento_semanal_resposta_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='item_os',
            field=models.CharField(blank=True, default='', help_text='Preencher se necessário para identificar ordens de serviço ou pontos específicos.', max_length=120, verbose_name='ITEM/O.S.'),
        ),
    ]
