# Generated by Django 5.0.14 on 2026-03-02 00:00

from django.conf import settings
from django.db import migrations, models


def forwards_copy_responsavel(apps, schema_editor):
    ModeloAuditoria = apps.get_model("auditoria", "ModeloAuditoria")

    for modelo in ModeloAuditoria.objects.exclude(responsavel_id=None).iterator():
        try:
            modelo.responsaveis.add(modelo.responsavel_id)
        except Exception:
            # If something goes wrong (e.g. missing user), keep migration resilient.
            continue


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0008_registroauditoria_item_os"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modeloauditoria",
            name="responsaveis",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuários autorizados a preencher/atualizar auditorias deste modelo.",
                related_name="modelos_auditoria_responsaveis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsáveis pela Auditoria",
            ),
        ),
        migrations.RunPython(forwards_copy_responsavel, backwards_noop),
    ]
