# Generated by Django 5.0.14 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0009_modeloauditoria_responsaveis"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeloauditoria",
            name="preenchimento_grid",
            field=models.BooleanField(
                default=False,
                help_text="Habilita preenchimento em tabela para repetir as mesmas perguntas por múltiplos itens/equipamentos/serviços.",
                verbose_name="Preenchimento em GRID",
            ),
        ),
        migrations.AddField(
            model_name="modeloauditoria",
            name="grid_rotulo_item",
            field=models.CharField(
                blank=True,
                default="Item",
                help_text="Ex.: Equipamento, Serviço, Item, Ativo.",
                max_length=60,
                verbose_name="Rótulo do item (GRID)",
            ),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="grid_itens",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use uma linha por item/equipamento/serviço quando o modelo estiver em modo GRID.",
                verbose_name="Itens (GRID)",
            ),
        ),
        migrations.AddField(
            model_name="respostaauditoria",
            name="grid_item",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identifica o item/equipamento/serviço quando o preenchimento é em GRID.",
                max_length=120,
                verbose_name="Item (GRID)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="respostaauditoria",
            unique_together={("registro", "pergunta", "dia_semana", "grid_item")},
        ),
    ]
