# Generated by Django 5.0.14 on 2026-03-05 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0014_modelo_subcategorias_pergunta_subcategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='tipo_resposta',
            field=models.CharField(choices=[('SIM_NAO', 'Sim/Não'), ('LISTA', 'Lista (opções)'), ('NUMERO', 'Número inteiro'), ('DECIMAL', 'Número decimal')], default='SIM_NAO', max_length=20),
        ),
        migrations.CreateModel(
            name='ComentarioAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='auditoria.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Comentário de Auditoria',
                'verbose_name_plural': 'Comentários de Auditoria',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
