# Generated by Django 5.0.14 on 2026-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0016_pergunta_descricao_detalhada_comentario_resposta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentariorespostaauditoria',
            unique_together=set(),
        ),
    ]
