# Generated by Django 5.0.14 on 2026-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0021_perguntaauditoria_exibir_grafico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloauditoria',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
