# Generated by Django 5.0.14 on 2026-07-22 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0022_modeloauditoria_arquivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da Justificativa')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Justificado por')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='auditoria.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Justificativa de Auditoria',
                'verbose_name_plural': 'Justificativas de Auditoria',
                'ordering': ['-ano_referencia', '-mes_referencia', '-criado_em'],
            },
        ),
    ]
