# Generated by Django 5.0.14 on 2026-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0023_justificativaauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justificativaauditoria',
            options={'ordering': ['-periodo_inicio', '-criado_em'], 'verbose_name': 'Justificativa de Auditoria', 'verbose_name_plural': 'Justificativas de Auditoria'},
        ),
        migrations.RemoveField(
            model_name='justificativaauditoria',
            name='ano_referencia',
        ),
        migrations.RemoveField(
            model_name='justificativaauditoria',
            name='mes_referencia',
        ),
        migrations.AddField(
            model_name='justificativaauditoria',
            name='periodo_fim',
            field=models.DateField(null=True, verbose_name='Fim do Período'),
        ),
        migrations.AddField(
            model_name='justificativaauditoria',
            name='periodo_inicio',
            field=models.DateField(null=True, verbose_name='Início do Período'),
        ),
    ]
