# Generated by Django 5.0.14 on 2026-08-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0024_alter_justificativaauditoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='subcategoria',
            field=models.CharField(blank=True, default='', help_text='Opcional. Deve existir nas sub-categorias do modelo (quando definidas).', max_length=80, verbose_name='Sub-categoria (Legado)'),
        ),
        migrations.CreateModel(
            name='CategoriaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='auditoria.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Categoria de Auditoria',
                'verbose_name_plural': 'Categorias de Auditoria',
                'ordering': ['modelo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='auditoria.categoriaauditoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Sub-categoria de Auditoria',
                'verbose_name_plural': 'Sub-categorias de Auditoria',
                'ordering': ['categoria__modelo', 'categoria__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='perguntaauditoria',
            name='subcategoria_nova',
            field=models.ForeignKey(blank=True, help_text='Sub-categoria / Sub-cláusula da pergunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='auditoria.subcategoriaauditoria', verbose_name='Sub-categoria'),
        ),
    ]
