# Generated by Django 5.0.14 on 2026-08-11 11:58

from django.db import migrations


def migrate_subcategorias(apps, schema_editor):
    ModeloAuditoria = apps.get_model('auditoria', 'ModeloAuditoria')
    CategoriaAuditoria = apps.get_model('auditoria', 'CategoriaAuditoria')
    SubcategoriaAuditoria = apps.get_model('auditoria', 'SubcategoriaAuditoria')
    PerguntaAuditoria = apps.get_model('auditoria', 'PerguntaAuditoria')

    for modelo in ModeloAuditoria.objects.all():
        raw_subcategorias = (modelo.subcategorias or "").replace("\r\n", "\n")
        parts = [p.strip() for p in raw_subcategorias.split("\n")]
        
        # Only create a category if there are subcategories
        valid_parts = [p for p in parts if p]
        if not valid_parts:
            continue

        # Create the default "Geral" category
        categoria = CategoriaAuditoria.objects.create(
            modelo=modelo,
            nome="Geral",
            ordem=1
        )

        subcategoria_map = {}
        ordem = 1
        seen = set()
        for p in valid_parts:
            key = p.lower()
            if key in seen:
                continue
            seen.add(key)
            sub_obj = SubcategoriaAuditoria.objects.create(
                categoria=categoria,
                nome=p,
                ordem=ordem
            )
            subcategoria_map[key] = sub_obj
            ordem += 1

        # Now link existing questions
        perguntas = PerguntaAuditoria.objects.filter(modelo=modelo)
        for pergunta in perguntas:
            sub = (pergunta.subcategoria or "").strip().lower()
            if sub in subcategoria_map:
                pergunta.subcategoria_nova = subcategoria_map[sub]
                pergunta.save()

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0025_alter_perguntaauditoria_subcategoria_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_subcategorias, reverse_migrate),
    ]
