# Generated by Django 5.0.14 on 2026-08-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0026_migrate_subcategorias_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloauditoria',
            name='subcategorias',
        ),
        migrations.RemoveField(
            model_name='perguntaauditoria',
            name='subcategoria',
        ),
        migrations.RenameField(
            model_name='perguntaauditoria',
            old_name='subcategoria_nova',
            new_name='subcategoria',
        ),
    ]
