# Generated by Django 5.0.14 on 2026-08-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0026_migrate_subcategorias_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloauditoria',
            name='subcategorias',
        ),
        migrations.RemoveField(
            model_name='perguntaauditoria',
            name='subcategoria_nova',
        ),
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='subcategoria',
            field=models.ForeignKey(blank=True, help_text='Sub-categoria / Sub-cláusula da pergunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='auditoria.subcategoriaauditoria', verbose_name='Sub-cláusula'),
        ),
    ]
