# Generated by Django 5.0.14 on 2026-08-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0027_remove_modeloauditoria_subcategorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='subcategoria',
            field=models.ForeignKey(blank=True, help_text='Sub-categoria / Sub-cláusula da pergunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='auditoria.subcategoriaauditoria', verbose_name='Sub-cláusula'),
        ),
    ]
