# Generated by Django 5.0.14 on 2026-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0028_alter_perguntaauditoria_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='alvo',
            field=models.CharField(blank=True, default='', help_text='Empresa, setor ou departamento alvo deste ciclo.', max_length=150, verbose_name='Alvo da Auditoria'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='nome',
            field=models.CharField(default='Ciclo de Auditoria', max_length=150, verbose_name='Nome do Ciclo'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='progresso',
            field=models.PositiveIntegerField(default=0, help_text='Progresso do ciclo em % (0 a 100).'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='data_auditoria',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Auditoria'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='item_os',
            field=models.CharField(blank=True, default='', help_text='Preencher se necessário para identificar ordens de serviço ou pontos específicos.', max_length=120, verbose_name='ITEM/O.S. (Legado)'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='periodo_fim',
            field=models.DateField(verbose_name='Período Final Previsto'),
        ),
    ]
