# Generated by Django 5.0.14 on 2026-08-11 19:11

from django.db import migrations

def migrate_legado_ciclos(apps, schema_editor):
    RegistroAuditoria = apps.get_model("auditoria", "RegistroAuditoria")
    
    for registro in RegistroAuditoria.objects.all():
        registro.status = "CONCLUIDO"
        registro.progresso = 100
        registro.alvo = registro.item_os or ""
        registro.nome = f"Ciclo - {registro.modelo.nome} - {registro.periodo_inicio.strftime('%d/%m/%Y')}"
        registro.save(update_fields=['status', 'progresso', 'alvo', 'nome'])

class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0029_registroauditoria_alvo_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legado_ciclos),
    ]
