# Generated by Django 5.0.14 on 2026-08-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0030_auto_20260811_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='subcategoria',
            field=models.ForeignKey(blank=True, help_text='Sub-categoria / Sub-cláusula da pergunta (Obsoleto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='auditoria.subcategoriaauditoria', verbose_name='Sub-cláusula'),
        ),
        migrations.CreateModel(
            name='TopicoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='auditoria.modeloauditoria', verbose_name='Modelo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='auditoria.topicoauditoria', verbose_name='Tópico Pai')),
            ],
            options={
                'verbose_name': 'Tópico de Auditoria',
                'verbose_name_plural': 'Tópicos de Auditoria',
                'ordering': ['modelo', 'parent__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='perguntaauditoria',
            name='topico',
            field=models.ForeignKey(blank=True, help_text='Tópico hierárquico da pergunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='auditoria.topicoauditoria', verbose_name='Tópico / Estrutura'),
        ),
    ]
