# Generated by Django 5.0.14 on 2026-08-11 19:42

from django.db import migrations


def migrate_data(apps, schema_editor):
    CategoriaAuditoria = apps.get_model('auditoria', 'CategoriaAuditoria')
    SubcategoriaAuditoria = apps.get_model('auditoria', 'SubcategoriaAuditoria')
    TopicoAuditoria = apps.get_model('auditoria', 'TopicoAuditoria')
    PerguntaAuditoria = apps.get_model('auditoria', 'PerguntaAuditoria')

    cat_to_topico = {}
    subcat_to_topico = {}

    for cat in CategoriaAuditoria.objects.all():
        topico = TopicoAuditoria.objects.create(
            modelo=cat.modelo,
            parent=None,
            nome=cat.nome,
            ordem=cat.ordem
        )
        cat_to_topico[cat.id] = topico

    for subcat in SubcategoriaAuditoria.objects.all():
        parent_topico = cat_to_topico.get(subcat.categoria_id)
        if parent_topico:
            topico = TopicoAuditoria.objects.create(
                modelo=parent_topico.modelo,
                parent=parent_topico,
                nome=subcat.nome,
                ordem=subcat.ordem
            )
            subcat_to_topico[subcat.id] = topico

    for pergunta in PerguntaAuditoria.objects.all():
        if pergunta.subcategoria_id:
            topico = subcat_to_topico.get(pergunta.subcategoria_id)
            if topico:
                pergunta.topico = topico
                pergunta.save(update_fields=['topico'])

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0031_add_topico_auditoria'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate),
    ]
