# Generated by Django 5.0.14 on 2026-08-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0032_migrate_data_topico_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoriaauditoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='perguntaauditoria',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='CategoriaAuditoria',
        ),
        migrations.DeleteModel(
            name='SubcategoriaAuditoria',
        ),
    ]
