# Generated by Django 5.0.14 on 2026-08-14 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0033_remove_old_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Norma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Código da Norma (ex: ISO 13485:2016)",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Norma",
                "verbose_name_plural": "Normas",
            },
        ),
        migrations.CreateModel(
            name="ItemNorma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        max_length=50, verbose_name="Referência (ex: 4.1.6)"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do Item"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição / Requisito"),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subitens",
                        to="auditoria.itemnorma",
                    ),
                ),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="auditoria.norma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Norma",
                "verbose_name_plural": "Itens da Norma",
                "ordering": ["norma", "referencia"],
            },
        ),
        migrations.CreateModel(
            name="BancoPergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_pergunta",
                    models.TextField(verbose_name="Pergunta (Linguagem Natural)"),
                ),
                (
                    "dica_auditor",
                    models.TextField(blank=True, verbose_name="Dicas / O que procurar"),
                ),
                ("ativa", models.BooleanField(default=True)),
                (
                    "itens_norma",
                    models.ManyToManyField(
                        related_name="perguntas_vinculadas",
                        to="auditoria.itemnorma",
                        verbose_name="Itens da Norma Avaliados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco de Pergunta (ISO)",
                "verbose_name_plural": "Banco de Perguntas (ISO)",
            },
        ),
        migrations.CreateModel(
            name="AuditoriaIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim Prevista")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADA", "Planejada"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="PLANEJADA",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "auditores",
                    models.ManyToManyField(
                        related_name="auditorias_iso_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auditores",
                    ),
                ),
                (
                    "escopo_itens",
                    models.ManyToManyField(
                        help_text="Itens da norma que serão avaliados nesta auditoria",
                        related_name="auditorias_escopo",
                        to="auditoria.itemnorma",
                        verbose_name="Escopo (Itens Aplicáveis)",
                    ),
                ),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias",
                        to="auditoria.norma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria (Modo Entrevista)",
                "verbose_name_plural": "Auditorias (Modo Entrevista)",
            },
        ),
        migrations.CreateModel(
            name="RespostaEntrevistaIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_resposta",
                    models.TextField(
                        blank=True, verbose_name="Resposta do Auditado / Anotações"
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("C", "Conforme"),
                            ("NC", "Não Conforme"),
                            ("NA", "Não Aplicável"),
                            ("OM", "Oportunidade de Melhoria"),
                            ("P", "Pendente"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                ("respondida_em", models.DateTimeField(auto_now=True)),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="auditoria.auditoriaiso",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respostas",
                        to="auditoria.bancopergunta",
                    ),
                ),
                (
                    "respondida_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta Entrevista ISO",
                "verbose_name_plural": "Respostas Entrevista ISO",
                "unique_together": {("auditoria", "pergunta")},
            },
        ),
    ]
