# Generated by Django
from django.db import migrations

ITEMS_DATA = [
    {
        "norma": "ISO 13485:2016",
        "referencia": "4",
        "titulo_item": "Sistema de gestão da qualidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1",
        "titulo_item": "Requisitos gerais"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1.1",
        "titulo_item": "A organização deve documentar um sistema de gestão da qualidade e manter sua eficácia"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1.2",
        "titulo_item": "A organização deve:"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1.3",
        "titulo_item": "Para cada processo do sistema de gestão da qualidade, a organização deve:"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1.4",
        "titulo_item": "A organização deve gerenciar estes processos do sistema de gestão da qualidade de acordo"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1.5",
        "titulo_item": "Quando uma organização optar por terceirizar algum processo que afete a conformidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.1.6",
        "titulo_item": "A organização deve documentar procedimentos para validação da aplicação de software"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.2",
        "titulo_item": "Requisitos de documentação"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.2.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.2.2",
        "titulo_item": "Manual da qualidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.2.3",
        "titulo_item": "Arquivo de produto para saúde"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.2.4",
        "titulo_item": "Controle de documentos"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "4.2.5",
        "titulo_item": "Controle de registros"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5",
        "titulo_item": "Responsabilidade da direção"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.1",
        "titulo_item": "Comprometimento da direção"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.2",
        "titulo_item": "Foco no cliente"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.3",
        "titulo_item": "Política da qualidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.4",
        "titulo_item": "Planejamento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.4.1",
        "titulo_item": "Objetivos da qualidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.4.2",
        "titulo_item": "Planejamento do sistema de gestão da qualidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.5",
        "titulo_item": "Responsabilidade, autoridade e comunicação"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.5.1",
        "titulo_item": "Responsabilidade e autoridade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.5.2",
        "titulo_item": "Representante da direção"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.5.3",
        "titulo_item": "Comunicação interna"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.6",
        "titulo_item": "Análise crítica pela direção"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.6.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.6.2",
        "titulo_item": "Entradas para a análise crítica"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "5.6.3",
        "titulo_item": "Saídas da análise crítica"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6",
        "titulo_item": "Gestão de recursos"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6.1",
        "titulo_item": "Provisão de recursos"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6.2",
        "titulo_item": "Recursos humanos"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6.3",
        "titulo_item": "Infraestrutura"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6.4",
        "titulo_item": "Ambiente de trabalho e controle de contaminação"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6.4.1",
        "titulo_item": "Ambiente de trabalho"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "6.4.2",
        "titulo_item": "Controle de contaminação"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7",
        "titulo_item": "Realização do produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.1",
        "titulo_item": "Planejamento da realização do produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.2",
        "titulo_item": "Processos relacionados a clientes"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.2.1",
        "titulo_item": "Determinação de requisitos relacionados ao produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.2.2",
        "titulo_item": "Análise crítica de requisitos relacionados ao produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.2.3",
        "titulo_item": "Comunicação com o cliente"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3",
        "titulo_item": "Projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.2",
        "titulo_item": "Planejamento de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.3",
        "titulo_item": "Entradas de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.4",
        "titulo_item": "Saídas de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.5",
        "titulo_item": "Análise crítica de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.6",
        "titulo_item": "Verificação de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.7",
        "titulo_item": "Validação de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.8",
        "titulo_item": "Transferência de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.9",
        "titulo_item": "Controle de mudanças de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.3.10",
        "titulo_item": "Arquivos de projeto e desenvolvimento"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.4",
        "titulo_item": "Aquisição"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.4.1",
        "titulo_item": "Processo de aquisição"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.4.2",
        "titulo_item": "Informações de aquisição"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.4.3",
        "titulo_item": "Verificação do produto adquirido"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5",
        "titulo_item": "Produção e prestação de serviço"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.1",
        "titulo_item": "Controle de produção e prestação de serviço"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.2",
        "titulo_item": "Limpeza de produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.3",
        "titulo_item": "Atividades de instalação"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.4",
        "titulo_item": "Atividades de serviço"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.5",
        "titulo_item": "Requisitos particulares para produtos para saúde estéreis"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.6",
        "titulo_item": "Validação de processos para produção e prestação de serviço"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.7",
        "titulo_item": "Requisitos particulares para validação de processos para esterilização e sistemas de barreira estéril"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.8",
        "titulo_item": "Identificação"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.9",
        "titulo_item": "Rastreabilidade"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.9.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.9.2",
        "titulo_item": "Requisitos particulares para produtos para saúde implantáveis"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.10",
        "titulo_item": "Propriedade do cliente"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.5.11",
        "titulo_item": "Preservação de produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "7.6",
        "titulo_item": "Controle de equipamento de monitoramento e medição"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8",
        "titulo_item": "Medição, análise e melhoria"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2",
        "titulo_item": "Monitoramento e medição"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2.1",
        "titulo_item": "Realimentação (feedback)"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2.2",
        "titulo_item": "Tratamento de reclamações"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2.3",
        "titulo_item": "Notificação às autoridades regulatórias"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2.4",
        "titulo_item": "Auditoria interna"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2.5",
        "titulo_item": "Monitoramento e medição de processos"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.2.6",
        "titulo_item": "Monitoramento e medição de produto"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.3",
        "titulo_item": "Controle de produto não conforme"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.3.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.3.2",
        "titulo_item": "Ações em resposta ao produto não conforme detectado antes da entrega"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.3.3",
        "titulo_item": "Ações em resposta ao produto não conforme detectado após a entrega"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.3.4",
        "titulo_item": "Retrabalho"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.4",
        "titulo_item": "Análise de dados"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.5",
        "titulo_item": "Melhoria"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.5.1",
        "titulo_item": "Geral"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.5.2",
        "titulo_item": "Ação corretiva"
    },
    {
        "norma": "ISO 13485:2016",
        "referencia": "8.5.3",
        "titulo_item": "Ação preventiva"
    }
]

def populate_iso_data(apps, schema_editor):
    Norma = apps.get_model('auditoria', 'Norma')
    ItemNorma = apps.get_model('auditoria', 'ItemNorma')

    norma_obj, _ = Norma.objects.get_or_create(
        codigo='ISO 13485:2016',
        defaults={'descricao': 'Sistemas de gestão da qualidade - Requisitos para fins regulamentares'}
    )

    instances_map = {}
    ordem_counter = 10

    for data in ITEMS_DATA:
        referencia = data['referencia']
        titulo = data['titulo_item']
        
        parts = referencia.split('.')
        parent_obj = None
        if len(parts) > 1:
            parent_ref = '.'.join(parts[:-1])
            parent_obj = instances_map.get(parent_ref)
            
        item_obj, _ = ItemNorma.objects.update_or_create(
            norma=norma_obj,
            referencia=referencia,
            defaults={
                'titulo': titulo,
                'parent': parent_obj,
                'ordem': ordem_counter
            }
        )
        
        instances_map[referencia] = item_obj
        ordem_counter += 10

def reverse_populate(apps, schema_editor):
    Norma = apps.get_model('auditoria', 'Norma')
    ItemNorma = apps.get_model('auditoria', 'ItemNorma')
    try:
        norma = Norma.objects.get(codigo='ISO 13485:2016')
        ItemNorma.objects.filter(norma=norma).delete()
        norma.delete()
    except Exception:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0034_norma_itemnorma_bancopergunta_auditoriaiso_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_iso_data, reverse_populate),
    ]
