# Generated by Django 5.0.14 on 2026-08-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0035_popular_iso13485_itens"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaAuditoriaIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título da Agenda"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendas",
                        to="auditoria.auditoriaiso",
                    ),
                ),
                (
                    "itens_norma",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agendas_vinculadas",
                        to="auditoria.itemnorma",
                        verbose_name="Itens da Norma Observados",
                    ),
                ),
                (
                    "perguntas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agendas_vinculadas",
                        to="auditoria.bancopergunta",
                        verbose_name="Perguntas Aplicáveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda de Auditoria",
                "verbose_name_plural": "Agendas de Auditoria",
                "ordering": ["criado_em"],
            },
        ),
    ]
