# Generated by Django 5.0.14 on 2026-08-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0036_agendaauditoriaiso"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="data",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Agenda"
            ),
        ),
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="hora_fim",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Término"
            ),
        ),
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="hora_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Início"
            ),
        ),
    ]
