# Generated by Django 5.0.14 on 2026-08-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0038_popular_iso13485_descricoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloAuditoriaIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do Modelo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição do Modelo"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_auditoria",
                        to="auditoria.norma",
                        verbose_name="Norma de Referência",
                    ),
                ),
                (
                    "perguntas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="modelos_vinculados",
                        to="auditoria.bancopergunta",
                        verbose_name="Perguntas do Modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Auditoria",
                "verbose_name_plural": "Modelos de Auditoria",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="modelo_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendas_instanciadas",
                to="auditoria.modeloauditoriaiso",
                verbose_name="Modelo Base",
            ),
        ),
    ]
