# Generated by Django 5.0.14 on 2026-08-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0039_modeloauditoriaiso_agendaauditoriaiso_modelo_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlocoModeloIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do Bloco"),
                ),
                ("ordem", models.IntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "itens_norma",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocos_modelo_vinculados",
                        to="auditoria.itemnorma",
                        verbose_name="Itens Alvo do Bloco",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocos",
                        to="auditoria.modeloauditoriaiso",
                        verbose_name="Modelo de Origem",
                    ),
                ),
                (
                    "perguntas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocos_modelo_vinculados",
                        to="auditoria.bancopergunta",
                        verbose_name="Perguntas do Bloco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloco de Modelo",
                "verbose_name_plural": "Blocos de Modelo",
                "ordering": ["ordem", "criado_em"],
            },
        ),
    ]
