# Generated by Django 5.0.14 on 2026-08-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0040_blocomodeloiso"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="arquivada",
            field=models.BooleanField(default=False, verbose_name="Arquivada"),
        ),
        migrations.AddField(
            model_name="auditoriaiso",
            name="arquivada",
            field=models.BooleanField(default=False, verbose_name="Arquivada"),
        ),
        migrations.AlterField(
            model_name="auditoriaiso",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANEJADA", "Planejada"),
                    ("EM_ANDAMENTO", "Em Andamento"),
                    ("CONCLUIDA", "Concluída"),
                    ("ARQUIVADA", "Arquivada"),
                ],
                default="PLANEJADA",
                max_length=20,
            ),
        ),
    ]
