# Generated by Django 5.0.14 on 2026-08-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auditoria",
            "0041_agendaauditoriaiso_arquivada_auditoriaiso_arquivada_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoEvidenciaIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solicitacao",
                    models.TextField(verbose_name="Solicitação / Item Solicitado"),
                ),
                (
                    "evidencia",
                    models.TextField(blank=True, verbose_name="Evidência Apresentada"),
                ),
                (
                    "conclusao",
                    models.CharField(
                        choices=[
                            ("C", "Conforme"),
                            ("NC", "Não Conforme"),
                            ("NA", "Não Aplicável"),
                            ("OM", "Oportunidade de Melhoria"),
                            ("P", "Pendente"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="auditoria.respostaentrevistaiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Evidência ISO",
                "verbose_name_plural": "Solicitações de Evidências ISO",
                "ordering": ["criado_em"],
            },
        ),
    ]
