# Generated by Django 5.0.14 on 2026-08-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0042_solicitacaoevidenciaiso"),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoSolicitacaoIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_solicitacao",
                    models.TextField(verbose_name="Solicitação / Item Solicitado"),
                ),
                (
                    "dica_evidencia",
                    models.TextField(
                        blank=True, verbose_name="Dicas de Evidência / O que verificar"
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "itens_norma",
                    models.ManyToManyField(
                        blank=True,
                        related_name="solicitacoes_modelo_vinculadas",
                        to="auditoria.itemnorma",
                        verbose_name="Itens da Norma Avaliados",
                    ),
                ),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banco_solicitacoes",
                        to="auditoria.norma",
                        verbose_name="Norma de Referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco de Solicitação de Evidência (ISO)",
                "verbose_name_plural": "Banco de Solicitações de Evidências (ISO)",
            },
        ),
        migrations.AddField(
            model_name="blocomodeloiso",
            name="solicitacoes",
            field=models.ManyToManyField(
                blank=True,
                related_name="blocos_modelo_vinculados",
                to="auditoria.bancosolicitacaoiso",
                verbose_name="Solicitações do Bloco",
            ),
        ),
        migrations.AddField(
            model_name="modeloauditoriaiso",
            name="solicitacoes",
            field=models.ManyToManyField(
                blank=True,
                related_name="modelos_vinculados",
                to="auditoria.bancosolicitacaoiso",
                verbose_name="Solicitações do Modelo",
            ),
        ),
    ]
