# Generated by Django 5.0.14 on 2026-08-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0043_bancosolicitacaoiso_blocomodeloiso_solicitacoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoriaiso",
            name="itens_nao_aplicaveis",
            field=models.ManyToManyField(
                blank=True,
                related_name="auditorias_nao_aplicaveis",
                to="auditoria.itemnorma",
                verbose_name="Itens Marcados como Não Aplicáveis",
            ),
        ),
    ]
