# Generated by Django 5.0.14 on 2026-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0044_auditoriaiso_itens_nao_aplicaveis"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemnorma",
            name="evidencia_padrao",
            field=models.TextField(
                blank=True, verbose_name="Evidências Esperadas (Padrão)"
            ),
        ),
        migrations.AddField(
            model_name="itemnorma",
            name="pergunta_padrao",
            field=models.TextField(blank=True, verbose_name="Pergunta Padrão"),
        ),
    ]
