# Generated by Django 5.0.14 on 2026-08-17 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0045_itemnorma_evidencia_padrao_itemnorma_pergunta_padrao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="auditores",
            field=models.ManyToManyField(
                blank=True,
                related_name="agendas_iso_alocadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auditores do Bloco",
            ),
        ),
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="representantes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Representantes do Local"
            ),
        ),
    ]
