# Generated by Django 5.0.14 on 2026-08-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0046_agendaauditoriaiso_auditores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="concluida",
            field=models.BooleanField(default=False, verbose_name="Etapa Concluída"),
        ),
    ]
