# Generated by Django 5.0.14 on 2026-08-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0047_agendaauditoriaiso_concluida"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="data_real",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Ajustada/Real"
            ),
        ),
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="hora_fim_real",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Término Ajustada"
            ),
        ),
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="hora_inicio_real",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Início Ajustada"
            ),
        ),
        migrations.AlterField(
            model_name="agendaauditoriaiso",
            name="data",
            field=models.DateField(blank=True, null=True, verbose_name="Data Prevista"),
        ),
        migrations.AlterField(
            model_name="agendaauditoriaiso",
            name="hora_fim",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Término Prevista"
            ),
        ),
        migrations.AlterField(
            model_name="agendaauditoriaiso",
            name="hora_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Início Prevista"
            ),
        ),
    ]
