# Generated by Django 5.0.14 on 2026-08-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0048_agendaauditoriaiso_data_real_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaauditoriaiso",
            name="auditores_nomes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Auditores (Texto Livre)"
            ),
        ),
    ]
