# Generated by Django 5.0.14 on 2026-08-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0049_agendaauditoriaiso_auditores_nomes"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoriaiso",
            name="abertura_auditores",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Auditores (Abertura)"
            ),
        ),
        migrations.AddField(
            model_name="auditoriaiso",
            name="abertura_representantes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Representantes (Abertura)"
            ),
        ),
        migrations.AddField(
            model_name="auditoriaiso",
            name="encerramento_auditores",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Auditores (Encerramento)"
            ),
        ),
        migrations.AddField(
            model_name="auditoriaiso",
            name="encerramento_representantes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Representantes (Encerramento)"
            ),
        ),
        migrations.AddField(
            model_name="auditoriaiso",
            name="revisao_auditores",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Auditores (Revisão)"
            ),
        ),
        migrations.AddField(
            model_name="auditoriaiso",
            name="revisao_representantes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Representantes (Revisão)"
            ),
        ),
    ]
