# Generated by Django 5.0.14 on 2026-08-17 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0050_auditoriaiso_abertura_auditores_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoFinalRequisitoIso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("C", "Conforme"),
                            ("NC", "Não Conforme"),
                            ("NA", "Não Aplicável"),
                            ("OM", "Oportunidade de Melhoria"),
                            ("P", "Pendente"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True,
                        verbose_name="Argumentação / Justificativa da Reversão",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_finais",
                        to="auditoria.auditoriaiso",
                    ),
                ),
                (
                    "item_norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_finais",
                        to="auditoria.itemnorma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação Final do Requisito ISO",
                "verbose_name_plural": "Avaliações Finais dos Requisitos ISO",
                "unique_together": {("auditoria", "item_norma")},
            },
        ),
    ]
