# Generated by Django on 2026-08-18 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0051_avaliacaofinalrequisitoiso"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaofinalrequisitoiso",
            name="grau_nc",
            field=models.CharField(
                blank=True,
                choices=[("MENOR", "NC Menor"), ("MAIOR", "NC Maior")],
                max_length=10,
                null=True,
                verbose_name="Grau da Não Conformidade",
            ),
        ),
        migrations.CreateModel(
            name="RegraVeredictoNorma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_resultado",
                    models.CharField(
                        choices=[
                            ("APTO", "Apto / Recomendado"),
                            ("RESSALVA", "Apto com Ressalvas"),
                            ("INAPTO", "Inapto / Não Recomendado"),
                        ],
                        max_length=15,
                        verbose_name="Status do Resultado",
                    ),
                ),
                (
                    "min_percentual_conformidade",
                    models.FloatField(
                        default=0.0,
                        help_text="Índice mínimo global exigido (ex: 95.0)",
                        verbose_name="% Mínimo de Conformidade",
                    ),
                ),
                (
                    "max_nc_maior",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Limite máximo tolerado",
                        verbose_name="Máx. NC Maior Permitida",
                    ),
                ),
                (
                    "max_nc_menor",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Limite máximo tolerado",
                        verbose_name="Máx. NC Menor Permitida",
                    ),
                ),
                (
                    "texto_parecer_padrao",
                    models.TextField(
                        blank=True,
                        help_text="Texto institucional que será exibido no slide de fechamento",
                        verbose_name="Parecer Padrão no Relatório",
                    ),
                ),
                (
                    "cor_badge",
                    models.CharField(
                        default="#198754",
                        help_text="Hexadecimal da cor (ex: #198754 para verde)",
                        max_length=20,
                        verbose_name="Cor do Badge",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_veredicto",
                        to="auditoria.norma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Veredicto da Norma",
                "verbose_name_plural": "Regras de Veredicto das Normas",
                "unique_together": {("norma", "status_resultado")},
            },
        ),
    ]
