# Generated by Django 5.0.14 on 2026-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0074_remover_perguntas_padrao_autocriadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='tipo_resposta',
            field=models.CharField(choices=[('SIM_NAO', 'Sim/Não'), ('LISTA', 'Lista (opções)'), ('NUMERO', 'Número inteiro'), ('DECIMAL', 'Número decimal'), ('TEXTO', 'Texto')], default='SIM_NAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perguntaavaliacaoauditoriso',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='regraveredictonorma',
            name='cor_badge',
            field=models.CharField(default='#198754', max_length=20, verbose_name='Cor Hexadecimal / CSS'),
        ),
        migrations.AlterField(
            model_name='regraveredictonorma',
            name='max_nc_maior',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd Máxima de NC Maior Tolerada'),
        ),
        migrations.AlterField(
            model_name='regraveredictonorma',
            name='max_nc_menor',
            field=models.PositiveIntegerField(default=2, verbose_name='Qtd Máxima de NC Menor Tolerada'),
        ),
        migrations.AlterField(
            model_name='regraveredictonorma',
            name='min_percentual_conformidade',
            field=models.FloatField(default=90.0, help_text='Abaixo deste percentual, o status não é concedido.', verbose_name='Índice Mínimo de Conformidade (%)'),
        ),
        migrations.AlterField(
            model_name='regraveredictonorma',
            name='status_resultado',
            field=models.CharField(choices=[('APTO', 'Apto (Recomendado)'), ('RESSALVA', 'Apto com Ressalvas'), ('INAPTO', 'Inapto / Não Conforme')], max_length=20, verbose_name='Status do Parecer'),
        ),
        migrations.AlterField(
            model_name='regraveredictonorma',
            name='texto_parecer_padrao',
            field=models.TextField(help_text='Texto institucional que será exibido no slide de fechamento.', verbose_name='Texto do Parecer Padrão no Relatório'),
        ),
    ]
