# Generated by Django 5.0.14 on 2026-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0075_alter_perguntaauditoria_tipo_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaauditoria',
            name='exibir_indicador_sessao',
            field=models.BooleanField(default=False, help_text='Se marcado, inclui as respostas desta pergunta no resumo de indicadores do cabeçalho da sessão.', verbose_name='Exibir indicador na sessão'),
        ),
    ]
