# Generated by Django 5.0.14 on 2026-09-03 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0076_perguntaauditoria_exibir_indicador_sessao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloauditoria',
            name='multiplos_registros',
            field=models.BooleanField(default=False, help_text='Se ativado, cada ciclo deste modelo permite cadastrar múltiplos registros amostrais das perguntas base, contabilizando o tempo de início e fim da amostragem.', verbose_name='Ciclo com múltiplos registros (amostral)'),
        ),
        migrations.AddField(
            model_name='perguntaauditoria',
            name='exibir_como_farol',
            field=models.BooleanField(default=True, help_text='Se marcado, a resposta será exibida como farol colorido. Quando desmarcado, exibe o resultado diretamente.', verbose_name='Exibir como Farol'),
        ),
        migrations.CreateModel(
            name='AmostraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Número da Amostra')),
                ('identificador', models.CharField(blank=True, default='', help_text='Opcional: código ou referência desta amostra.', max_length=120, verbose_name='Identificador / O.S. / Lote')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Registro')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador / Autor')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='auditoria.registroauditoria', verbose_name='Ciclo de Auditoria')),
            ],
            options={
                'verbose_name': 'Amostra de Auditoria',
                'verbose_name_plural': 'Amostras de Auditoria',
                'ordering': ['numero', 'criado_em'],
                'unique_together': {('registro', 'numero')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='respostaauditoria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respostaauditoria',
            name='amostra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='auditoria.amostraauditoria', verbose_name='Amostra (se ciclo amostral)'),
        ),
        migrations.AlterUniqueTogether(
            name='respostaauditoria',
            unique_together={('registro', 'pergunta', 'dia_semana', 'grid_item', 'amostra')},
        ),
    ]
