"""
Script para criar superusuário no Django via Railway
Execute este script localmente e ele te guiará no processo
"""

print("=" * 60)
print("CRIAR SUPERUSUÁRIO NO RAILWAY - CalibraWeb")
print("=" * 60)
print()
print("📋 OPÇÃO 1: Via Dashboard do Railway (RECOMENDADO)")
print("-" * 60)
print()
print("1. Acesse: https://railway.app/")
print("2. Abra seu projeto 'CalibraWeb'")
print("3. Clique no serviço 'Django Web' (não beat/worker)")
print("4. Clique em 'Settings' (ícone de engrenagem)")
print("5. Role até a seção 'Deploy' e procure por 'Shell' ou 'Terminal'")
print("6. Um terminal vai abrir no navegador")
print("7. Execute este comando:")
print()
print("   python manage.py createsuperuser")
print()
print("8. Preencha:")
print("   Username: admin")
print("   Email: admin@calibraweb.com")
print("   Password: [escolha uma senha forte]")
print()
print("=" * 60)
print()
print("📋 OPÇÃO 2: Via Variáveis de Ambiente + Redeploy")
print("-" * 60)
print()
print("1. Railway Dashboard → Serviço Django Web → Variables")
print("2. Adicione estas 3 variáveis:")
print()
print("   DJANGO_SUPERUSER_USERNAME=admin")
print("   DJANGO_SUPERUSER_EMAIL=admin@calibraweb.com")
print("   DJANGO_SUPERUSER_PASSWORD=SuaSenhaForte123!")
print()
print("3. Após adicionar, o Railway fará redeploy automático")
print("4. Acesse o terminal do Railway e execute:")
print()
print("   python manage.py shell -c \"")
print("   from django.contrib.auth import get_user_model;")
print("   User = get_user_model();")
print("   if not User.objects.filter(username='admin').exists():")
print("       User.objects.create_superuser('admin', 'admin@calibraweb.com', 'SuaSenhaForte123!')")
print("   \"")
print()
print("=" * 60)
print()
print("🎯 DEPOIS DE CRIAR:")
print("-" * 60)
print()
print("Acesse: https://calibraweb.up.railway.app/admin/")
print("Login com:")
print("  - Username: admin")
print("  - Password: [a senha que você escolheu]")
print()
print("=" * 60)
