# Generated by Django 5.0.14 on 2025-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
            },
        ),
        migrations.CreateModel(
            name="HierarquiaSetor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrativo"),
                            ("TURNO_1", "Turno 1"),
                            ("TURNO_2", "Turno 2"),
                            ("TURNO_3", "Turno 3"),
                            ("12X36", "12x36"),
                        ],
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hierarquia",
                "verbose_name_plural": "Hierarquia (Setor x Turno)",
            },
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Setor"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Responsável Genérico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Cadastro de Setores",
                "ordering": ["nome"],
            },
        ),
    ]
