# Generated by Django 5.0.14 on 2025-12-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hierarquiasetor",
            name="diretor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diretoria_setor",
                to="rh.colaborador",
                verbose_name="Diretor",
            ),
        ),
        migrations.AddField(
            model_name="hierarquiasetor",
            name="gerente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gerenciados_setor",
                to="rh.colaborador",
                verbose_name="Gerente",
            ),
        ),
        migrations.AddField(
            model_name="hierarquiasetor",
            name="lider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liderados_setor",
                to="rh.colaborador",
                verbose_name="Líder",
            ),
        ),
        migrations.AddField(
            model_name="hierarquiasetor",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisionados_setor",
                to="rh.colaborador",
                verbose_name="Supervisor",
            ),
        ),
        migrations.AddField(
            model_name="hierarquiasetor",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.setor",
                verbose_name="Setor",
            ),
        ),
        migrations.AddField(
            model_name="centrocusto",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centros_custo",
                to="organization.setor",
                verbose_name="Setor Pertencente",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hierarquiasetor",
            unique_together={("setor", "turno")},
        ),
        migrations.AlterUniqueTogether(
            name="centrocusto",
            unique_together={("setor", "codigo")},
        ),
    ]
