# Generated by Django 5.0.14 on 2025-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnidadeMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Unidade de Medida"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "ordering": ["nome"],
            },
        ),
    ]
