# Generated by Copilot on 2026-03-05

from __future__ import annotations

from django.db import migrations


def create_nav_action_permissions(apps, schema_editor):
    """Cria permissões derivadas para edição e exclusão a partir de core.nav_*.

    Convenção:
    - perm base (visualizar/acessar): nav_x
    - editar: nav_x_edit
    - deletar: nav_x_delete

    Observação: não removemos nada; apenas garantimos que existam.
    """

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    try:
        ct = ContentType.objects.get(app_label="core", model="navigationpermission")
    except ContentType.DoesNotExist:
        return

    # Import local (fora do apps registry) apenas para ler a NAV_STRUCTURE.
    try:
        from shared.permissions import NAV_STRUCTURE  # noqa: WPS433
    except Exception:
        NAV_STRUCTURE = []

    def _iter_full_perms():
        for module in NAV_STRUCTURE or []:
            yield module.get("module_perm")
            for bloco in module.get("blocos") or []:
                yield bloco.get("perm")
                for func in bloco.get("funcoes") or []:
                    yield func.get("perm")

    base_codenames: set[str] = set()
    for full_perm in _iter_full_perms():
        if not full_perm or "." not in str(full_perm):
            continue
        app_label, codename = str(full_perm).split(".", 1)
        if app_label != "core":
            continue
        if codename.startswith("nav_"):
            base_codenames.add(codename)

    if not base_codenames:
        return

    base_perms = {
        p.codename: p
        for p in Permission.objects.filter(content_type=ct, codename__in=sorted(base_codenames))
    }

    for codename in sorted(base_codenames):
        base_name = base_perms.get(codename).name if codename in base_perms else f"NAV: {codename}"

        for suffix, label in (("_edit", "Editar"), ("_delete", "Deletar")):
            derived_codename = f"{codename}{suffix}"
            derived_name = f"{base_name} ({label})"

            Permission.objects.get_or_create(
                content_type=ct,
                codename=derived_codename,
                defaults={"name": derived_name},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_navigationpermission_treinamentos_acompanhamento_calendario"),
    ]

    operations = [
        migrations.RunPython(create_nav_action_permissions, migrations.RunPython.noop),
    ]
