"""Reestruturação das permissões de navegação: 1 bloco por tela em todos os módulos.

- Cria as permissões novas (blocos por tela, ações que antes não tinham permissão própria,
  permissões especiais) e as 3 que apareciam no painel sem existir no banco.
- Preserva o acesso atual: cada permissão nova é concedida a quem tinha a permissão que
  cobria aquela view/ação antes da mudança; em seguida, cada bloco é concedido a quem tem
  alguma função dele (o painel descarta funções de blocos desligados ao salvar).
- Remove permissões órfãs (módulo Ações Corretivas e blocos extintos).

Os dicionários abaixo são um retrato congelado da estrutura na data da migration
(não importar shared.permissions aqui: ela vai continuar evoluindo).
"""
from django.db import migrations

PERM_NAMES = {'nav_auditoria_admin': 'NAV: Auditoria / Permissão Especial: Administrador de Auditoria',
 'nav_auditoria_analise': 'NAV: Auditoria / Bloco Análise',
 'nav_auditoria_avaliacao': 'NAV: Auditoria / Avaliação de Dados',
 'nav_auditoria_cadastro': 'NAV: Auditoria / Bloco Cadastro',
 'nav_auditoria_comentario_delete': 'NAV: Auditoria / Remover Comentário',
 'nav_auditoria_comentario_edit': 'NAV: Auditoria / Editar Comentário',
 'nav_auditoria_dashboard': 'NAV: Auditoria / Dashboard',
 'nav_auditoria_detalhe_registro': 'NAV: Auditoria / Detalhe do Registro',
 'nav_auditoria_duplicar_modelo': 'NAV: Auditoria / Duplicar Modelo',
 'nav_auditoria_duplicar_pergunta': 'NAV: Auditoria / Duplicar Pergunta',
 'nav_auditoria_editar_modelo': 'NAV: Auditoria / Editar Modelo',
 'nav_auditoria_editar_pergunta': 'NAV: Auditoria / Editar Pergunta',
 'nav_auditoria_editar_registro': 'NAV: Auditoria / Editar Registro',
 'nav_auditoria_encerrar_modelo': 'NAV: Auditoria / Encerrar/Arquivar Modelo',
 'nav_auditoria_excluir_registro': 'NAV: Auditoria / Excluir Registro',
 'nav_auditoria_exportar_excel': 'NAV: Auditoria / Exportar Respostas (Excel)',
 'nav_auditoria_exportar_pdf': 'NAV: Auditoria / Exportar Registro (PDF)',
 'nav_auditoria_iso_agendas': 'NAV: Auditoria / ISO 13485 - Planejamento e Agendas ISO',
 'nav_auditoria_iso_agendas_delete': 'NAV: Auditoria / Arquivar/Excluir Auditorias e Agendas ISO',
 'nav_auditoria_iso_amostras': 'NAV: Auditoria / ISO 13485 - Gestão de Amostras',
 'nav_auditoria_iso_analytics': 'NAV: Auditoria / ISO 13485 - Analytics Global',
 'nav_auditoria_iso_avaliacao': 'NAV: Auditoria / ISO 13485 - Avaliação do Auditor',
 'nav_auditoria_iso_avaliacao_excluir': 'NAV: Auditoria / Permissão Especial: Excluir Avaliação do Auditor '
                                        '(ISO)',
 'nav_auditoria_iso_bloco': 'NAV: Auditoria / Bloco ISO 13485 - Auditorias & Ferramentas',
 'nav_auditoria_iso_capa': 'NAV: Auditoria / ISO 13485 - Planos de Ação (CAPA)',
 'nav_auditoria_iso_cronograma': 'NAV: Auditoria / ISO 13485 - Cronograma & Horários',
 'nav_auditoria_iso_entrevista': 'NAV: Auditoria / ISO 13485 - Execução da Entrevista',
 'nav_auditoria_iso_export': 'NAV: Auditoria / ISO 13485 - Exportar Relatórios (Excel/Word)',
 'nav_auditoria_iso_fechamento': 'NAV: Auditoria / ISO 13485 - Apresentação de Fechamento',
 'nav_auditoria_iso_itens': 'NAV: Auditoria / ISO 13485 - Itens da Norma',
 'nav_auditoria_iso_itens_bloco': 'NAV: Auditoria / Bloco Setup: Itens da Norma',
 'nav_auditoria_iso_itens_delete': 'NAV: Auditoria / Excluir Item da Norma',
 'nav_auditoria_iso_lista': 'NAV: Auditoria / ISO 13485 - Modo Entrevista (Lista)',
 'nav_auditoria_iso_matriz': 'NAV: Auditoria / ISO 13485 - Matriz de Correlação',
 'nav_auditoria_iso_modelos': 'NAV: Auditoria / ISO 13485 - Modelos e Blocos ISO',
 'nav_auditoria_iso_modelos_bloco': 'NAV: Auditoria / Bloco Setup: Modelos e Blocos ISO',
 'nav_auditoria_iso_modelos_delete': 'NAV: Auditoria / Arquivar/Excluir Modelos e Blocos ISO',
 'nav_auditoria_iso_normas': 'NAV: Auditoria / ISO 13485 - Normas ISO e Requisitos',
 'nav_auditoria_iso_normas_bloco': 'NAV: Auditoria / Bloco Setup: Normas ISO',
 'nav_auditoria_iso_normas_delete': 'NAV: Auditoria / Arquivar/Excluir Norma',
 'nav_auditoria_iso_perguntas': 'NAV: Auditoria / ISO 13485 - Banco de Perguntas ISO',
 'nav_auditoria_iso_perguntas_bloco': 'NAV: Auditoria / Bloco Setup: Banco de Perguntas ISO',
 'nav_auditoria_iso_perguntas_delete': 'NAV: Auditoria / Excluir Pergunta ISO',
 'nav_auditoria_iso_revisao': 'NAV: Auditoria / ISO 13485 - Painel de Revisão',
 'nav_auditoria_iso_setup': 'NAV: Auditoria / ISO 13485 - Painel de Setup',
 'nav_auditoria_iso_setup_bloco': 'NAV: Auditoria / Bloco ISO 13485 - Setup & Cadastros',
 'nav_auditoria_iso_sintese': 'NAV: Auditoria / ISO 13485 - Síntese da Auditoria',
 'nav_auditoria_iso_solicitacoes': 'NAV: Auditoria / Solicitações e Evidências',
 'nav_auditoria_justificar_nao_execucao': 'NAV: Auditoria / Justificar Não Execução',
 'nav_auditoria_modelo_topicos': 'NAV: Auditoria / Tópicos do Modelo',
 'nav_auditoria_modelos': 'NAV: Auditoria / Modelos de Auditoria',
 'nav_auditoria_nova': 'NAV: Auditoria / Nova Auditoria',
 'nav_auditoria_nova_bloco': 'NAV: Auditoria / Bloco Nova Auditoria',
 'nav_auditoria_nova_pergunta': 'NAV: Auditoria / Nova Pergunta',
 'nav_auditoria_novo_modelo': 'NAV: Auditoria / Novo Modelo',
 'nav_auditoria_operacao': 'NAV: Auditoria / Bloco Operação',
 'nav_auditoria_perguntas': 'NAV: Auditoria / Perguntas por Modelo',
 'nav_auditoria_perguntas_bloco': 'NAV: Auditoria / Bloco Perguntas por Modelo',
 'nav_auditoria_perguntas_massa': 'NAV: Auditoria / Ações em Massa (Tópico, Resposta)',
 'nav_auditoria_registros': 'NAV: Auditoria / Modelos Cadastrados / Período',
 'nav_auditoria_registros_por_modelo': 'NAV: Auditoria / Registros por Modelo',
 'nav_auditoria_remover_modelo': 'NAV: Auditoria / Remover Modelo',
 'nav_auditoria_remover_pergunta': 'NAV: Auditoria / Remover Pergunta',
 'nav_boards_archive': 'NAV: Quadros / Arquivar Quadro',
 'nav_boards_create': 'NAV: Quadros / Criar Quadro',
 'nav_boards_dashboard': 'NAV: Quadros / Acessar Dashboard',
 'nav_boards_detail': 'NAV: Quadros / Detalhe de Quadro',
 'nav_boards_edit': 'NAV: Quadros / Editar Quadro',
 'nav_boards_gerenciar_todos': 'NAV: Quadros / Permissão Especial: Gerenciar Todos os Quadros',
 'nav_boards_gestao': 'NAV: Quadros / Bloco Gestão',
 'nav_boards_visao_geral': 'NAV: Quadros / Bloco Visão Geral',
 'nav_fornecedores_avaliacao': 'NAV: Fornecedores / Bloco Avaliação',
 'nav_fornecedores_avaliacao_create': 'NAV: Fornecedores / Nova Avaliação',
 'nav_fornecedores_avaliacao_edit': 'NAV: Fornecedores / Editar Avaliação',
 'nav_fornecedores_avaliacao_matriz': 'NAV: Fornecedores / Criar Matriz de Avaliação',
 'nav_fornecedores_avaliacao_selecao': 'NAV: Fornecedores / Criar Seleção',
 'nav_fornecedores_avaliacoes': 'NAV: Fornecedores / Avaliações e Reavaliações',
 'nav_fornecedores_documento_create': 'NAV: Fornecedores / Novo Documento',
 'nav_fornecedores_documento_delete': 'NAV: Fornecedores / Remover Documento',
 'nav_fornecedores_editar': 'NAV: Fornecedores / Editar Fornecedor',
 'nav_fornecedores_export_avaliacoes': 'NAV: Fornecedores / Exportar Avaliações (Excel)',
 'nav_fornecedores_gestao': 'NAV: Fornecedores / Bloco Gestão',
 'nav_fornecedores_lista': 'NAV: Fornecedores / Lista de Fornecedores',
 'nav_fornecedores_novo': 'NAV: Fornecedores / Novo Fornecedor',
 'nav_fornecedores_pergunta_create': 'NAV: Fornecedores / Nova Pergunta',
 'nav_fornecedores_pergunta_delete': 'NAV: Fornecedores / Remover Pergunta',
 'nav_fornecedores_pergunta_edit': 'NAV: Fornecedores / Editar Pergunta',
 'nav_fornecedores_perguntas': 'NAV: Fornecedores / Perguntas de Avaliação',
 'nav_fornecedores_perguntas_bloco': 'NAV: Fornecedores / Bloco Perguntas de Avaliação',
 'nav_fornecedores_reavaliacao_create': 'NAV: Fornecedores / Nova Reavaliação',
 'nav_fornecedores_reavaliacao_delete': 'NAV: Fornecedores / Deletar Reavaliação',
 'nav_global_action_buttons': 'NAV: Global / Exibir Botões de Ações em Tabelas',
 'nav_laboratorio_categoria_create': 'NAV: Laboratório / Nova Categoria',
 'nav_laboratorio_categoria_maquina_create': 'NAV: Laboratório / Nova Categoria de Máquina',
 'nav_laboratorio_categoria_maquina_delete': 'NAV: Laboratório / Excluir Categoria de Máquina',
 'nav_laboratorio_categoria_maquina_update': 'NAV: Laboratório / Editar Categoria de Máquina',
 'nav_laboratorio_categoria_update': 'NAV: Laboratório / Editar Categoria',
 'nav_laboratorio_categorias': 'NAV: Laboratório / Tabela de Categorias',
 'nav_laboratorio_categorias_bloco': 'NAV: Laboratorio / Bloco Categorias de Ocorrência',
 'nav_laboratorio_coating': 'NAV: Laboratório / Bloco Coating (Anti-Reflexo)',
 'nav_laboratorio_coating_ciclo_copy': 'NAV: Laboratorio / Copiar Ciclos',
 'nav_laboratorio_coating_ciclo_create': 'NAV: Laboratorio / Novo Ciclo',
 'nav_laboratorio_coating_ciclo_delete': 'NAV: Laboratorio / Excluir Ciclo',
 'nav_laboratorio_coating_ciclo_update': 'NAV: Laboratorio / Editar Ciclo (Checklist, Ordem, Ativação)',
 'nav_laboratorio_coating_ciclos': 'NAV: Laboratório / Coating / Ciclos de Manutenção',
 'nav_laboratorio_coating_ciclos_bloco': 'NAV: Laboratorio / Bloco Coating: Ciclos de Manutenção',
 'nav_laboratorio_coating_dashboard': 'NAV: Laboratório / Coating / Dashboard',
 'nav_laboratorio_coating_dashboard_bloco': 'NAV: Laboratorio / Bloco Coating: Dashboard',
 'nav_laboratorio_coating_equipe': 'NAV: Laboratório / Coating / Equipe Coating',
 'nav_laboratorio_coating_equipe_bloco': 'NAV: Laboratorio / Bloco Coating: Equipe',
 'nav_laboratorio_coating_equipe_delete': 'NAV: Laboratorio / Excluir Membro da Equipe',
 'nav_laboratorio_coating_equipe_update': 'NAV: Laboratorio / Editar Membro da Equipe',
 'nav_laboratorio_coating_importacao': 'NAV: Laboratório / Coating / Importação',
 'nav_laboratorio_coating_importacao_bloco': 'NAV: Laboratorio / Bloco Coating: Importação',
 'nav_laboratorio_coating_painel': 'NAV: Laboratório / Coating / Painel Diário',
 'nav_laboratorio_coating_painel_editar': 'NAV: Laboratorio / Editar Lançamentos (Células, Lotes, '
                                          'Observações, Manutenções)',
 'nav_laboratorio_coating_recalcular_todos': 'NAV: Laboratorio / Permissão Especial: Recalcular Turnos de '
                                             'Todos os Lotes',
 'nav_laboratorio_coating_registro_delete': 'NAV: Laboratorio / Excluir Lote',
 'nav_laboratorio_coating_tratamento_create': 'NAV: Laboratorio / Novo Tratamento',
 'nav_laboratorio_coating_tratamento_update': 'NAV: Laboratorio / Editar Tratamento',
 'nav_laboratorio_coating_tratamentos': 'NAV: Laboratório / Coating / Tratamentos',
 'nav_laboratorio_coating_tratamentos_bloco': 'NAV: Laboratorio / Bloco Coating: Tratamentos',
 'nav_laboratorio_coating_turno_create': 'NAV: Laboratorio / Nova Regra de Turno',
 'nav_laboratorio_coating_turno_update': 'NAV: Laboratorio / Editar Regra de Turno',
 'nav_laboratorio_coating_turnos': 'NAV: Laboratório / Coating / Regras de Turno',
 'nav_laboratorio_coating_turnos_bloco': 'NAV: Laboratorio / Bloco Coating: Regras de Turno',
 'nav_laboratorio_dashboard': 'NAV: Laboratório / Dashboard',
 'nav_laboratorio_dashboard_bloco': 'NAV: Laboratorio / Bloco Dashboard Laboratório',
 'nav_laboratorio_dashboard_pdf': 'NAV: Laboratorio / Exportar Dashboard (PDF)',
 'nav_laboratorio_editar_ocorrencia': 'NAV: Laboratório / Editar Ocorrência',
 'nav_laboratorio_encerrar_qualquer_ocorrencia': 'NAV: Laboratorio / Permissão Especial: Encerrar Ocorrência '
                                                 'de Qualquer Usuário',
 'nav_laboratorio_lista_ocorrencias': 'NAV: Laboratório / Listagem de Ocorrências',
 'nav_laboratorio_maquina_create': 'NAV: Laboratório / Nova Máquina',
 'nav_laboratorio_maquina_delete': 'NAV: Laboratório / Excluir Máquina',
 'nav_laboratorio_maquina_update': 'NAV: Laboratório / Editar Máquina',
 'nav_laboratorio_maquinas': 'NAV: Laboratório / Bloco Máquinas',
 'nav_laboratorio_maquinas_categorias': 'NAV: Laboratório / Categorias de Máquinas',
 'nav_laboratorio_maquinas_categorias_bloco': 'NAV: Laboratorio / Bloco Categorias de Máquinas',
 'nav_laboratorio_maquinas_lista': 'NAV: Laboratório / Cadastro de Máquinas',
 'nav_laboratorio_modulo': 'NAV: Laboratório / Módulo',
 'nav_laboratorio_nova_ocorrencia': 'NAV: Laboratório / Nova Ocorrência',
 'nav_laboratorio_ocorrencia_anotar': 'NAV: Laboratorio / Registrar Anotações',
 'nav_laboratorio_ocorrencia_delete': 'NAV: Laboratorio / Excluir Ocorrência',
 'nav_laboratorio_ocorrencia_detalhe': 'NAV: Laboratorio / Detalhe da Ocorrência',
 'nav_laboratorio_ocorrencia_encerrar': 'NAV: Laboratorio / Encerrar Ocorrência',
 'nav_laboratorio_ocorrencias_bloco': 'NAV: Laboratorio / Bloco Ocorrências',
 'nav_laboratorio_ocorrencias_gerais': 'NAV: Laboratório / Bloco Ocorrências Gerais',
 'nav_metrologia_aplicar_carimbo_certificado': 'NAV: Metrologia / Certificado (Aplicar Carimbo)',
 'nav_metrologia_atendimento_confirmar': 'NAV: Metrologia / Confirmar Atendimento',
 'nav_metrologia_atendimento_create': 'NAV: Metrologia / Novo Atendimento',
 'nav_metrologia_atendimento_update': 'NAV: Metrologia / Atualizar Atendimento (Dados, Cotação, Datas, '
                                      'Chegada, Rastreio)',
 'nav_metrologia_atualizar_datas_massa': 'NAV: Metrologia / Atualizar Datas de Calibração em Massa',
 'nav_metrologia_categoria_bulk_update': 'NAV: Metrologia / Atualizações em Massa (Categoria)',
 'nav_metrologia_categoria_create': 'NAV: Metrologia / Nova Categoria',
 'nav_metrologia_categoria_delete': 'NAV: Metrologia / Deletar Categoria',
 'nav_metrologia_categoria_update': 'NAV: Metrologia / Editar Categoria',
 'nav_metrologia_categorias': 'NAV: Metrologia / Categorias',
 'nav_metrologia_categorias_bloco': 'NAV: Metrologia / Bloco Categorias',
 'nav_metrologia_cotacao_fornecedor_create': 'NAV: Metrologia / Nova Cotação (Fornecedor)',
 'nav_metrologia_cotacao_fornecedor_update': 'NAV: Metrologia / Editar Cotação (Fornecedor)',
 'nav_metrologia_cotacoes': 'NAV: Metrologia / Bloco Cotações',
 'nav_metrologia_dashboard': 'NAV: Metrologia / Dashboard',
 'nav_metrologia_detalhe_instrumento': 'NAV: Metrologia / Detalhe do Instrumento',
 'nav_metrologia_download_arquivo_padrao': 'NAV: Metrologia / Arquivo Padrão (Download)',
 'nav_metrologia_download_certificado': 'NAV: Metrologia / Certificado (Download)',
 'nav_metrologia_editar_historico': 'NAV: Metrologia / Editar Histórico de Calibração',
 'nav_metrologia_editar_instrumento': 'NAV: Metrologia / Editar Instrumento',
 'nav_metrologia_estatisticas': 'NAV: Metrologia / Estatísticas de Calibração',
 'nav_metrologia_etiquetas_bloco': 'NAV: Metrologia / Bloco Modelos de Etiquetas',
 'nav_metrologia_export_estatisticas': 'NAV: Metrologia / Exportar Estatísticas',
 'nav_metrologia_export_etiquetas': 'NAV: Metrologia / Exportar Etiquetas',
 'nav_metrologia_export_instrumentos': 'NAV: Metrologia / Exportar Instrumentos',
 'nav_metrologia_faixa_categoria_create': 'NAV: Metrologia / Nova Faixa (Categoria)',
 'nav_metrologia_faixa_categoria_delete': 'NAV: Metrologia / Deletar Faixa (Categoria)',
 'nav_metrologia_faixa_categoria_update': 'NAV: Metrologia / Editar Faixa (Categoria)',
 'nav_metrologia_faixa_instrumento_add': 'NAV: Metrologia / Aplicar Faixa a Instrumentos',
 'nav_metrologia_faixa_instrumento_bulk_delete': 'NAV: Metrologia / Remover Faixa-Instrumento em Massa',
 'nav_metrologia_faixa_instrumento_delete': 'NAV: Metrologia / Remover Faixa-Instrumento',
 'nav_metrologia_faixa_instrumento_replace': 'NAV: Metrologia / Substituir Faixa-Instrumento (Individual e '
                                             'em Massa)',
 'nav_metrologia_gestao': 'NAV: Metrologia / Bloco Gestão',
 'nav_metrologia_historicos_bloco': 'NAV: Metrologia / Bloco Históricos de Calibração',
 'nav_metrologia_historicos_calibracao': 'NAV: Metrologia / Históricos de Calibração',
 'nav_metrologia_import_jobs': 'NAV: Metrologia / Acompanhar Importações (Jobs)',
 'nav_metrologia_importar_historico': 'NAV: Metrologia / Importar Histórico',
 'nav_metrologia_importar_instrumentos': 'NAV: Metrologia / Importar Instrumentos',
 'nav_metrologia_instrumento_bulk_change_category': 'NAV: Metrologia / Alterar Categoria de Instrumentos em '
                                                    'Massa',
 'nav_metrologia_item_solicitacao_delete': 'NAV: Metrologia / Deletar Item da Solicitação',
 'nav_metrologia_item_solicitacao_edit': 'NAV: Metrologia / Editar Item da Solicitação',
 'nav_metrologia_lista_instrumentos': 'NAV: Metrologia / Lista de Instrumentos',
 'nav_metrologia_novo_instrumento': 'NAV: Metrologia / Novo Instrumento',
 'nav_metrologia_ocorrencia_editar': 'NAV: Metrologia / Editar/Encerrar Ocorrência do Instrumento',
 'nav_metrologia_ocorrencia_excluir': 'NAV: Metrologia / Excluir Ocorrência do Instrumento',
 'nav_metrologia_ocorrencia_registrar': 'NAV: Metrologia / Registrar Ocorrência do Instrumento',
 'nav_metrologia_registrar_historico': 'NAV: Metrologia / Registrar Histórico de Calibração',
 'nav_metrologia_registrar_historico_massa': 'NAV: Metrologia / Registrar Históricos em Massa',
 'nav_metrologia_relatorio_vencidos': 'NAV: Metrologia / Relatório de Vencidos',
 'nav_metrologia_remover_arquivo_padrao': 'NAV: Metrologia / Arquivo Padrão (Remover)',
 'nav_metrologia_remover_carimbo_certificado': 'NAV: Metrologia / Certificado (Remover Carimbo)',
 'nav_metrologia_remover_certificado_historico': 'NAV: Metrologia / Certificado (Remover)',
 'nav_metrologia_remover_historico': 'NAV: Metrologia / Remover Histórico de Calibração',
 'nav_metrologia_solicitacao_create': 'NAV: Metrologia / Nova Solicitação de Cotação',
 'nav_metrologia_solicitacao_delete': 'NAV: Metrologia / Deletar Solicitação de Cotação',
 'nav_metrologia_solicitacao_status': 'NAV: Metrologia / Alterar Status (Concluir, Cancelar, Reabrir, '
                                      'Reativar)',
 'nav_metrologia_solicitacao_update': 'NAV: Metrologia / Editar Solicitação de Cotação',
 'nav_metrologia_solicitacoes_cotacao': 'NAV: Metrologia / Solicitações de Cotação',
 'nav_metrologia_substituir_instrumento': 'NAV: Metrologia / Substituir Instrumento',
 'nav_metrologia_template_etiqueta_delete': 'NAV: Metrologia / Excluir Modelo',
 'nav_metrologia_template_etiqueta_toggle': 'NAV: Metrologia / Ativar/Desativar Modelo',
 'nav_metrologia_template_etiqueta_upload': 'NAV: Metrologia / Enviar Modelo',
 'nav_metrologia_templates_etiquetas': 'NAV: Metrologia / Modelos de Etiquetas',
 'nav_metrologia_unidade_create': 'NAV: Metrologia / Nova Unidade de Medida',
 'nav_metrologia_unidade_delete': 'NAV: Metrologia / Deletar Unidade de Medida',
 'nav_metrologia_unidade_update': 'NAV: Metrologia / Editar Unidade de Medida',
 'nav_metrologia_unidades_bloco': 'NAV: Metrologia / Bloco Unidades de Medida',
 'nav_metrologia_unidades_medida': 'NAV: Metrologia / Unidades de Medida',
 'nav_metrologia_visao_geral': 'NAV: Metrologia / Bloco Visão Geral',
 'nav_metrologia_visualizar_historico': 'NAV: Metrologia / Visualizar Histórico de Calibração',
 'nav_mod_auditoria': 'NAV: Módulo Auditoria',
 'nav_mod_boards': 'NAV: Módulo Quadros',
 'nav_mod_fornecedores': 'NAV: Módulo Fornecedores',
 'nav_mod_laboratorio': 'NAV: Módulo Laboratório',
 'nav_mod_metrologia': 'NAV: Módulo Metrologia',
 'nav_mod_pessoas': 'NAV: Módulo Pessoas',
 'nav_mod_treinamentos': 'NAV: Módulo Treinamentos',
 'nav_mod_usuarios': 'NAV: Módulo Usuários',
 'nav_pessoas_api_delete_colaborador': 'NAV: Pessoas / Deletar Colaborador (API)',
 'nav_pessoas_api_delete_colaboradores_multiple': 'NAV: Pessoas / Deletar Colaboradores em Massa (API)',
 'nav_pessoas_arquivar_demanda': 'NAV: Pessoas / Arquivar/Desarquivar Demanda de Ponto',
 'nav_pessoas_colaboradores': 'NAV: Pessoas / Colaboradores',
 'nav_pessoas_deletar_ocorrencia': 'NAV: Pessoas / Deletar Ocorrência',
 'nav_pessoas_demandas_falhas_ponto': 'NAV: Pessoas / Demandas & Cobranças de Ponto',
 'nav_pessoas_detalhe_colaborador': 'NAV: Pessoas / Detalhe do Colaborador',
 'nav_pessoas_editar_colaborador': 'NAV: Pessoas / Editar Colaborador',
 'nav_pessoas_editar_ferias': 'NAV: Pessoas / Editar Férias',
 'nav_pessoas_editar_ocorrencia': 'NAV: Pessoas / Editar Ocorrência',
 'nav_pessoas_equipe': 'NAV: Pessoas / Bloco Equipe',
 'nav_pessoas_excluir_demanda': 'NAV: Pessoas / Excluir Demanda de Ponto (Permanente)',
 'nav_pessoas_excluir_ferias': 'NAV: Pessoas / Excluir Férias',
 'nav_pessoas_exportar_ferias': 'NAV: Pessoas / Exportar Férias',
 'nav_pessoas_ferias_bloco': 'NAV: Pessoas / Bloco Gestão de Férias',
 'nav_pessoas_ferias_configuracao': 'NAV: Pessoas / Permissão Especial: Configurar Meses de Abono e '
                                    'Adiantamento de 13º',
 'nav_pessoas_ferias_status': 'NAV: Pessoas / Atualizar Status das Férias',
 'nav_pessoas_ferias_vencimentos': 'NAV: Pessoas / Vencimentos de Férias (Criar/Excluir)',
 'nav_pessoas_gestao_ferias': 'NAV: Pessoas / Gestão de Férias',
 'nav_pessoas_horas_extras': 'NAV: Pessoas / Bloco Horas Extras',
 'nav_pessoas_horas_extras_create': 'NAV: Pessoas / Novo Planejamento',
 'nav_pessoas_horas_extras_delete': 'NAV: Pessoas / Excluir Planejamento',
 'nav_pessoas_horas_extras_edit': 'NAV: Pessoas / Editar Planejamento',
 'nav_pessoas_horas_extras_list': 'NAV: Pessoas / Planejamento de Horas Extras',
 'nav_pessoas_horas_extras_motivos': 'NAV: Pessoas / Motivos de Planejamento',
 'nav_pessoas_importar_falhas_ponto': 'NAV: Pessoas / Importar Relatório de Falhas de Ponto',
 'nav_pessoas_importar_ferias': 'NAV: Pessoas / Importar Férias',
 'nav_pessoas_importar_hierarquia': 'NAV: Pessoas / Importar Hierarquia',
 'nav_pessoas_importar_pessoas': 'NAV: Pessoas / Importar Pessoas',
 'nav_pessoas_liderancas': 'NAV: Pessoas / Lideranças',
 'nav_pessoas_liderancas_bloco': 'NAV: Pessoas / Bloco Lideranças',
 'nav_pessoas_novo_colaborador': 'NAV: Pessoas / Novo Colaborador',
 'nav_pessoas_ocorrencias': 'NAV: Pessoas / Ocorrências',
 'nav_pessoas_ocorrencias_bloco': 'NAV: Pessoas / Bloco Ocorrências',
 'nav_pessoas_perfil_rh': 'NAV: Pessoas / Permissão Especial: Perfil RH/DP',
 'nav_pessoas_ponto_ver_todos': 'NAV: Pessoas / Permissão Especial: Ver Todos os Colaboradores (Ponto)',
 'nav_pessoas_registrar_ferias': 'NAV: Pessoas / Registrar Férias',
 'nav_pessoas_registrar_ferias_todos': 'NAV: Pessoas / Permissão Especial: Registrar Férias de Qualquer '
                                       'Colaborador',
 'nav_pessoas_registrar_ocorrencia': 'NAV: Pessoas / Registrar Ocorrência',
 'nav_pessoas_tratativa_ponto_bloco': 'NAV: Pessoas / Bloco Tratativa de Batidas de Ponto',
 'nav_pessoas_ver_salario': 'NAV: Pessoas / Permissão Especial: Ver Salário',
 'nav_pessoas_ver_todos_colaboradores': 'NAV: Global / Permissão Especial: Ver Todos os Colaboradores',
 'nav_treinamentos_acompanhamento': 'NAV: Treinamentos / Bloco Acompanhamento',
 'nav_treinamentos_avaliacao_edit': 'NAV: Treinamentos / Editar Avaliação',
 'nav_treinamentos_avaliacoes': 'NAV: Treinamentos / Avaliações de Colaboradores',
 'nav_treinamentos_avaliacoes_bloco': 'NAV: Treinamentos / Bloco Avaliações de Colaboradores',
 'nav_treinamentos_calendario': 'NAV: Treinamentos / Calendário',
 'nav_treinamentos_calendario_bloco': 'NAV: Treinamentos / Bloco Calendário',
 'nav_treinamentos_cotacao_create': 'NAV: Treinamentos / Nova Cotação',
 'nav_treinamentos_cotacao_update': 'NAV: Treinamentos / Editar Cotação',
 'nav_treinamentos_dashboard': 'NAV: Treinamentos / Dashboard',
 'nav_treinamentos_dashboard_export_csv': 'NAV: Treinamentos / Exportar Dashboard (CSV)',
 'nav_treinamentos_detalhe_treinamento': 'NAV: Treinamentos / Detalhe do Treinamento',
 'nav_treinamentos_disciplina_create': 'NAV: Treinamentos / Nova Disciplina',
 'nav_treinamentos_disciplina_edit': 'NAV: Treinamentos / Editar Disciplina',
 'nav_treinamentos_disciplina_procedimento_add': 'NAV: Treinamentos / Adicionar Procedimentos à Disciplina',
 'nav_treinamentos_disciplina_procedimento_remove': 'NAV: Treinamentos / Remover Procedimento da Disciplina',
 'nav_treinamentos_disciplinas': 'NAV: Treinamentos / Disciplinas',
 'nav_treinamentos_disciplinas_bloco': 'NAV: Treinamentos / Bloco Disciplinas',
 'nav_treinamentos_disciplinas_delete': 'NAV: Treinamentos / Deletar Disciplina',
 'nav_treinamentos_download_template': 'NAV: Treinamentos / Download Template Importação',
 'nav_treinamentos_editar_procedimento': 'NAV: Treinamentos / Editar Procedimento',
 'nav_treinamentos_editar_treinamento': 'NAV: Treinamentos / Editar Treinamento',
 'nav_treinamentos_eficacia': 'NAV: Treinamentos / Avaliação de Eficácia',
 'nav_treinamentos_eficacia_alterar_gestor': 'NAV: Treinamentos / Alterar Gestor em Massa',
 'nav_treinamentos_eficacia_bloco': 'NAV: Treinamentos / Bloco Avaliação de Eficácia',
 'nav_treinamentos_eficacia_export': 'NAV: Treinamentos / Exportar (Excel / FOR.142)',
 'nav_treinamentos_eficacia_registrar': 'NAV: Treinamentos / Registrar Avaliação de Eficácia',
 'nav_treinamentos_eficacia_registrar_massa': 'NAV: Treinamentos / Registrar Avaliação de Eficácia em Massa',
 'nav_treinamentos_exportar_procedimentos': 'NAV: Treinamentos / Exportar Procedimentos (Excel)',
 'nav_treinamentos_exportar_treinamentos': 'NAV: Treinamentos / Exportar Treinamentos (Excel)',
 'nav_treinamentos_fornecedor_avaliacao': 'NAV: Treinamentos / Nova Avaliação de Fornecedor',
 'nav_treinamentos_fornecedor_create': 'NAV: Treinamentos / Novo Fornecedor',
 'nav_treinamentos_fornecedor_update': 'NAV: Treinamentos / Editar Fornecedor',
 'nav_treinamentos_fornecedores': 'NAV: Treinamentos / Fornecedores e Cotações',
 'nav_treinamentos_fornecedores_bloco': 'NAV: Treinamentos / Bloco Fornecedores e Cotações de Treinamento',
 'nav_treinamentos_gaps': 'NAV: Treinamentos / Gaps de Competência',
 'nav_treinamentos_gestao': 'NAV: Treinamentos / Bloco Gestão de Treinamentos',
 'nav_treinamentos_grupo_create': 'NAV: Treinamentos / Novo Grupo',
 'nav_treinamentos_grupo_delete': 'NAV: Treinamentos / Deletar Grupo',
 'nav_treinamentos_grupo_update': 'NAV: Treinamentos / Editar Grupo',
 'nav_treinamentos_importar_procedimentos': 'NAV: Treinamentos / Importar Procedimentos',
 'nav_treinamentos_importar_treinamentos': 'NAV: Treinamentos / Importar Lista de Presença',
 'nav_treinamentos_lista_presenca_create': 'NAV: Treinamentos / Nova Lista de Presença',
 'nav_treinamentos_lista_presenca_delete': 'NAV: Treinamentos / Deletar Lista de Presença',
 'nav_treinamentos_lista_presenca_edit': 'NAV: Treinamentos / Editar Lista de Presença',
 'nav_treinamentos_lista_presenca_erros_download': 'NAV: Treinamentos / Download Erros Importação',
 'nav_treinamentos_lista_presenca_export': 'NAV: Treinamentos / Exportar Listas de Presença',
 'nav_treinamentos_lista_presenca_export_pdf': 'NAV: Treinamentos / Exportar Lista de Presença (PDF)',
 'nav_treinamentos_lista_presenca_gerar': 'NAV: Treinamentos / Gerar Lista de Presença (a partir do '
                                          'Planejamento)',
 'nav_treinamentos_lista_presenca_import': 'NAV: Treinamentos / Importar Lista de Presença',
 'nav_treinamentos_lista_presenca_remover_assinada': 'NAV: Treinamentos / Remover Lista Assinada',
 'nav_treinamentos_lista_presenca_template': 'NAV: Treinamentos / Template Lista de Presença',
 'nav_treinamentos_lista_presenca_template_upload': 'NAV: Treinamentos / Upload Template Lista de Presença',
 'nav_treinamentos_lista_presenca_upload_assinada': 'NAV: Treinamentos / Upload Lista Assinada',
 'nav_treinamentos_listas_presenca': 'NAV: Treinamentos / Listas de Presença',
 'nav_treinamentos_listas_presenca_bloco': 'NAV: Treinamentos / Bloco Listas de Presença',
 'nav_treinamentos_matriz': 'NAV: Treinamentos / Bloco Matriz de Competências',
 'nav_treinamentos_matriz_colaborador_add': 'NAV: Treinamentos / Associar Colaboradores',
 'nav_treinamentos_matriz_create': 'NAV: Treinamentos / Nova Matriz',
 'nav_treinamentos_matriz_edit': 'NAV: Treinamentos / Editar Matriz',
 'nav_treinamentos_matriz_solicitar_validacao': 'NAV: Treinamentos / Solicitar Validação',
 'nav_treinamentos_matrizes': 'NAV: Treinamentos / Matrizes',
 'nav_treinamentos_matrizes_colaborador_remove': 'NAV: Treinamentos / Remover Colaborador da Matriz',
 'nav_treinamentos_matrizes_delete': 'NAV: Treinamentos / Deletar Matriz',
 'nav_treinamentos_matrizes_export': 'NAV: Treinamentos / Exportar Matrizes',
 'nav_treinamentos_matrizes_import': 'NAV: Treinamentos / Importação de Matriz',
 'nav_treinamentos_matrizes_template': 'NAV: Treinamentos / Template Importação Matriz',
 'nav_treinamentos_novo_procedimento': 'NAV: Treinamentos / Novo Procedimento',
 'nav_treinamentos_novo_treinamento': 'NAV: Treinamentos / Novo Treinamento',
 'nav_treinamentos_orcamento_create': 'NAV: Treinamentos / Novo Orçamento',
 'nav_treinamentos_orcamento_update': 'NAV: Treinamentos / Editar Orçamento',
 'nav_treinamentos_perfil_create': 'NAV: Treinamentos / Novo Perfil',
 'nav_treinamentos_perfil_edit': 'NAV: Treinamentos / Editar Perfil',
 'nav_treinamentos_perfis': 'NAV: Treinamentos / Perfis e Grupos',
 'nav_treinamentos_perfis_bloco': 'NAV: Treinamentos / Bloco Perfis de Treinamento',
 'nav_treinamentos_perfis_colaborador_add': 'NAV: Treinamentos / Adicionar/Associar Colaborador ao Perfil',
 'nav_treinamentos_perfis_colaborador_edit': 'NAV: Treinamentos / Editar Colaborador do Perfil',
 'nav_treinamentos_perfis_colaborador_mass_remove': 'NAV: Treinamentos / Remover Colaboradores em Massa',
 'nav_treinamentos_perfis_colaborador_remove': 'NAV: Treinamentos / Remover Colaborador do Perfil',
 'nav_treinamentos_perfis_delete': 'NAV: Treinamentos / Deletar Perfil (API)',
 'nav_treinamentos_perfis_delete_template': 'NAV: Treinamentos / Remover Template',
 'nav_treinamentos_perfis_export_erros': 'NAV: Treinamentos / Exportar Erros Importação',
 'nav_treinamentos_perfis_export_estrutura': 'NAV: Treinamentos / Exportar Estrutura',
 'nav_treinamentos_perfis_import': 'NAV: Treinamentos / Importar Perfis',
 'nav_treinamentos_perfis_import_estrutura': 'NAV: Treinamentos / Importar Estrutura',
 'nav_treinamentos_perfis_integracao': 'NAV: Treinamentos / Pacotes de Integração (Salvar, Editar, Copiar)',
 'nav_treinamentos_perfis_integracao_delete': 'NAV: Treinamentos / Excluir Pacote de Integração',
 'nav_treinamentos_perfis_mass_delete': 'NAV: Treinamentos / Deletar Perfis em Massa (API)',
 'nav_treinamentos_perfis_template_importacao': 'NAV: Treinamentos / Template Importação (Download)',
 'nav_treinamentos_perfis_upload_template': 'NAV: Treinamentos / Upload Template',
 'nav_treinamentos_perguntas_auto_avaliacao': 'NAV: Treinamentos / Perguntas Auto-Avaliação (Lista e '
                                              'Pré-visualização)',
 'nav_treinamentos_perguntas_auto_avaliacao_bloco': 'NAV: Treinamentos / Bloco Perguntas Auto-Avaliação '
                                                    '(FOR.141)',
 'nav_treinamentos_perguntas_auto_avaliacao_edit': 'NAV: Treinamentos / Salvar Perguntas de Auto-Avaliação',
 'nav_treinamentos_planejamento': 'NAV: Treinamentos / Planejamento',
 'nav_treinamentos_planejamento_bloco': 'NAV: Treinamentos / Bloco Planejamento',
 'nav_treinamentos_planejamento_colaborador_remove': 'NAV: Treinamentos / Remover Colaborador do '
                                                     'Planejamento',
 'nav_treinamentos_planejamento_create': 'NAV: Treinamentos / Novo Planejamento',
 'nav_treinamentos_planejamento_criar_registros': 'NAV: Treinamentos / Gerar Registros de Treinamento',
 'nav_treinamentos_planejamento_delete': 'NAV: Treinamentos / Deletar Planejamento',
 'nav_treinamentos_planejamento_edit': 'NAV: Treinamentos / Editar Planejamento',
 'nav_treinamentos_planejamento_export': 'NAV: Treinamentos / Exportar Planejamentos (Excel)',
 'nav_treinamentos_planejamento_mass_delete': 'NAV: Treinamentos / Excluir Planejamentos (Massa)',
 'nav_treinamentos_planejamento_procedimento_remove': 'NAV: Treinamentos / Remover Procedimento do '
                                                      'Planejamento',
 'nav_treinamentos_planejamento_status': 'NAV: Treinamentos / Alterar Status do Planejamento',
 'nav_treinamentos_proc_matrizes_bloco': 'NAV: Treinamentos / Bloco Matrizes e Sub-áreas',
 'nav_treinamentos_procedimentos': 'NAV: Treinamentos / Procedimentos',
 'nav_treinamentos_procedimentos_bloco': 'NAV: Treinamentos / Bloco Procedimentos',
 'nav_treinamentos_procedimentos_matrizes': 'NAV: Treinamentos / Matrizes e Sub-áreas (Procedimentos)',
 'nav_treinamentos_procedimentos_matrizes_import': 'NAV: Treinamentos / Importar Matrizes e Sub-áreas '
                                                   '(Procedimentos)',
 'nav_treinamentos_procedimentos_subareas_api': 'NAV: Treinamentos / API Sub-áreas por Matriz',
 'nav_treinamentos_registros': 'NAV: Treinamentos / Registros de Treinamento',
 'nav_treinamentos_subgrupo_create': 'NAV: Treinamentos / Novo Subgrupo',
 'nav_treinamentos_subgrupo_delete': 'NAV: Treinamentos / Deletar Subgrupo',
 'nav_treinamentos_subgrupo_procedimento_add': 'NAV: Treinamentos / Adicionar Procedimento ao Subgrupo',
 'nav_treinamentos_subgrupo_procedimento_remove': 'NAV: Treinamentos / Remover Procedimento do Subgrupo',
 'nav_treinamentos_subgrupo_update': 'NAV: Treinamentos / Editar Subgrupo',
 'nav_treinamentos_templates_bloco': 'NAV: Treinamentos / Bloco Templates de Documentos',
 'nav_treinamentos_templates_config': 'NAV: Treinamentos / Configuração de Templates',
 'nav_treinamentos_validar_matriz': 'NAV: Treinamentos / Permissão Especial: Validar Qualquer Matriz de '
                                    'Competência',
 'nav_usuarios_lista': 'NAV: Usuários / Lista',
 'nav_usuarios_lista_bloco': 'NAV: Usuários / Bloco Lista de Usuários'}

# permissão -> permissões de origem (quem tinha alguma origem recebe a permissão)
GRANTS = {'nav_auditoria_admin': ['nav_pessoas_ver_todos_colaboradores'],
 'nav_auditoria_encerrar_modelo': ['nav_auditoria_editar_modelo'],
 'nav_auditoria_exportar_pdf': ['nav_auditoria_detalhe_registro'],
 'nav_auditoria_iso_agendas_delete': ['nav_auditoria_iso_agendas'],
 'nav_auditoria_iso_itens_delete': ['nav_auditoria_iso_itens'],
 'nav_auditoria_iso_modelos_delete': ['nav_auditoria_iso_modelos'],
 'nav_auditoria_iso_normas_delete': ['nav_auditoria_iso_normas'],
 'nav_auditoria_iso_perguntas_delete': ['nav_auditoria_iso_perguntas'],
 'nav_auditoria_iso_solicitacoes': ['nav_auditoria_iso_entrevista'],
 'nav_auditoria_justificar_nao_execucao': ['nav_auditoria_avaliacao', 'nav_auditoria_editar_modelo'],
 'nav_auditoria_modelo_topicos': ['nav_auditoria_editar_modelo'],
 'nav_auditoria_perguntas_massa': ['nav_auditoria_editar_pergunta'],
 'nav_fornecedores_avaliacoes': ['nav_fornecedores_lista'],
 'nav_laboratorio_coating_ciclo_copy': ['nav_laboratorio_coating_ciclos'],
 'nav_laboratorio_coating_ciclo_create': ['nav_laboratorio_coating_ciclos'],
 'nav_laboratorio_coating_ciclo_delete': ['nav_laboratorio_coating_ciclos'],
 'nav_laboratorio_coating_ciclo_update': ['nav_laboratorio_coating_ciclos'],
 'nav_laboratorio_coating_equipe_delete': ['nav_laboratorio_coating_equipe'],
 'nav_laboratorio_coating_equipe_update': ['nav_laboratorio_coating_equipe'],
 'nav_laboratorio_coating_painel_editar': ['nav_laboratorio_coating_painel'],
 'nav_laboratorio_coating_registro_delete': ['nav_laboratorio_coating_painel'],
 'nav_laboratorio_coating_tratamento_create': ['nav_laboratorio_coating_tratamentos'],
 'nav_laboratorio_coating_tratamento_update': ['nav_laboratorio_coating_tratamentos'],
 'nav_laboratorio_coating_turno_create': ['nav_laboratorio_coating_turnos'],
 'nav_laboratorio_coating_turno_update': ['nav_laboratorio_coating_turnos'],
 'nav_laboratorio_dashboard_pdf': ['nav_laboratorio_dashboard'],
 'nav_laboratorio_ocorrencia_anotar': ['nav_laboratorio_editar_ocorrencia',
                                       'nav_laboratorio_lista_ocorrencias',
                                       'nav_laboratorio_modulo',
                                       'nav_laboratorio_nova_ocorrencia'],
 'nav_laboratorio_ocorrencia_delete': ['nav_laboratorio_editar_ocorrencia'],
 'nav_laboratorio_ocorrencia_detalhe': ['nav_laboratorio_editar_ocorrencia',
                                        'nav_laboratorio_lista_ocorrencias',
                                        'nav_laboratorio_modulo',
                                        'nav_laboratorio_nova_ocorrencia'],
 'nav_laboratorio_ocorrencia_encerrar': ['nav_laboratorio_editar_ocorrencia',
                                         'nav_laboratorio_lista_ocorrencias',
                                         'nav_laboratorio_modulo',
                                         'nav_laboratorio_nova_ocorrencia'],
 'nav_metrologia_aplicar_carimbo_certificado': ['nav_metrologia_editar_historico'],
 'nav_metrologia_atendimento_confirmar': ['nav_metrologia_atendimento_create'],
 'nav_metrologia_atendimento_update': ['nav_metrologia_atendimento_create'],
 'nav_metrologia_atualizar_datas_massa': ['nav_metrologia_editar_instrumento'],
 'nav_metrologia_estatisticas': ['nav_metrologia_dashboard'],
 'nav_metrologia_faixa_instrumento_add': ['nav_metrologia_faixa_categoria_create'],
 'nav_metrologia_faixa_instrumento_replace': ['nav_metrologia_faixa_categoria_update'],
 'nav_metrologia_instrumento_bulk_change_category': ['nav_metrologia_categoria_bulk_update'],
 'nav_metrologia_ocorrencia_editar': ['nav_metrologia_editar_instrumento'],
 'nav_metrologia_ocorrencia_excluir': ['nav_metrologia_editar_instrumento'],
 'nav_metrologia_ocorrencia_registrar': ['nav_metrologia_detalhe_instrumento'],
 'nav_metrologia_registrar_historico_massa': ['nav_metrologia_registrar_historico'],
 'nav_metrologia_relatorio_vencidos': ['nav_metrologia_dashboard'],
 'nav_metrologia_solicitacao_status': ['nav_metrologia_solicitacao_update'],
 'nav_metrologia_substituir_instrumento': ['nav_metrologia_editar_instrumento'],
 'nav_metrologia_template_etiqueta_delete': ['nav_metrologia_export_etiquetas'],
 'nav_metrologia_template_etiqueta_toggle': ['nav_metrologia_export_etiquetas'],
 'nav_metrologia_template_etiqueta_upload': ['nav_metrologia_export_etiquetas'],
 'nav_metrologia_templates_etiquetas': ['nav_metrologia_export_etiquetas'],
 'nav_pessoas_ferias_vencimentos': ['nav_pessoas_editar_ferias'],
 'nav_pessoas_horas_extras_create': ['nav_pessoas_horas_extras_list'],
 'nav_pessoas_horas_extras_delete': ['nav_pessoas_horas_extras_list'],
 'nav_pessoas_horas_extras_edit': ['nav_pessoas_horas_extras_list'],
 'nav_pessoas_horas_extras_motivos': ['nav_pessoas_horas_extras_list'],
 'nav_pessoas_registrar_ocorrencia': ['nav_pessoas_ocorrencias'],
 'nav_treinamentos_avaliacao_edit': ['nav_treinamentos_avaliacoes'],
 'nav_treinamentos_cotacao_create': ['nav_treinamentos_cotacao_update'],
 'nav_treinamentos_disciplina_create': ['nav_treinamentos_disciplinas'],
 'nav_treinamentos_disciplina_edit': ['nav_treinamentos_disciplinas'],
 'nav_treinamentos_disciplina_procedimento_add': ['nav_treinamentos_disciplinas'],
 'nav_treinamentos_eficacia': ['nav_treinamentos_registros'],
 'nav_treinamentos_eficacia_alterar_gestor': ['nav_treinamentos_registros'],
 'nav_treinamentos_eficacia_export': ['nav_treinamentos_registros'],
 'nav_treinamentos_eficacia_registrar': ['nav_treinamentos_registros'],
 'nav_treinamentos_eficacia_registrar_massa': ['nav_treinamentos_registros'],
 'nav_treinamentos_fornecedor_avaliacao': ['nav_treinamentos_fornecedor_update'],
 'nav_treinamentos_fornecedores': ['nav_treinamentos_cotacao_update',
                                   'nav_treinamentos_fornecedor_create',
                                   'nav_treinamentos_fornecedor_update',
                                   'nav_treinamentos_orcamento_create',
                                   'nav_treinamentos_orcamento_update'],
 'nav_treinamentos_gaps': ['nav_treinamentos_dashboard'],
 'nav_treinamentos_lista_presenca_gerar': ['nav_treinamentos_listas_presenca',
                                           'nav_treinamentos_planejamento_export'],
 'nav_treinamentos_matriz_colaborador_add': ['nav_treinamentos_matrizes'],
 'nav_treinamentos_matriz_create': ['nav_treinamentos_matrizes'],
 'nav_treinamentos_matriz_edit': ['nav_treinamentos_matrizes'],
 'nav_treinamentos_matriz_solicitar_validacao': ['nav_treinamentos_matrizes'],
 'nav_treinamentos_perfil_create': ['nav_treinamentos_perfis'],
 'nav_treinamentos_perfil_edit': ['nav_treinamentos_perfis'],
 'nav_treinamentos_perfis_colaborador_add': ['nav_treinamentos_perfis'],
 'nav_treinamentos_perfis_integracao': ['nav_treinamentos_perfis'],
 'nav_treinamentos_perfis_integracao_delete': ['nav_treinamentos_perfis'],
 'nav_treinamentos_perguntas_auto_avaliacao': ['nav_treinamentos_procedimentos'],
 'nav_treinamentos_perguntas_auto_avaliacao_edit': ['nav_treinamentos_editar_procedimento'],
 'nav_treinamentos_planejamento_create': ['nav_treinamentos_planejamento'],
 'nav_treinamentos_planejamento_criar_registros': ['nav_treinamentos_planejamento_edit'],
 'nav_treinamentos_planejamento_status': ['nav_treinamentos_planejamento_edit'],
 'nav_treinamentos_subgrupo_procedimento_add': ['nav_treinamentos_subgrupo_update']}

# bloco -> funções do bloco
BLOCKS = {'nav_auditoria_analise': ['nav_auditoria_dashboard'],
 'nav_auditoria_cadastro': ['nav_auditoria_duplicar_modelo',
                            'nav_auditoria_editar_modelo',
                            'nav_auditoria_encerrar_modelo',
                            'nav_auditoria_justificar_nao_execucao',
                            'nav_auditoria_modelo_topicos',
                            'nav_auditoria_modelos',
                            'nav_auditoria_novo_modelo',
                            'nav_auditoria_remover_modelo'],
 'nav_auditoria_iso_bloco': ['nav_auditoria_iso_amostras',
                             'nav_auditoria_iso_analytics',
                             'nav_auditoria_iso_avaliacao',
                             'nav_auditoria_iso_capa',
                             'nav_auditoria_iso_cronograma',
                             'nav_auditoria_iso_entrevista',
                             'nav_auditoria_iso_export',
                             'nav_auditoria_iso_fechamento',
                             'nav_auditoria_iso_lista',
                             'nav_auditoria_iso_matriz',
                             'nav_auditoria_iso_revisao',
                             'nav_auditoria_iso_sintese',
                             'nav_auditoria_iso_solicitacoes'],
 'nav_auditoria_iso_itens_bloco': ['nav_auditoria_iso_itens', 'nav_auditoria_iso_itens_delete'],
 'nav_auditoria_iso_modelos_bloco': ['nav_auditoria_iso_modelos', 'nav_auditoria_iso_modelos_delete'],
 'nav_auditoria_iso_normas_bloco': ['nav_auditoria_iso_normas', 'nav_auditoria_iso_normas_delete'],
 'nav_auditoria_iso_perguntas_bloco': ['nav_auditoria_iso_perguntas', 'nav_auditoria_iso_perguntas_delete'],
 'nav_auditoria_iso_setup_bloco': ['nav_auditoria_iso_agendas',
                                   'nav_auditoria_iso_agendas_delete',
                                   'nav_auditoria_iso_setup'],
 'nav_auditoria_nova_bloco': ['nav_auditoria_avaliacao', 'nav_auditoria_nova'],
 'nav_auditoria_operacao': ['nav_auditoria_comentario_delete',
                            'nav_auditoria_comentario_edit',
                            'nav_auditoria_detalhe_registro',
                            'nav_auditoria_editar_registro',
                            'nav_auditoria_excluir_registro',
                            'nav_auditoria_exportar_excel',
                            'nav_auditoria_exportar_pdf',
                            'nav_auditoria_registros',
                            'nav_auditoria_registros_por_modelo'],
 'nav_auditoria_perguntas_bloco': ['nav_auditoria_duplicar_pergunta',
                                   'nav_auditoria_editar_pergunta',
                                   'nav_auditoria_nova_pergunta',
                                   'nav_auditoria_perguntas',
                                   'nav_auditoria_perguntas_massa',
                                   'nav_auditoria_remover_pergunta'],
 'nav_boards_gestao': ['nav_boards_archive', 'nav_boards_detail', 'nav_boards_edit'],
 'nav_boards_visao_geral': ['nav_boards_create', 'nav_boards_dashboard'],
 'nav_fornecedores_avaliacao': ['nav_fornecedores_avaliacao_create',
                                'nav_fornecedores_avaliacao_edit',
                                'nav_fornecedores_avaliacao_matriz',
                                'nav_fornecedores_avaliacao_selecao',
                                'nav_fornecedores_avaliacoes',
                                'nav_fornecedores_export_avaliacoes',
                                'nav_fornecedores_reavaliacao_create',
                                'nav_fornecedores_reavaliacao_delete'],
 'nav_fornecedores_gestao': ['nav_fornecedores_documento_create',
                             'nav_fornecedores_documento_delete',
                             'nav_fornecedores_editar',
                             'nav_fornecedores_lista',
                             'nav_fornecedores_novo'],
 'nav_fornecedores_perguntas_bloco': ['nav_fornecedores_pergunta_create',
                                      'nav_fornecedores_pergunta_delete',
                                      'nav_fornecedores_pergunta_edit',
                                      'nav_fornecedores_perguntas'],
 'nav_laboratorio_categorias_bloco': ['nav_laboratorio_categoria_create',
                                      'nav_laboratorio_categoria_update',
                                      'nav_laboratorio_categorias'],
 'nav_laboratorio_coating': ['nav_laboratorio_coating_painel',
                             'nav_laboratorio_coating_painel_editar',
                             'nav_laboratorio_coating_registro_delete'],
 'nav_laboratorio_coating_ciclos_bloco': ['nav_laboratorio_coating_ciclo_copy',
                                          'nav_laboratorio_coating_ciclo_create',
                                          'nav_laboratorio_coating_ciclo_delete',
                                          'nav_laboratorio_coating_ciclo_update',
                                          'nav_laboratorio_coating_ciclos'],
 'nav_laboratorio_coating_dashboard_bloco': ['nav_laboratorio_coating_dashboard'],
 'nav_laboratorio_coating_equipe_bloco': ['nav_laboratorio_coating_equipe',
                                          'nav_laboratorio_coating_equipe_delete',
                                          'nav_laboratorio_coating_equipe_update'],
 'nav_laboratorio_coating_importacao_bloco': ['nav_laboratorio_coating_importacao'],
 'nav_laboratorio_coating_tratamentos_bloco': ['nav_laboratorio_coating_tratamento_create',
                                               'nav_laboratorio_coating_tratamento_update',
                                               'nav_laboratorio_coating_tratamentos'],
 'nav_laboratorio_coating_turnos_bloco': ['nav_laboratorio_coating_turno_create',
                                          'nav_laboratorio_coating_turno_update',
                                          'nav_laboratorio_coating_turnos'],
 'nav_laboratorio_dashboard_bloco': ['nav_laboratorio_dashboard', 'nav_laboratorio_dashboard_pdf'],
 'nav_laboratorio_maquinas': ['nav_laboratorio_maquina_create',
                              'nav_laboratorio_maquina_delete',
                              'nav_laboratorio_maquina_update',
                              'nav_laboratorio_maquinas_lista'],
 'nav_laboratorio_maquinas_categorias_bloco': ['nav_laboratorio_categoria_maquina_create',
                                               'nav_laboratorio_categoria_maquina_delete',
                                               'nav_laboratorio_categoria_maquina_update',
                                               'nav_laboratorio_maquinas_categorias'],
 'nav_laboratorio_ocorrencias_bloco': ['nav_laboratorio_editar_ocorrencia',
                                       'nav_laboratorio_lista_ocorrencias',
                                       'nav_laboratorio_nova_ocorrencia',
                                       'nav_laboratorio_ocorrencia_anotar',
                                       'nav_laboratorio_ocorrencia_delete',
                                       'nav_laboratorio_ocorrencia_detalhe',
                                       'nav_laboratorio_ocorrencia_encerrar'],
 'nav_laboratorio_ocorrencias_gerais': ['nav_laboratorio_modulo'],
 'nav_metrologia_categorias_bloco': ['nav_metrologia_categoria_bulk_update',
                                     'nav_metrologia_categoria_create',
                                     'nav_metrologia_categoria_delete',
                                     'nav_metrologia_categoria_update',
                                     'nav_metrologia_categorias',
                                     'nav_metrologia_download_arquivo_padrao',
                                     'nav_metrologia_faixa_categoria_create',
                                     'nav_metrologia_faixa_categoria_delete',
                                     'nav_metrologia_faixa_categoria_update',
                                     'nav_metrologia_faixa_instrumento_add',
                                     'nav_metrologia_faixa_instrumento_bulk_delete',
                                     'nav_metrologia_faixa_instrumento_delete',
                                     'nav_metrologia_faixa_instrumento_replace',
                                     'nav_metrologia_instrumento_bulk_change_category',
                                     'nav_metrologia_remover_arquivo_padrao'],
 'nav_metrologia_cotacoes': ['nav_metrologia_atendimento_confirmar',
                             'nav_metrologia_atendimento_create',
                             'nav_metrologia_atendimento_update',
                             'nav_metrologia_cotacao_fornecedor_create',
                             'nav_metrologia_cotacao_fornecedor_update',
                             'nav_metrologia_item_solicitacao_delete',
                             'nav_metrologia_item_solicitacao_edit',
                             'nav_metrologia_solicitacao_create',
                             'nav_metrologia_solicitacao_delete',
                             'nav_metrologia_solicitacao_status',
                             'nav_metrologia_solicitacao_update',
                             'nav_metrologia_solicitacoes_cotacao'],
 'nav_metrologia_etiquetas_bloco': ['nav_metrologia_export_etiquetas',
                                    'nav_metrologia_template_etiqueta_delete',
                                    'nav_metrologia_template_etiqueta_toggle',
                                    'nav_metrologia_template_etiqueta_upload',
                                    'nav_metrologia_templates_etiquetas'],
 'nav_metrologia_gestao': ['nav_metrologia_atualizar_datas_massa',
                           'nav_metrologia_detalhe_instrumento',
                           'nav_metrologia_editar_instrumento',
                           'nav_metrologia_export_instrumentos',
                           'nav_metrologia_import_jobs',
                           'nav_metrologia_importar_instrumentos',
                           'nav_metrologia_lista_instrumentos',
                           'nav_metrologia_novo_instrumento',
                           'nav_metrologia_ocorrencia_editar',
                           'nav_metrologia_ocorrencia_excluir',
                           'nav_metrologia_ocorrencia_registrar',
                           'nav_metrologia_substituir_instrumento'],
 'nav_metrologia_historicos_bloco': ['nav_metrologia_aplicar_carimbo_certificado',
                                     'nav_metrologia_download_certificado',
                                     'nav_metrologia_editar_historico',
                                     'nav_metrologia_historicos_calibracao',
                                     'nav_metrologia_importar_historico',
                                     'nav_metrologia_registrar_historico',
                                     'nav_metrologia_registrar_historico_massa',
                                     'nav_metrologia_remover_carimbo_certificado',
                                     'nav_metrologia_remover_certificado_historico',
                                     'nav_metrologia_remover_historico',
                                     'nav_metrologia_visualizar_historico'],
 'nav_metrologia_unidades_bloco': ['nav_metrologia_unidade_create',
                                   'nav_metrologia_unidade_delete',
                                   'nav_metrologia_unidade_update',
                                   'nav_metrologia_unidades_medida'],
 'nav_metrologia_visao_geral': ['nav_metrologia_dashboard',
                                'nav_metrologia_estatisticas',
                                'nav_metrologia_export_estatisticas',
                                'nav_metrologia_relatorio_vencidos'],
 'nav_pessoas_equipe': ['nav_pessoas_api_delete_colaborador',
                        'nav_pessoas_api_delete_colaboradores_multiple',
                        'nav_pessoas_colaboradores',
                        'nav_pessoas_detalhe_colaborador',
                        'nav_pessoas_editar_colaborador',
                        'nav_pessoas_importar_pessoas',
                        'nav_pessoas_novo_colaborador'],
 'nav_pessoas_ferias_bloco': ['nav_pessoas_editar_ferias',
                              'nav_pessoas_excluir_ferias',
                              'nav_pessoas_exportar_ferias',
                              'nav_pessoas_ferias_status',
                              'nav_pessoas_ferias_vencimentos',
                              'nav_pessoas_gestao_ferias',
                              'nav_pessoas_importar_ferias',
                              'nav_pessoas_registrar_ferias'],
 'nav_pessoas_horas_extras': ['nav_pessoas_horas_extras_create',
                              'nav_pessoas_horas_extras_delete',
                              'nav_pessoas_horas_extras_edit',
                              'nav_pessoas_horas_extras_list',
                              'nav_pessoas_horas_extras_motivos'],
 'nav_pessoas_liderancas_bloco': ['nav_pessoas_importar_hierarquia', 'nav_pessoas_liderancas'],
 'nav_pessoas_ocorrencias_bloco': ['nav_pessoas_deletar_ocorrencia',
                                   'nav_pessoas_editar_ocorrencia',
                                   'nav_pessoas_ocorrencias',
                                   'nav_pessoas_registrar_ocorrencia'],
 'nav_pessoas_tratativa_ponto_bloco': ['nav_pessoas_arquivar_demanda',
                                       'nav_pessoas_demandas_falhas_ponto',
                                       'nav_pessoas_excluir_demanda',
                                       'nav_pessoas_importar_falhas_ponto'],
 'nav_treinamentos_acompanhamento': ['nav_treinamentos_dashboard',
                                     'nav_treinamentos_dashboard_export_csv',
                                     'nav_treinamentos_gaps'],
 'nav_treinamentos_avaliacoes_bloco': ['nav_treinamentos_avaliacao_edit', 'nav_treinamentos_avaliacoes'],
 'nav_treinamentos_calendario_bloco': ['nav_treinamentos_calendario'],
 'nav_treinamentos_disciplinas_bloco': ['nav_treinamentos_disciplina_create',
                                        'nav_treinamentos_disciplina_edit',
                                        'nav_treinamentos_disciplina_procedimento_add',
                                        'nav_treinamentos_disciplina_procedimento_remove',
                                        'nav_treinamentos_disciplinas',
                                        'nav_treinamentos_disciplinas_delete'],
 'nav_treinamentos_eficacia_bloco': ['nav_treinamentos_eficacia',
                                     'nav_treinamentos_eficacia_alterar_gestor',
                                     'nav_treinamentos_eficacia_export',
                                     'nav_treinamentos_eficacia_registrar',
                                     'nav_treinamentos_eficacia_registrar_massa'],
 'nav_treinamentos_fornecedores_bloco': ['nav_treinamentos_cotacao_create',
                                         'nav_treinamentos_cotacao_update',
                                         'nav_treinamentos_fornecedor_avaliacao',
                                         'nav_treinamentos_fornecedor_create',
                                         'nav_treinamentos_fornecedor_update',
                                         'nav_treinamentos_fornecedores',
                                         'nav_treinamentos_orcamento_create',
                                         'nav_treinamentos_orcamento_update'],
 'nav_treinamentos_gestao': ['nav_treinamentos_detalhe_treinamento',
                             'nav_treinamentos_download_template',
                             'nav_treinamentos_editar_treinamento',
                             'nav_treinamentos_exportar_treinamentos',
                             'nav_treinamentos_importar_treinamentos',
                             'nav_treinamentos_novo_treinamento',
                             'nav_treinamentos_registros'],
 'nav_treinamentos_listas_presenca_bloco': ['nav_treinamentos_lista_presenca_create',
                                            'nav_treinamentos_lista_presenca_delete',
                                            'nav_treinamentos_lista_presenca_edit',
                                            'nav_treinamentos_lista_presenca_erros_download',
                                            'nav_treinamentos_lista_presenca_export',
                                            'nav_treinamentos_lista_presenca_export_pdf',
                                            'nav_treinamentos_lista_presenca_gerar',
                                            'nav_treinamentos_lista_presenca_import',
                                            'nav_treinamentos_lista_presenca_remover_assinada',
                                            'nav_treinamentos_lista_presenca_template',
                                            'nav_treinamentos_lista_presenca_template_upload',
                                            'nav_treinamentos_lista_presenca_upload_assinada',
                                            'nav_treinamentos_listas_presenca'],
 'nav_treinamentos_matriz': ['nav_treinamentos_matriz_colaborador_add',
                             'nav_treinamentos_matriz_create',
                             'nav_treinamentos_matriz_edit',
                             'nav_treinamentos_matriz_solicitar_validacao',
                             'nav_treinamentos_matrizes',
                             'nav_treinamentos_matrizes_colaborador_remove',
                             'nav_treinamentos_matrizes_delete',
                             'nav_treinamentos_matrizes_export',
                             'nav_treinamentos_matrizes_import',
                             'nav_treinamentos_matrizes_template'],
 'nav_treinamentos_perfis_bloco': ['nav_treinamentos_grupo_create',
                                   'nav_treinamentos_grupo_delete',
                                   'nav_treinamentos_grupo_update',
                                   'nav_treinamentos_perfil_create',
                                   'nav_treinamentos_perfil_edit',
                                   'nav_treinamentos_perfis',
                                   'nav_treinamentos_perfis_colaborador_add',
                                   'nav_treinamentos_perfis_colaborador_edit',
                                   'nav_treinamentos_perfis_colaborador_mass_remove',
                                   'nav_treinamentos_perfis_colaborador_remove',
                                   'nav_treinamentos_perfis_delete',
                                   'nav_treinamentos_perfis_delete_template',
                                   'nav_treinamentos_perfis_export_erros',
                                   'nav_treinamentos_perfis_export_estrutura',
                                   'nav_treinamentos_perfis_import',
                                   'nav_treinamentos_perfis_import_estrutura',
                                   'nav_treinamentos_perfis_integracao',
                                   'nav_treinamentos_perfis_integracao_delete',
                                   'nav_treinamentos_perfis_mass_delete',
                                   'nav_treinamentos_perfis_template_importacao',
                                   'nav_treinamentos_perfis_upload_template',
                                   'nav_treinamentos_subgrupo_create',
                                   'nav_treinamentos_subgrupo_delete',
                                   'nav_treinamentos_subgrupo_procedimento_add',
                                   'nav_treinamentos_subgrupo_procedimento_remove',
                                   'nav_treinamentos_subgrupo_update'],
 'nav_treinamentos_perguntas_auto_avaliacao_bloco': ['nav_treinamentos_perguntas_auto_avaliacao',
                                                     'nav_treinamentos_perguntas_auto_avaliacao_edit'],
 'nav_treinamentos_planejamento_bloco': ['nav_treinamentos_planejamento',
                                         'nav_treinamentos_planejamento_colaborador_remove',
                                         'nav_treinamentos_planejamento_create',
                                         'nav_treinamentos_planejamento_criar_registros',
                                         'nav_treinamentos_planejamento_delete',
                                         'nav_treinamentos_planejamento_edit',
                                         'nav_treinamentos_planejamento_export',
                                         'nav_treinamentos_planejamento_mass_delete',
                                         'nav_treinamentos_planejamento_procedimento_remove',
                                         'nav_treinamentos_planejamento_status'],
 'nav_treinamentos_proc_matrizes_bloco': ['nav_treinamentos_procedimentos_matrizes',
                                          'nav_treinamentos_procedimentos_matrizes_import',
                                          'nav_treinamentos_procedimentos_subareas_api'],
 'nav_treinamentos_procedimentos_bloco': ['nav_treinamentos_editar_procedimento',
                                          'nav_treinamentos_exportar_procedimentos',
                                          'nav_treinamentos_importar_procedimentos',
                                          'nav_treinamentos_novo_procedimento',
                                          'nav_treinamentos_procedimentos'],
 'nav_treinamentos_templates_bloco': ['nav_treinamentos_templates_config'],
 'nav_usuarios_lista_bloco': ['nav_usuarios_lista']}

OBSOLETE = ['nav_acoes_8d_create',
 'nav_acoes_8d_detail',
 'nav_acoes_8d_list',
 'nav_acoes_8d_update',
 'nav_acoes_a3_create',
 'nav_acoes_a3_detail',
 'nav_acoes_a3_list',
 'nav_acoes_a3_update',
 'nav_acoes_api_proximo_numero',
 'nav_acoes_controle_registros',
 'nav_acoes_criar_registro_modal',
 'nav_acoes_criar_solucao',
 'nav_acoes_dashboard',
 'nav_acoes_deletar_acoes_associadas',
 'nav_acoes_detalhe_acao',
 'nav_acoes_detalhe_solucao',
 'nav_acoes_download_template',
 'nav_acoes_download_template_acoes_associadas',
 'nav_acoes_download_template_controle_registros',
 'nav_acoes_download_template_plano_acao',
 'nav_acoes_editar_solucao',
 'nav_acoes_exportar_acoes_associadas',
 'nav_acoes_importar_acoes_associadas',
 'nav_acoes_importar_controle_registros',
 'nav_acoes_importar_plano_acao',
 'nav_acoes_kpis',
 'nav_acoes_kpis_create',
 'nav_acoes_kpis_delete',
 'nav_acoes_kpis_update',
 'nav_acoes_linha_create',
 'nav_acoes_linha_dados',
 'nav_acoes_linha_delete',
 'nav_acoes_linha_update',
 'nav_acoes_listar_acoes',
 'nav_acoes_listar_templates',
 'nav_acoes_mudanca_create',
 'nav_acoes_mudanca_detail',
 'nav_acoes_mudanca_list',
 'nav_acoes_mudanca_update',
 'nav_acoes_origens',
 'nav_acoes_origens_create',
 'nav_acoes_origens_delete',
 'nav_acoes_origens_update',
 'nav_acoes_plano',
 'nav_acoes_plano_create',
 'nav_acoes_plano_delete',
 'nav_acoes_plano_detail',
 'nav_acoes_plano_list',
 'nav_acoes_plano_update',
 'nav_acoes_referencia',
 'nav_acoes_registradas',
 'nav_acoes_registro',
 'nav_acoes_revisao_create',
 'nav_acoes_revisao_detail',
 'nav_acoes_revisao_list',
 'nav_acoes_revisao_update',
 'nav_acoes_rnc_create',
 'nav_acoes_rnc_detail',
 'nav_acoes_rnc_list',
 'nav_acoes_rnc_update',
 'nav_acoes_salvar_acao',
 'nav_acoes_tipos',
 'nav_acoes_tipos_create',
 'nav_acoes_tipos_delete',
 'nav_acoes_tipos_update',
 'nav_metrologia_importacao',
 'nav_mod_acoes',
 'nav_pessoas_importacao']


def forwards(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    User = apps.get_model("auth", "User")
    Through = User.user_permissions.through

    content_type, _ = ContentType.objects.get_or_create(app_label="core", model="navigationpermission")

    perms = {}
    for codename, name in PERM_NAMES.items():
        perm, _ = Permission.objects.update_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name[:255]},
        )
        perms[codename] = perm

    def user_codenames():
        result = {}
        rows = Through.objects.filter(
            permission__content_type__app_label="core",
            permission__codename__startswith="nav_",
        ).values_list("user_id", "permission__codename")
        for user_id, codename in rows:
            result.setdefault(user_id, set()).add(codename)
        return result

    def grant(pairs):
        Through.objects.bulk_create(
            [Through(user_id=user_id, permission_id=perms[codename].pk) for user_id, codename in pairs],
            ignore_conflicts=True,
        )

    # 1) Funções/ações: avaliadas sobre o estado ANTERIOR (sem encadear concessões)
    before = user_codenames()
    pairs = set()
    for user_id, owned in before.items():
        for codename, sources in GRANTS.items():
            if codename not in owned and owned.intersection(sources):
                pairs.add((user_id, codename))
    grant(pairs)

    # 2) Blocos: quem tem alguma função do bloco recebe o bloco
    after = user_codenames()
    pairs = set()
    for user_id, owned in after.items():
        for block, funcs in BLOCKS.items():
            if block not in owned and owned.intersection(funcs):
                pairs.add((user_id, block))
    grant(pairs)

    # 3) Limpeza de permissões órfãs
    Permission.objects.filter(content_type__app_label="core", codename__in=OBSOLETE).delete()
    Permission.objects.filter(content_type__app_label="core", codename__startswith="nav_acoes_").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_nav_permissoes_por_tela"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
