# Generated by Django 5.0.14 on 2025-11-21 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (Ex: 2050)')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição (Opcional)')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': '0.2 Centros de Custo',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('contato', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('escopo_servico', models.TextField(verbose_name='Escopo de Serviço')),
                ('status', models.CharField(choices=[('HOMOLOGADO', 'Homologado'), ('BLOQUEADO', 'Bloqueado'), ('EM_ANALISE', 'Em Análise')], default='EM_ANALISE', max_length=20)),
                ('nota_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota Média (0-10)')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': '5. Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='Identificação/Tag')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Equipamento')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Série')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUCATA', 'Sucata')], default='ATIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': '2. Instrumentos (Cadastro Físico)',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável Genérico')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': '0.1 Cadastro de Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Login (Caixa Alta)')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo (Macro)')),
                ('turno', models.CharField(choices=[('ADM', 'Administrativo'), ('TURNO_1', 'Turno 1'), ('TURNO_2', 'Turno 2'), ('TURNO_3', 'Turno 3'), ('12X36', '12x36')], default='ADM', max_length=20, verbose_name='Turno')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('password_last_changed', models.DateField(blank=True, null=True, verbose_name='Última Troca de Senha')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.centrocusto', verbose_name='Centro de Custo')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': '1. Colaboradores (RH)',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('nota_tecnica', models.IntegerField(default=10, verbose_name='Capacidade Técnica (0-10)')),
                ('nota_pontualidade', models.IntegerField(default=10, verbose_name='Pontualidade (0-10)')),
                ('nota_atendimento', models.IntegerField(default=10, verbose_name='Atendimento (0-10)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Ocorrências/Obs')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='qms.fornecedor')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações de Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='ProcessoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('prazo_limite', models.DateField(verbose_name='Prazo para envio')),
                ('status', models.CharField(choices=[('ABERTO', 'Cotação Aberta'), ('FECHADO', 'Finalizado/Aprovado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('instrumentos', models.ManyToManyField(to='qms.instrumento', verbose_name='Instrumentos do Lote')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador')),
            ],
            options={
                'verbose_name': 'Processo de Cotação',
                'verbose_name_plural': '6. Processos de Cotação',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('prazo_execucao_dias', models.IntegerField(verbose_name='Prazo Execução (Dias)')),
                ('arquivo_proposta', models.FileField(upload_to='orcamentos/', verbose_name='PDF da Proposta')),
                ('vencedor', models.BooleanField(default=False, verbose_name='Vencedor?')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='qms.processocotacao')),
            ],
        ),
        migrations.AddField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor de Instalação'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código (Ex: POP-01)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Procedimento')),
                ('revisao_atual', models.CharField(max_length=10, verbose_name='Revisão Atual (Ex: 05)')),
                ('data_revisao', models.DateField(verbose_name='Data da Revisão')),
                ('link_externo', models.URLField(blank=True, null=True, verbose_name='Link para Qualiex (Opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor Aplicável')),
            ],
            options={
                'verbose_name': 'Documento (POP/IT)',
                'verbose_name_plural': '7.1 Cadastro de Documentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='qms.setor', verbose_name='Setor Pertencente'),
        ),
        migrations.CreateModel(
            name='TipoMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandeza', models.CharField(max_length=100, verbose_name='Grandeza (Ex: Temperatura)')),
                ('faixa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa de Medição')),
                ('resolucao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolução')),
                ('periodicidade_meses', models.IntegerField(default=12, verbose_name='Freq. (Meses)')),
                ('data_ultima_calibracao', models.DateField(blank=True, null=True, verbose_name='Última Calibração')),
                ('data_proxima_calibracao', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='qms.instrumento', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Monitoramento de Vencimento',
                'verbose_name_plural': '3. Painel de Vencimentos (Tipos de Medição)',
                'unique_together': {('instrumento', 'grandeza')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calibracao', models.DateField(verbose_name='Data da Calibração')),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado (PDF)')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('COM_RESTricao', 'Aprovado c/ Restrição'), ('REPROVADO', 'Reprovado')], default='APROVADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador', verbose_name='Responsável Validação')),
                ('tipo_medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='qms.tipomedicao', verbose_name='Tipo de Medição')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': '4. Histórico de Calibrações',
                'ordering': ['-data_calibracao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao_treinada', models.CharField(max_length=10, verbose_name='Revisão Treinada')),
                ('data_treinamento', models.DateField(verbose_name='Data do Treinamento')),
                ('validade_treinamento', models.DateField(blank=True, null=True, verbose_name='Validade (Opcional)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='qms.colaborador', verbose_name='Colaborador')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_treinamento', to='qms.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Registro de Treinamento',
                'verbose_name_plural': '7.2 Matriz de Treinamentos',
                'unique_together': {('colaborador', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='HierarquiaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('ADM', 'Administrativo'), ('TURNO_1', 'Turno 1'), ('TURNO_2', 'Turno 2'), ('TURNO_3', 'Turno 3'), ('12X36', '12x36')], max_length=20, verbose_name='Turno')),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretoria_setor', to='qms.colaborador', verbose_name='Diretor')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerenciados_setor', to='qms.colaborador', verbose_name='Gerente')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados_setor', to='qms.colaborador', verbose_name='Líder')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisionados_setor', to='qms.colaborador', verbose_name='Supervisor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Definição de Hierarquia',
                'verbose_name_plural': '1.1 Hierarquia (Setor x Turno)',
                'unique_together': {('setor', 'turno')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('setor', 'codigo')},
        ),
    ]
