# Generated by Django 5.2.8 on 2025-11-20 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "0.2 Centros de Custo",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=100)),
                (
                    "razao_social",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("cnpj", models.CharField(max_length=20, unique=True)),
                ("contato", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("escopo_servico", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HOMOLOGADO", "Homologado"),
                            ("BLOQUEADO", "Bloqueado"),
                            ("EM_ANALISE", "Em Análise"),
                        ],
                        default="EM_ANALISE",
                        max_length=20,
                    ),
                ),
                (
                    "nota_media",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
            ],
            options={
                "verbose_name_plural": "5. Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "equipamento",
                    models.CharField(max_length=200, verbose_name="Equipamento"),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fabricante"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Modelo"
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="N° de Série",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Ativo", max_length=50, verbose_name="Status"
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Setor"
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Localização/Area",
                    ),
                ),
                (
                    "frequencia",
                    models.IntegerField(
                        blank=True,
                        help_text="Em meses",
                        null=True,
                        verbose_name="Frequência",
                    ),
                ),
                (
                    "unidade01",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Unidade 01"
                    ),
                ),
                (
                    "faixa01",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Faixa 01"
                    ),
                ),
                (
                    "data01_ultima_calibracao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data 01 - Última Calibração",
                    ),
                ),
                (
                    "data01_prox_calibracao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data 01 - Próxima Calibração",
                    ),
                ),
                (
                    "unidade02",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Unidade 02"
                    ),
                ),
                (
                    "faixa02",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Faixa 02"
                    ),
                ),
                (
                    "data02_ultima_calibracao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data 02 - Última Calibração",
                    ),
                ),
                (
                    "data02_prox_calibracao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data 02 - Próxima Calibração",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "2. Instrumentos",
            },
        ),
        migrations.CreateModel(
            name="PacoteTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Pacote"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Pacote de Treinamento",
                "verbose_name_plural": "7.3 Pacotes de Treinamento",
            },
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "revisao_atual",
                    models.CharField(max_length=10, verbose_name="Revisão Atual"),
                ),
                (
                    "data_revisao",
                    models.DateField(blank=True, null=True, verbose_name="Data Rev."),
                ),
                ("prioridade", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "habilidade_vinculada",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tem_copia_fisica", models.BooleanField(default=False)),
                ("aplica_treinamento", models.BooleanField(default=False)),
                ("link_externo", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Procedimento",
                "verbose_name_plural": "7.1 Procedimentos (GED)",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Setor"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Responsável Genérico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "0.1 Cadastro de Setores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "cargo",
                    models.CharField(max_length=100, verbose_name="Cargo/Função"),
                ),
                (
                    "grupo",
                    models.CharField(max_length=50, verbose_name="Grupo (Macro)"),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrativo"),
                            ("TURNO_1", "Turno 1"),
                            ("TURNO_2", "Turno 2"),
                            ("TURNO_3", "Turno 3"),
                            ("12X36", "12x36"),
                        ],
                        default="ADM",
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salário (R$)",
                    ),
                ),
                (
                    "em_ferias",
                    models.BooleanField(default=False, verbose_name="Está de Férias?"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Colaborador Ativo (RH)"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qms.centrocusto",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "user_django",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de Acesso (Login)",
                    ),
                ),
                (
                    "pacotes_treinamento",
                    models.ManyToManyField(
                        blank=True,
                        related_name="colaboradores",
                        to="qms.pacotetreinamento",
                        verbose_name="Pacotes Atribuídos",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qms.setor",
                        verbose_name="Setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "1. Colaboradores (RH)",
            },
        ),
        migrations.CreateModel(
            name="DocumentoPessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "arquivo",
                    models.FileField(upload_to="rh_docs/", verbose_name="Arquivo"),
                ),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
                ("data_upload", models.DateField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_pessoais",
                        to="qms.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Pessoal",
                "verbose_name_plural": "Documentos Pessoais",
            },
        ),
        migrations.CreateModel(
            name="Ferias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Início")),
                ("data_fim", models.DateField(verbose_name="Fim")),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Obs"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_ferias",
                        to="qms.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Férias",
                "verbose_name_plural": "1.2 Controle de Férias",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_avaliacao", models.DateField(auto_now_add=True)),
                ("nota_tecnica", models.IntegerField(default=10)),
                ("nota_pontualidade", models.IntegerField(default=10)),
                ("nota_atendimento", models.IntegerField(default=10)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qms.colaborador",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="qms.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ocorrencia", models.DateField(verbose_name="Data")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FALTA", "Falta"),
                            ("ATRASO", "Atraso"),
                            ("ADV", "Advertência"),
                            ("ELOGIO", "Elogio"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        choices=[
                            ("NEGATIVA", "🔴 Negativa"),
                            ("POSITIVA", "🟢 Positiva"),
                            ("NEUTRA", "⚪ Neutra"),
                        ],
                        default="NEGATIVA",
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Resumo")),
                ("descricao", models.TextField(verbose_name="Detalhes")),
                (
                    "arquivo_evidencia",
                    models.FileField(blank=True, null=True, upload_to="ocorrencias/"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="qms.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "1.3 Ocorrências",
            },
        ),
        migrations.AddField(
            model_name="pacotetreinamento",
            name="procedimentos",
            field=models.ManyToManyField(
                related_name="pacotes",
                to="qms.procedimento",
                verbose_name="Procedimentos Incluídos",
            ),
        ),
        migrations.CreateModel(
            name="ProcessoCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("data_abertura", models.DateField(auto_now_add=True)),
                ("prazo_limite", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("FECHADO", "Fechado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                ("instrumentos", models.ManyToManyField(to="qms.instrumento")),
                (
                    "responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qms.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6. Processos de Cotação",
            },
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prazo_execucao_dias", models.IntegerField()),
                ("arquivo_proposta", models.FileField(upload_to="orcamentos/")),
                ("vencedor", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qms.fornecedor"
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamentos",
                        to="qms.processocotacao",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="procedimento",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qms.setor",
                verbose_name="Setor Aplicável",
            ),
        ),
        migrations.AddField(
            model_name="centrocusto",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centros_custo",
                to="qms.setor",
                verbose_name="Setor Pertencente",
            ),
        ),
        migrations.CreateModel(
            name="TipoMedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grandeza", models.CharField(default="GERAL", max_length=100)),
                ("faixa", models.CharField(blank=True, max_length=100, null=True)),
                ("unidade", models.CharField(blank=True, max_length=50, null=True)),
                ("resolucao", models.CharField(blank=True, max_length=100, null=True)),
                ("periodicidade_meses", models.IntegerField(default=12)),
                ("data_ultima_calibracao", models.DateField(blank=True, null=True)),
                ("data_proxima_calibracao", models.DateField(blank=True, null=True)),
                (
                    "ultimo_certificado_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicoes",
                        to="qms.instrumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoramento",
                "verbose_name_plural": "3. Painel de Vencimentos",
                "unique_together": {("instrumento", "grandeza")},
            },
        ),
        migrations.CreateModel(
            name="HistoricoCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_calibracao", models.DateField()),
                (
                    "certificado_pdf",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("APROVADO", "Aprovado"),
                            ("COM_RESTricao", "Aprovado c/ Restrição"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="APROVADO",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qms.colaborador",
                    ),
                ),
                (
                    "tipo_medicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="qms.tipomedicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico",
                "verbose_name_plural": "4. Histórico de Calibrações",
                "ordering": ["-data_calibracao"],
            },
        ),
        migrations.CreateModel(
            name="RegistroTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revisao_treinada", models.CharField(max_length=10)),
                ("data_treinamento", models.DateField()),
                ("validade_treinamento", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treinamentos",
                        to="qms.colaborador",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_treinamento",
                        to="qms.procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "7.2 Matriz de Treinamentos",
                "unique_together": {("colaborador", "procedimento")},
            },
        ),
        migrations.CreateModel(
            name="HierarquiaSetor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrativo"),
                            ("TURNO_1", "Turno 1"),
                            ("TURNO_2", "Turno 2"),
                            ("TURNO_3", "Turno 3"),
                            ("12X36", "12x36"),
                        ],
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "diretor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diretoria_setor",
                        to="qms.colaborador",
                        verbose_name="Diretor",
                    ),
                ),
                (
                    "gerente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gerenciados_setor",
                        to="qms.colaborador",
                        verbose_name="Gerente",
                    ),
                ),
                (
                    "lider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liderados_setor",
                        to="qms.colaborador",
                        verbose_name="Líder",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisionados_setor",
                        to="qms.colaborador",
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qms.setor",
                        verbose_name="Setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hierarquia",
                "verbose_name_plural": "1.1 Hierarquia (Setor x Turno)",
                "unique_together": {("setor", "turno")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="centrocusto",
            unique_together={("setor", "codigo")},
        ),
    ]
