# Generated by Django 5.2.8 on 2025-11-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Login (Caixa Alta)')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo (Macro)')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor/Localização')),
                ('centro_custo', models.CharField(max_length=20, verbose_name='Centro de Custo')),
                ('turno', models.CharField(choices=[('ADM', 'Administrativo'), ('1_TURNO', '1º Turno'), ('2_TURNO', '2º Turno'), ('3_TURNO', '3º Turno'), ('12X36', '12x36')], default='ADM', max_length=20, verbose_name='Turno')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('password_last_changed', models.DateField(blank=True, null=True, verbose_name='Última Troca de Senha')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores (Login/RH)',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='Identificação/Tag')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Equipamento')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Série')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor/Localização')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUCATA', 'Sucata')], default='ATIVO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandeza', models.CharField(max_length=100, verbose_name='Grandeza (Ex: Temperatura)')),
                ('faixa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa de Medição')),
                ('resolucao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolução')),
                ('periodicidade_meses', models.IntegerField(default=12, verbose_name='Freq. (Meses)')),
                ('data_ultima_calibracao', models.DateField(blank=True, null=True, verbose_name='Última Calibração')),
                ('data_proxima_calibracao', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='qms.instrumento', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Tipo de Medição',
                'verbose_name_plural': 'Tipos de Medição (Controle Geral)',
                'unique_together': {('instrumento', 'grandeza')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calibracao', models.DateField(verbose_name='Data da Calibração')),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado (PDF)')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('COM_RESTricao', 'Aprovado c/ Restrição'), ('REPROVADO', 'Reprovado')], default='APROVADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador', verbose_name='Responsável Validação')),
                ('tipo_medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='qms.tipomedicao', verbose_name='Tipo de Medição')),
            ],
            options={
                'verbose_name': 'Registro de Histórico',
                'verbose_name_plural': 'Histórico de Calibrações',
                'ordering': ['-data_calibracao'],
            },
        ),
    ]
