# Generated by Django 5.2.8 on 2025-11-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('contato', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('escopo_servico', models.TextField(verbose_name='Escopo de Serviço')),
                ('status', models.CharField(choices=[('HOMOLOGADO', 'Homologado'), ('BLOQUEADO', 'Bloqueado'), ('EM_ANALISE', 'Em Análise')], default='EM_ANALISE', max_length=20)),
                ('nota_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota Média (0-10)')),
            ],
            options={
                'verbose_name': 'Fornecedor / Laboratório',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('nota_tecnica', models.IntegerField(default=10, verbose_name='Capacidade Técnica (0-10)')),
                ('nota_pontualidade', models.IntegerField(default=10, verbose_name='Pontualidade (0-10)')),
                ('nota_atendimento', models.IntegerField(default=10, verbose_name='Atendimento (0-10)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Ocorrências/Obs')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='qms.fornecedor')),
            ],
            options={
                'verbose_name': 'Avaliação de Desempenho',
                'verbose_name_plural': 'Avaliações de Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='ProcessoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título (Ex: Calibração Balanças 2025)')),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('prazo_limite', models.DateField(verbose_name='Prazo para envio das propostas')),
                ('status', models.CharField(choices=[('ABERTO', 'Cotação Aberta'), ('FECHADO', 'Finalizado/Aprovado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('instrumentos', models.ManyToManyField(to='qms.instrumento', verbose_name='Instrumentos do Lote')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador')),
            ],
            options={
                'verbose_name': 'Processo de Cotação',
                'verbose_name_plural': 'Processos de Cotação',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('prazo_execucao_dias', models.IntegerField(verbose_name='Prazo Execução (Dias)')),
                ('arquivo_proposta', models.FileField(upload_to='orcamentos/', verbose_name='PDF da Proposta')),
                ('vencedor', models.BooleanField(default=False, verbose_name='Vencedor?')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='qms.processocotacao')),
            ],
        ),
    ]
