# Generated by Django 5.2.8 on 2025-11-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': '1. Colaboradores'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_revisao',
            field=models.DateField(),
        ),
    ]
