# Generated by Django 5.2.8 on 2025-11-20 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0002_remove_historicocalibracao_tipo_medicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocalibracao',
            name='data_aprovacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Aprovação/Validação'),
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='numero_certificado',
            field=models.CharField(default='S/N', max_length=100, verbose_name='N° do Certificado'),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='resultado',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONDICIONAL', 'Aprovado Condicionalmente')], default='APROVADO', max_length=50, verbose_name='Resultado'),
        ),
        migrations.AlterUniqueTogether(
            name='historicocalibracao',
            unique_together={('instrumento', 'data_calibracao', 'data_aprovacao', 'numero_certificado')},
        ),
    ]
