# Generated by Django 5.2.8 on 2025-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0002_fornecedor_avaliacaofornecedor_processocotacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaofornecedor',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações de Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': '1. Colaboradores (RH)'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': '5. Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='historicocalibracao',
            options={'ordering': ['-data_calibracao'], 'verbose_name': 'Histórico', 'verbose_name_plural': '4. Histórico de Calibrações'},
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'verbose_name': 'Instrumento', 'verbose_name_plural': '2. Instrumentos (Cadastro Físico)'},
        ),
        migrations.AlterModelOptions(
            name='processocotacao',
            options={'verbose_name': 'Processo de Cotação', 'verbose_name_plural': '6. Processos de Cotação'},
        ),
        migrations.AlterModelOptions(
            name='tipomedicao',
            options={'verbose_name': 'Monitoramento de Vencimento', 'verbose_name_plural': '3. Painel de Vencimentos (Tipos de Medição)'},
        ),
        migrations.AlterField(
            model_name='processocotacao',
            name='prazo_limite',
            field=models.DateField(verbose_name='Prazo para envio'),
        ),
        migrations.AlterField(
            model_name='processocotacao',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
