# Generated by Django 5.2.8 on 2025-11-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0003_alter_avaliacaofornecedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('centro_custo', models.CharField(max_length=50, verbose_name='Centro de Custo')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável do Setor')),
            ],
            options={
                'verbose_name': 'Setor / Centro de Custo',
                'verbose_name_plural': '0. Cadastro de Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='localizacao',
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor de Instalação'),
        ),
    ]
