# Generated by Django 5.0.14 on 2025-11-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0003_historicocalibracao_data_aprovacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2.2 Categorias de Instrumentos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '2.1 Unidades de Medida',
            },
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='data01_prox_calibracao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='data01_ultima_calibracao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='data02_prox_calibracao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='data02_ultima_calibracao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='faixa01',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='faixa02',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='unidade01',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='unidade02',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='data_proxima_calibracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='data_ultima_calibracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='descricao',
            field=models.CharField(default='Sem Descrição', max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumento',
            name='frequencia_meses',
            field=models.IntegerField(default=12, verbose_name='Frequência (Meses)'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tag',
            field=models.CharField(default='TAG-000', max_length=50, unique=True, verbose_name='TAG / Identificação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='resultado',
            field=models.CharField(choices=[('APROVADO', 'Aprovado sem correções'), ('CONDICIONAL', 'Aprovado com correções'), ('REPROVADO', 'Reprovado')], default='APROVADO', max_length=50, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.categoriainstrumento', verbose_name='Categoria / Família'),
        ),
        migrations.CreateModel(
            name='FaixaMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('resolucao', models.DecimalField(blank=True, decimal_places=4, help_text='Menor divisão', max_digits=10, null=True)),
                ('incerteza_padrao', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='qms.categoriainstrumento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qms.unidademedida')),
            ],
            options={
                'verbose_name_plural': '2.3 Faixas de Medição',
            },
        ),
    ]
