# Generated by Django 5.0.14 on 2025-11-21 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0004_categoriainstrumento_unidademedida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faixamedicao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='faixamedicao',
            name='instrumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='qms.instrumento'),
            preserve_default=False,
        ),
    ]
