# Generated by Django 5.2.8 on 2025-11-18 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0004_setor_remove_instrumento_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': '0.1 Cadastro de Setores'},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='centro_custo',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável Genérico'),
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (Ex: 2050)')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição (Opcional)')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='qms.setor', verbose_name='Setor Pertencente')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': '0.2 Centros de Custo',
                'unique_together': {('setor', 'codigo')},
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.CreateModel(
            name='HierarquiaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('ADM', 'Administrativo'), ('1_TURNO', '1º Turno'), ('2_TURNO', '2º Turno'), ('3_TURNO', '3º Turno'), ('12X36', '12x36')], max_length=20, verbose_name='Turno')),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretoria_setor', to='qms.colaborador', verbose_name='Diretor')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerenciados_setor', to='qms.colaborador', verbose_name='Gerente')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados_setor', to='qms.colaborador', verbose_name='Líder')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms.setor', verbose_name='Setor')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisionados_setor', to='qms.colaborador', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Definição de Hierarquia',
                'verbose_name_plural': '1.1 Hierarquia (Setor x Turno)',
                'unique_together': {('setor', 'turno')},
            },
        ),
    ]
