# Generated by Django 5.2.8 on 2025-11-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0005_alter_setor_options_remove_setor_centro_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor de Instalação'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código (Ex: POP-01)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Procedimento')),
                ('revisao_atual', models.CharField(max_length=10, verbose_name='Revisão Atual (Ex: 05)')),
                ('data_revisao', models.DateField(verbose_name='Data da Revisão')),
                ('link_externo', models.URLField(blank=True, null=True, verbose_name='Link para Qualiex (Opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.setor', verbose_name='Setor Aplicável')),
            ],
            options={
                'verbose_name': 'Documento (POP/IT)',
                'verbose_name_plural': '7.1 Cadastro de Documentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao_treinada', models.CharField(max_length=10, verbose_name='Revisão Treinada')),
                ('data_treinamento', models.DateField(verbose_name='Data do Treinamento')),
                ('validade_treinamento', models.DateField(blank=True, null=True, verbose_name='Validade (Opcional)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='qms.colaborador', verbose_name='Colaborador')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_treinamento', to='qms.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Registro de Treinamento',
                'verbose_name_plural': '7.2 Matriz de Treinamentos',
                'unique_together': {('colaborador', 'documento')},
            },
        ),
    ]
