# Generated by Django 5.0.14 on 2025-11-22 02:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0005_remove_faixamedicao_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faixamedicao',
            name='incerteza_padrao',
        ),
        migrations.AddField(
            model_name='faixamedicao',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor central/nominal do processo', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='faixamedicao',
            name='tolerancia_mais_menos',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Variação aceitável (+/-)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='erro_encontrado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Erro (E)'),
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='incerteza',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Incerteza (U)'),
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='tolerancia_usada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tol. Processo (+/-)'),
        ),
        migrations.AlterField(
            model_name='faixamedicao',
            name='resolucao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='data_aprovacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='data_calibracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_calibracoes', to='qms.instrumento'),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='numero_certificado',
            field=models.CharField(default='S/N', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='proxima_calibracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.colaborador'),
        ),
        migrations.AlterField(
            model_name='historicocalibracao',
            name='resultado',
            field=models.CharField(choices=[('APROVADO', 'Aprovado sem correções'), ('CONDICIONAL', 'Aprovado com correções'), ('REPROVADO', 'Reprovado')], default='APROVADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.categoriainstrumento'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='frequencia_meses',
            field=models.IntegerField(default=12),
        ),
    ]
