# Generated by Django 5.0.14 on 2025-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0008_alter_colaborador_turno_alter_hierarquiasetor_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Padrão')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_certificado', models.CharField(max_length=100, verbose_name='Nº Certificado')),
                ('data_calibracao', models.DateField(verbose_name='Data Calib.')),
                ('data_validade', models.DateField(verbose_name='Validade do Padrão')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='padroes/', verbose_name='PDF do Certificado')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Padrão / Kit',
                'verbose_name_plural': '3. Padrões de Rastreabilidade',
            },
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='tem_selo_rbc',
            field=models.BooleanField(default=False, verbose_name='Possui Selo RBC?'),
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='tipo_calibracao',
            field=models.CharField(choices=[('EXTERNA', 'Externa (Fornecedor)'), ('INTERNA', 'Interna (Equipe Própria)')], default='EXTERNA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('TURNO_1', 'Turno 1'), ('TURNO_2', 'Turno 2'), ('TURNO_3', 'Turno 3'), ('12X36', '12x36')], default='ADM', max_length=20, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='hierarquiasetor',
            name='turno',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('TURNO_1', 'Turno 1'), ('TURNO_2', 'Turno 2'), ('TURNO_3', 'Turno 3'), ('12X36', '12x36')], max_length=20, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='historicocalibracao',
            name='padroes_utilizados',
            field=models.ManyToManyField(blank=True, to='qms.padrao', verbose_name='Padrões Utilizados (Kits)'),
        ),
    ]
