# Generated by Django 5.0.14 on 2025-11-24 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0013_solicitacaoinstrumento_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'verbose_name': 'Ocorrência', 'verbose_name_plural': '1.3 Ocorrências'},
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='custo_reparo',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='usuario_responsavel',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='arquivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='ocorrencias/'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='qms.colaborador'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='natureza',
            field=models.CharField(choices=[('NEGATIVA', '🔴 Negativa'), ('POSITIVA', '🟢 Positiva'), ('NEUTRA', '⚪ Neutra')], default='NEGATIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_ocorrencia',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.CharField(choices=[('FALTA', 'Falta'), ('ATRASO', 'Atraso'), ('ADV', 'Advertência'), ('ELOGIO', 'Elogio'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.CreateModel(
            name='OcorrenciaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUTENCAO', 'Manutenção Corretiva'), ('QUEDA', 'Queda/Dano Físico'), ('AJUSTE', 'Ajuste Interno'), ('OUTRO', 'Outros')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateField(default=django.utils.timezone.now)),
                ('custo_reparo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='qms.instrumento')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
