# Generated by Django on 2025-11-24

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0015_colaborador_gerente_colaborador_supervisor"),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Em Progresso'), ('SUCCESS', 'Concluído'), ('FAILURE', 'Falha')], default='PENDING', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={'verbose_name': 'Import Job', 'verbose_name_plural': 'Import Jobs'},
        ),
    ]
