# Generated by Django 5.0.14 on 2025-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0016_create_importjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="job_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
