# Generated by Django 5.0.14 on 2025-11-28 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0018_merge_20251127_1352"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Área"
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "7.0 Áreas (Macro)",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="procedimento",
            name="aprovador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedimentos_aprovados",
                to="qms.colaborador",
                verbose_name="Aprovador",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="procedimentos/",
                verbose_name="Arquivo do Procedimento (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="data_aprovacao_revisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Aprovação Revisão"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="elaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedimentos_elaborados",
                to="qms.colaborador",
                verbose_name="Elaborador",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="revisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedimentos_revisados",
                to="qms.colaborador",
                verbose_name="Revisor",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("POP", "POP"),
                    ("DOC", "DOC"),
                    ("FOR", "FOR"),
                    ("TAB", "TAB"),
                    ("DEX", "DEX"),
                    ("OUTRO", "OUTRO"),
                ],
                default="OUTRO",
                max_length=10,
                verbose_name="Tipo de Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrenciainstrumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CALIBRACAO", "Calibração"),
                    ("VERIFICACAO", "Verificação"),
                    ("INSPECAO", "Inspeção"),
                    ("AJUSTE", "Ajuste"),
                    ("MANUTENCAO", "Manutenção"),
                    ("AVARIA", "Avaria/Dano"),
                    ("EXTRAVIO", "Extravio/Perda"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="data_revisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Revisão"
            ),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="revisao_atual",
            field=models.CharField(max_length=10, verbose_name="Nº Revisão"),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qms.setor",
                verbose_name="Setor Associado",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qms.area",
                verbose_name="Área Associada",
            ),
        ),
        migrations.CreateModel(
            name="ProcedimentoRevisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revisao", models.CharField(max_length=10)),
                ("data_revisao", models.DateField(blank=True, null=True)),
                ("data_aprovacao", models.DateField(blank=True, null=True)),
                (
                    "arquivo_prev",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="procedimentos/rev/",
                        verbose_name="Arquivo Revisão Anterior",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aprovador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_aprovadas",
                        to="qms.colaborador",
                    ),
                ),
                (
                    "elaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_elaboradas",
                        to="qms.colaborador",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_revisoes",
                        to="qms.procedimento",
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_revisadas",
                        to="qms.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Revisão de Procedimento",
                "verbose_name_plural": "7.1.1 Histórico de Revisões",
                "ordering": ["-criado_em"],
            },
        ),
    ]
