# Generated by Django 5.0.14 on 2025-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0019_area_procedimento_aprovador_procedimento_arquivo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["nome"],
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas (Macro)",
            },
        ),
        migrations.AlterModelOptions(
            name="categoriainstrumento",
            options={"verbose_name_plural": "Categorias de Instrumentos"},
        ),
        migrations.AlterModelOptions(
            name="centrocusto",
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
            },
        ),
        migrations.AlterModelOptions(
            name="colaborador",
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores (RH)",
            },
        ),
        migrations.AlterModelOptions(
            name="faixamedicao",
            options={"verbose_name_plural": "Faixas de Medição"},
        ),
        migrations.AlterModelOptions(
            name="fornecedor",
            options={"verbose_name_plural": "Fornecedores"},
        ),
        migrations.AlterModelOptions(
            name="hierarquiasetor",
            options={
                "verbose_name": "Hierarquia",
                "verbose_name_plural": "Hierarquia (Setor x Turno)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicocalibracao",
            options={
                "ordering": ["-data_calibracao"],
                "verbose_name": "Histórico de Calibração",
                "verbose_name_plural": "Histórico de Calibrações",
            },
        ),
        migrations.AlterModelOptions(
            name="instrumento",
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
            },
        ),
        migrations.AlterModelOptions(
            name="ocorrencia",
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
            },
        ),
        migrations.AlterModelOptions(
            name="pacotetreinamento",
            options={
                "verbose_name": "Pacote de Treinamento",
                "verbose_name_plural": "Pacotes de Treinamento",
            },
        ),
        migrations.AlterModelOptions(
            name="padrao",
            options={
                "verbose_name": "Padrão / Kit",
                "verbose_name_plural": "Padrões de Rastreabilidade",
            },
        ),
        migrations.AlterModelOptions(
            name="procedimento",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Procedimento",
                "verbose_name_plural": "Procedimentos (GED)",
            },
        ),
        migrations.AlterModelOptions(
            name="procedimentorevisao",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Histórico de Revisão de Procedimento",
                "verbose_name_plural": "Histórico de Revisões",
            },
        ),
        migrations.AlterModelOptions(
            name="processocotacao",
            options={"verbose_name_plural": "Processos de Cotação"},
        ),
        migrations.AlterModelOptions(
            name="registrotreinamento",
            options={"verbose_name_plural": "Matriz de Treinamentos"},
        ),
        migrations.AlterModelOptions(
            name="setor",
            options={
                "ordering": ["nome"],
                "verbose_name": "Setor",
                "verbose_name_plural": "Cadastro de Setores",
            },
        ),
        migrations.AlterModelOptions(
            name="unidademedida",
            options={"verbose_name_plural": "Unidades de Medida"},
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="aplica_treinamento",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="aprovador",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="area",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="arquivo",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="data_aprovacao_revisao",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="data_revisao",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="elaborador",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="habilidade_vinculada",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="link_externo",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="prioridade",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="revisao_atual",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="revisor",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="setor",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="tem_copia_fisica",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="titulo",
        ),
        migrations.AddField(
            model_name="procedimento",
            name="autor",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Autor (Texto Livre)",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="classificacao",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Classificação (Tipo de Procedimento)",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="data_aprovacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="data_validade",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Validade"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição/Objetivo/Função"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="documentos_controlados",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Documentos Controlados",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="matriz",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Matriz"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="no",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="No."
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="nome",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nome/Título do Documento",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="numero_revisao",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número da Revisão"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="pasta",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Pasta (Local no Qualiex)",
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="proxima_revisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Próxima Revisão"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="sub_area",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Sub-Área"
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="ultima_revisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Última Revisão"
            ),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Código"
            ),
        ),
    ]
