# Generated by Django 5.0.14 on 2025-11-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0020_alter_area_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedimento",
            name="no",
        ),
    ]
