# Generated by Copilot to remove Padrao model and padroes_utilizados field from HistoricoCalibracao
from django.db import migrations

def remove_padroes_and_field(apps, schema_editor):
    # Remove the Padrao table and the M2M field from HistoricoCalibracao
    # This is a no-op for data, as Django will handle schema changes
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("qms", "0020_alter_area_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicocalibracao",
            name="padroes_utilizados",
        ),
        migrations.DeleteModel(
            name="Padrao",
        ),
    ]
