# Generated by Django 5.0.14 on 2025-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0021_remove_procedimento_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumento",
            name="tolerancia_processo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Tolerância do processo (+/-), associada ao instrumento",
                max_digits=10,
                null=True,
            ),
        ),
    ]
