# Generated by Django 5.0.14 on 2025-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0022_instrumento_tolerancia_processo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicocalibracao",
            name="certificado_carimbado",
            field=models.FileField(
                blank=True, null=True, upload_to="certificados/carimbados/"
            ),
        ),
        migrations.AddField(
            model_name="historicocalibracao",
            name="certificado_validado",
            field=models.BooleanField(default=False),
        ),
    ]
