# Generated by Django 5.0.14 on 2025-12-02 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0023_historicocalibracao_certificado_carimbado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoFaixaCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erro_encontrado",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Erro Encontrado"
                    ),
                ),
                (
                    "incerteza",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Incerteza Expandida",
                    ),
                ),
                (
                    "tolerancia_usada",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Tolerância Usada"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("APROVADO", "Aprovado"),
                            ("CONDICIONAL", "Condicional"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        editable=False,
                        max_length=15,
                        verbose_name="Resultado da Calibração",
                    ),
                ),
                (
                    "desconsiderada",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se esta faixa não foi calibrada neste certificado",
                        verbose_name="Desconsiderar esta faixa",
                    ),
                ),
                (
                    "faixa_medicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_calibracao",
                        to="qms.faixamedicao",
                        verbose_name="Faixa de Medição",
                    ),
                ),
                (
                    "historico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_faixas",
                        to="qms.historicocalibracao",
                        verbose_name="Histórico de Calibração",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado por Faixa",
                "verbose_name_plural": "Resultados por Faixa",
                "ordering": ["faixa_medicao__valor_minimo"],
                "unique_together": {("historico", "faixa_medicao")},
            },
        ),
    ]
