# Generated by Django 5.0.14 on 2025-12-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0024_resultadofaixacalibracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadofaixacalibracao",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("APROVADO_SEM_CORRECAO", "Aprovado sem correção"),
                    ("APROVADO_COM_CORRECAO", "Aprovado com Correção"),
                    ("REPROVADO", "Reprovado"),
                ],
                editable=False,
                max_length=30,
                verbose_name="Resultado da Calibração",
            ),
        ),
    ]
