# Generated by Django 5.0.14 on 2025-12-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0025_alter_resultadofaixacalibracao_resultado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicocalibracao",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("APROVADO_SEM_CORRECAO", "Aprovado sem correção"),
                    ("APROVADO_COM_CORRECAO", "Aprovado com Correção"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="APROVADO_SEM_CORRECAO",
                max_length=50,
            ),
        ),
    ]
