# Generated by Django 5.0.14 on 2025-12-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0022_add_arquivos_padroes"),
        ("qms", "0027_fix_legacy_results"),
    ]

    operations = []
