# Generated by Django 5.0.14 on 2025-12-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0028_merge_20251202_1710"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arquivopadrao",
            options={
                "verbose_name": "Arquivo de Padrão",
                "verbose_name_plural": "Arquivos de Padrão",
            },
        ),
        migrations.AlterModelOptions(
            name="historicocalibracao",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="historicocalibracao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="arquivopadrao",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arquivos_padroes_instrumento",
                to="qms.instrumento",
            ),
        ),
        migrations.AlterField(
            model_name="arquivopadrao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="historicocalibracao",
            name="instrumento",
        ),
    ]
