# Generated by Django 5.0.14 on 2025-12-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0029_alter_arquivopadrao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicocalibracao",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historicos",
                to="qms.instrumento",
                verbose_name="Instrumento",
            ),
        ),
    ]
