# Generated by Django 5.0.14 on 2025-12-08 22:24
# Phase 9 Modularization - qms models consolidated to 3 cross-app coordinators
# All other models have been moved to their respective apps

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0030_historicocalibracao_instrumento"),
    ]

    operations = [
        # No operations - all model deletions handled by individual app migrations
    ]
