# Generated by Django 5.0.14 on 2025-12-09 02:19
# This is a no-op migration to acknowledge the Phase 9 modularization
# All model deletions and reorganizations have been handled at the database level

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0002_initial"),
        ("qms", "0031_phase9_modularization_cleanup"),
    ]

    operations = [
        # No-op migration: All schema changes from Phase 9 modularization
        # have already been applied to the database.
        # This migration serves as a checkpoint to prevent re-applying changes.
    ]
