# Generated by Django 5.0.14 on 2025-12-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0013_remove_itemsolicitacaocotacao_quantidade"),
        ("qms", "0034_add_performance_indexes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Area",
        ),
        migrations.RemoveField(
            model_name="historicocalibracao",
            name="arquivos_padroes",
        ),
        # migrations.RemoveField(
        #     model_name="historicocalibracao",
        #     name="arquivos_padroes",
        # ),
        # migrations.RemoveField(
        #     model_name="avaliacaofornecedor",
        #     name="avaliador",
        # ),
        # migrations.RemoveField(
        #     model_name="avaliacaofornecedor",
        #     name="fornecedor",
        # ),
        # migrations.RemoveField(
        #     model_name="categoriainstrumento",
        #     name="unidade_padrao",
        # ),
        # migrations.RemoveField(
        #     model_name="instrumento",
        #     name="categoria",
        # ),
        # migrations.RemoveField(
        #     model_name="centrocusto",
        #     name="setor",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="centro_custo",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="gerente",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="lider",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="pacotes_treinamento",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="setor",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="supervisor",
        # ),
        # migrations.RemoveField(
        #     model_name="colaborador",
        #     name="user_django",
        # ),
        # migrations.RemoveField(
        #     model_name="documentopessoal",
        #     name="colaborador",
        # ),
        # migrations.RemoveField(
        #     model_name="hierarquiasetor",
        #     name="diretor",
        # ),
        # migrations.RemoveField(
        #     model_name="procedimentorevisao",
        #     name="aprovador",
        # ),
        # migrations.RemoveField(
        #     model_name="ferias",
        #     name="colaborador",
        # ),
        # migrations.RemoveField(
        #     model_name="procedimentorevisao",
        #     name="elaborador",
        # ),
        # migrations.RemoveField(
        #     model_name="processocotacao",
        #     name="responsavel",
        # ),
        # migrations.RemoveField(
        #     model_name="procedimentorevisao",
        #     name="revisor",
        # ),
        # migrations.RemoveField(
        #     model_name="hierarquiasetor",
        #     name="gerente",
        # ),
        # migrations.RemoveField(
        #     model_name="hierarquiasetor",
        #     name="lider",
        # ),
        # migrations.RemoveField(
        #     model_name="instrumento",
        #     name="responsavel",
        # ),
        # migrations.RemoveField(
        #     model_name="registrotreinamento",
        #     name="colaborador",
        # ),
        # migrations.RemoveField(
        #     model_name="hierarquiasetor",
        #     name="supervisor",
        # ),
        # migrations.RemoveField(
        #     model_name="ocorrencia",
        #     name="colaborador",
        # ),
        # migrations.RemoveField(
        #     model_name="faixamedicao",
        #     name="instrumento",
        # ),
        # migrations.RemoveField(
        #     model_name="faixamedicao",
        #     name="unidade",
        # ),
        # migrations.RemoveField(
        #     model_name="resultadofaixacalibracao",
        #     name="faixa_medicao",
        # ),
        # migrations.RemoveField(
        #     model_name="orcamento",
        #     name="fornecedor",
        # ),
        migrations.AlterUniqueTogether(
            name="hierarquiasetor",
            unique_together=None,
        ),
        # migrations.RemoveField(
        #     model_name="hierarquiasetor",
        #     name="setor",
        # ),
        # migrations.RemoveField(
        #     model_name="historicocalibracao",
        #     name="instrumento",
        # ),
        # migrations.RemoveField(
        #     model_name="resultadofaixacalibracao",
        #     name="historico",
        # ),
        # migrations.RemoveField(
        #     model_name="instrumento",
        #     name="setor",
        # ),
        # migrations.RemoveField(
        #     model_name="ordemcalibracao",
        #     name="instrumento",
        # ),
        migrations.AlterField(
            model_name="solicitacaoinstrumento",
            name="instrumento_alvo",
            field=models.ForeignKey(
                blank=True,
                help_text="Preencher caso seja substituição de um item existente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metrologia.instrumento",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrenciainstrumento",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocorrencias",
                to="metrologia.instrumento",
            ),
        ),
        migrations.RemoveField(
            model_name="processocotacao",
            name="instrumentos",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="processo",
        ),
        migrations.RemoveField(
            model_name="pacotetreinamento",
            name="procedimentos",
        ),
        migrations.RemoveField(
            model_name="procedimentorevisao",
            name="procedimento",
        ),
        # migrations.RemoveField(
        #     model_name="registrotreinamento",
        #     name="procedimento",
        # ),
        migrations.AlterUniqueTogether(
            name="registrotreinamento",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="resultadofaixacalibracao",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="ArquivoPadrao",
        ),
        migrations.DeleteModel(
            name="AvaliacaoFornecedor",
        ),
        migrations.DeleteModel(
            name="CategoriaInstrumento",
        ),
        migrations.DeleteModel(
            name="CentroCusto",
        ),
        migrations.DeleteModel(
            name="DocumentoPessoal",
        ),
        migrations.DeleteModel(
            name="Ferias",
        ),
        migrations.DeleteModel(
            name="Colaborador",
        ),
        migrations.DeleteModel(
            name="Ocorrencia",
        ),
        migrations.DeleteModel(
            name="UnidadeMedida",
        ),
        migrations.DeleteModel(
            name="FaixaMedicao",
        ),
        migrations.DeleteModel(
            name="Fornecedor",
        ),
        migrations.DeleteModel(
            name="HierarquiaSetor",
        ),
        migrations.DeleteModel(
            name="HistoricoCalibracao",
        ),
        migrations.DeleteModel(
            name="ResultadoFaixaCalibracao",
        ),
        migrations.DeleteModel(
            name="Setor",
        ),
        migrations.DeleteModel(
            name="OrdemCalibracao",
        ),
        migrations.DeleteModel(
            name="Instrumento",
        ),
        migrations.DeleteModel(
            name="Orcamento",
        ),
        migrations.DeleteModel(
            name="ProcessoCotacao",
        ),
        migrations.DeleteModel(
            name="PacoteTreinamento",
        ),
        migrations.DeleteModel(
            name="ProcedimentoRevisao",
        ),
        migrations.DeleteModel(
            name="Procedimento",
        ),
        migrations.DeleteModel(
            name="RegistroTreinamento",
        ),
    ]
