# Generated by Django 5.0.14 on 2026-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0035_delete_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciainstrumento',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrenciainstrumento',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=20),
        ),
    ]
