# Generated by Django 5.0.14 on 2025-12-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoPessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(max_length=50, verbose_name="Tipo de Documento"),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_pessoais/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Documento Pessoal",
                "verbose_name_plural": "Documentos Pessoais",
                "ordering": ["colaborador", "tipo_documento"],
            },
        ),
        migrations.CreateModel(
            name="Ferias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Término")),
                (
                    "dias_solicitados",
                    models.IntegerField(verbose_name="Dias Solicitados"),
                ),
                (
                    "aprovada",
                    models.BooleanField(default=False, verbose_name="Aprovada?"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Férias",
                "verbose_name_plural": "Período de Férias",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_ocorrencia",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data da Ocorrência"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AVISO", "Aviso"),
                            ("ADVERTENCIA", "Advertência"),
                            ("SUSPENSAO", "Suspensão"),
                            ("DEMISSAO", "Demissão"),
                            ("ELOGIO", "Elogio"),
                            ("REABILITACAO", "Reabilitação"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ocorrência",
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        choices=[
                            ("POSITIVA", "Positiva"),
                            ("NEGATIVA", "Negativa"),
                            ("NEUTRA", "Neutra"),
                        ],
                        max_length=20,
                        verbose_name="Natureza",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Motivo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências (RH)",
                "ordering": ["-data_ocorrencia"],
            },
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "grupo",
                    models.CharField(max_length=50, verbose_name="Grupo (Macro)"),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrativo"),
                            ("TURNO_1", "Turno 1"),
                            ("TURNO_2", "Turno 2"),
                            ("TURNO_3", "Turno 3"),
                            ("12X36", "12x36"),
                        ],
                        default="ADM",
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salário (R$)",
                    ),
                ),
                (
                    "em_ferias",
                    models.BooleanField(default=False, verbose_name="Está de Férias?"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Colaborador Ativo (RH)"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.centrocusto",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "gerente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gerenciados",
                        to="rh.colaborador",
                        verbose_name="Gerente",
                    ),
                ),
                (
                    "lider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liderados",
                        to="rh.colaborador",
                        verbose_name="Líder/Supervisor Direto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores (RH)",
            },
        ),
    ]
