# Generated by Django 5.0.14 on 2025-12-08 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0002_initial"),
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="setor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.setor",
                verbose_name="Setor",
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisionados",
                to="rh.colaborador",
                verbose_name="Supervisor",
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="user_django",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário de Acesso (Login)",
            ),
        ),
        migrations.AddField(
            model_name="documentopessoal",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="rh.colaborador",
                verbose_name="Colaborador",
            ),
        ),
        migrations.AddField(
            model_name="ferias",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.colaborador",
                verbose_name="Colaborador",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocorrencias",
                to="rh.colaborador",
                verbose_name="Colaborador",
            ),
        ),
    ]
