# Generated by Django 5.0.14 on 2025-12-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_initial"),
        ("rh", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_mudanca",
                    models.CharField(
                        choices=[
                            ("SETOR", "Mudança de Setor"),
                            ("CARGO", "Mudança de Cargo"),
                            ("SALARIO", "Mudança de Salário"),
                            ("TURNO", "Mudança de Turno"),
                            ("STATUS", "Mudança de Status"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Mudança",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Mudança")),
                (
                    "dados_anteriores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados Anteriores"
                    ),
                ),
                ("dados_novos", models.JSONField(verbose_name="Dados Novos")),
                (
                    "data_mudanca",
                    models.DateField(auto_now_add=True, verbose_name="Data da Mudança"),
                ),
                (
                    "data_efetiva",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Efetiva"
                    ),
                ),
                (
                    "aprovado",
                    models.BooleanField(default=False, verbose_name="Aprovado"),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mudancas_colaborador_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_geral",
                        to="rh.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mudancas_colaborador_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Colaborador",
                "verbose_name_plural": "Histórico Geral de Colaboradores",
                "ordering": ["-data_mudanca"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoPosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo_anterior",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Cargo Anterior",
                    ),
                ),
                (
                    "cargo_novo",
                    models.CharField(max_length=100, verbose_name="Novo Cargo"),
                ),
                (
                    "data_mudanca",
                    models.DateField(auto_now_add=True, verbose_name="Data da Mudança"),
                ),
                (
                    "data_efetiva",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Efetiva"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Motivo"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_posto",
                        to="rh.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mudancas_cargo_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Posto",
                "verbose_name_plural": "Histórico de Postos",
                "ordering": ["-data_mudanca"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoSalario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salario_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salário Anterior",
                    ),
                ),
                (
                    "salario_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Novo Salário"
                    ),
                ),
                (
                    "diferenca",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Diferença",
                    ),
                ),
                (
                    "data_mudanca",
                    models.DateField(auto_now_add=True, verbose_name="Data da Mudança"),
                ),
                (
                    "data_efetiva",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Efetiva"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Motivo"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_salario",
                        to="rh.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mudancas_salario_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Salário",
                "verbose_name_plural": "Histórico de Salários",
                "ordering": ["-data_mudanca"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoSetor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_mudanca",
                    models.DateField(auto_now_add=True, verbose_name="Data da Mudança"),
                ),
                (
                    "data_efetiva",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Efetiva"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Motivo"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_setor",
                        to="rh.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mudancas_setor_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "setor_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_saida",
                        to="organization.setor",
                        verbose_name="Setor Anterior",
                    ),
                ),
                (
                    "setor_novo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_entrada",
                        to="organization.setor",
                        verbose_name="Setor Novo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Setor",
                "verbose_name_plural": "Histórico de Setores",
                "ordering": ["-data_mudanca"],
            },
        ),
    ]
