# Generated by Django 5.0.14 on 2025-12-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0003_historicocolaborador_historicoposto_historicosalario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="arquivo_evidencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ocorrencias_evidencias/",
                verbose_name="Arquivo de Evidência",
            ),
        ),
    ]
