# Generated by Django 5.0.14 on 2025-12-11

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_ocorrencia_arquivo_evidencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="data_ocorrencia",
            field=models.DateField(default=date.today, verbose_name="Data da Ocorrência"),
        ),
    ]
