# Generated by Django 5.0.14 on 2025-12-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0005_alter_ocorrencia_data_ocorrencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="condutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias_conduzidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável pela Ocorrência (Quem está conduzindo)",
            ),
        ),
    ]
