# Generated by Django 5.0.14 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0006_ocorrencia_condutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("AVISO", "Aviso"),
                    ("ADVERTENCIA", "Advertência"),
                    ("SUSPENSAO", "Suspensão"),
                    ("DEMISSAO", "Demissão"),
                    ("ELOGIO", "Elogio"),
                    ("REABILITACAO", "Reabilitação"),
                    ("FEEDBACK", "Feedback"),
                ],
                max_length=20,
                verbose_name="Tipo de Ocorrência",
            ),
        ),
    ]
