# Generated by Django 5.0.14 on 2025-12-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0007_alter_ocorrencia_tipo"),
    ]

    operations = [
        # Remover atribuição automática de natureza - agora é obrigatória
        # A lógica de save() foi removida para forçar preenchimento manual
    ]
