# Generated by Django 5.0.14 on 2025-12-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0008_remove_automatic_natureza"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferias",
            name="vencimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vencimento das Férias"
            ),
        ),
    ]
