# Generated by Django 5.0.14 on 2025-12-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0009_ferias_vencimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferias",
            name="periodo_aquisitivo_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim do Período Aquisitivo"
            ),
        ),
        migrations.AddField(
            model_name="ferias",
            name="periodo_aquisitivo_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início do Período Aquisitivo"
            ),
        ),
        migrations.AddField(
            model_name="ferias",
            name="status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Status das Férias"
            ),
        ),
    ]
