# Generated by Django 5.0.14 on 2025-12-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0010_ferias_periodo_aquisitivo_fim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferias",
            name="status",
            field=models.CharField(
                choices=[
                    ("AQUISITIVO", "Aquisitivo"),
                    ("PROGRAMADAS", "Programadas"),
                    ("GOZADAS", "Gozadas"),
                    ("VENDIDAS", "Vendidas"),
                    ("ABONO", "Abono"),
                    ("OUTRO", "Outro"),
                ],
                default="AQUISITIVO",
                max_length=20,
                verbose_name="Status das Férias",
            ),
        ),
    ]
