# Generated by Django 5.0.14 on 2025-12-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0011_alter_ferias_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferias",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANEJADO", "Planejado"),
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("CONCLUIDO", "Concluído"),
                ],
                default="PLANEJADO",
                max_length=20,
                verbose_name="Status das Férias",
            ),
        ),
    ]
