# Generated by Django 5.0.14 on 2025-12-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0001_initial"),
        ("rh", "0013_remove_ferias_periodo_aquisitivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="pacotes_treinamento",
            field=models.ManyToManyField(
                blank=True,
                related_name="colaboradores",
                to="procedures.pacotetreinamento",
                verbose_name="Pacotes Atribuídos",
            ),
        ),
    ]
