# Generated by Django 5.0.14 on 2026-01-08 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_initial"),
        ("procedures", "0027_update_criticidade_choices"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["setor", "is_active"], name="rh_colabora_setor_i_ea0ed8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["lider", "-matricula"], name="rh_colabora_lider_i_83e864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["em_ferias", "setor"], name="rh_colabora_em_feri_59ee0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["is_active", "-criado_em"],
                name="rh_colabora_is_acti_709c9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(
                fields=["colaborador", "data_inicio", "data_fim"],
                name="rh_ferias_colabor_773af1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(
                fields=["status", "-data_inicio"], name="rh_ferias_status_77d6bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(
                fields=["aprovada", "data_inicio", "data_fim"],
                name="rh_ferias_aprovad_e247e9_idx",
            ),
        ),
    ]
