# Generated by Django 5.0.14 on 2026-01-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_colaborador_rh_colabora_setor_i_ea0ed8_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS rh_colaborador_pacotes_treinamento (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                colaborador_id INTEGER NOT NULL REFERENCES rh_colaborador(id),
                pacotetreinamento_id INTEGER NOT NULL REFERENCES procedures_pacotetreinamento(id),
                UNIQUE(colaborador_id, pacotetreinamento_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS rh_colaborador_pacotes_treinamento;",
        ),
    ]
