# Generated by Django 5.0.14 on 2026-01-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_fix_pacotes_treinamento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='afastado',
            field=models.BooleanField(default=False, help_text='Marque se colaborador está afastado (INSS, Licença, etc.)', verbose_name='Colaborador Afastado?'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_fim_afastamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim do Afastamento'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_inicio_afastamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início do Afastamento'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_afastamento',
            field=models.CharField(blank=True, help_text='Ex: INSS, LICENÇA_MATERNIDADE, LICENÇA_PATERNIDADE, FÉRIAS, OUTRO', max_length=100, null=True, verbose_name='Tipo de Afastamento'),
        ),
    ]
