# Generated by Django 5.0.14 on 2026-03-02 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('procedures', '0032_procedimento_proc_criticidade_idx_and_more'),
        ('rh', '0017_colaborador_afastado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['turno'], name='rh_colaborador_turno_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['is_active', 'afastado', 'em_ferias', 'turno', 'setor'], name='rh_colab_dash_filters_idx'),
        ),
    ]
