# Generated by Django 5.0.14 on 2026-06-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_colaborador_rh_colaborador_turno_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Planejamento')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('horas_extras', models.DurationField(verbose_name='Horas Extras')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaboradores', models.ManyToManyField(related_name='planejamentos_hora_extra', to='rh.colaborador', verbose_name='Colaboradores convocados')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Planejamento de Hora Extra',
                'verbose_name_plural': 'Planejamentos de Horas Extras',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
