# Generated by Django 5.0.14 on 2026-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_planejamentohoraextra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamentohoraextra',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Planejamento (Hora Extra / Folga)', 'verbose_name_plural': 'Planejamentos (Horas Extras e Absenteísmo)'},
        ),
        migrations.AddField(
            model_name='planejamentohoraextra',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='planejamentohoraextra',
            name='data_hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='planejamentohoraextra',
            name='tipo',
            field=models.CharField(choices=[('HORA_EXTRA', 'Hora Extra'), ('FOLGA', 'Folga Planejada')], default='HORA_EXTRA', max_length=20, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='planejamentohoraextra',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Planejamento'),
        ),
        migrations.AlterField(
            model_name='planejamentohoraextra',
            name='horas_extras',
            field=models.DurationField(blank=True, null=True, verbose_name='Horas Extras'),
        ),
    ]
