# Generated by Django 5.0.14 on 2026-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_alter_planejamentohoraextra_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Motivo')),
                ('tipo', models.CharField(choices=[('HORA_EXTRA', 'Hora Extra'), ('FOLGA', 'Folga Planejada'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=20, verbose_name='Categoria/Tipo')),
            ],
            options={
                'verbose_name': 'Motivo de Planejamento',
                'verbose_name_plural': 'Motivos de Planejamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='planejamentohoraextra',
            name='motivos',
            field=models.ManyToManyField(blank=True, related_name='planejamentos', to='rh.motivoplanejamento', verbose_name='Motivos Categorizados'),
        ),
    ]
