# Generated by Django 5.0.14 on 2026-06-19 13:35

from django.db import migrations


def seed_motivos(apps, schema_editor):
    MotivoPlanejamento = apps.get_model('rh', 'MotivoPlanejamento')
    
    motivos_padrao = [
        # Hora Extra
        ('Inventário', 'HORA_EXTRA'),
        ('Pico de Demanda / Produção Extra', 'HORA_EXTRA'),
        ('Manutenção Preventiva / Corretiva', 'HORA_EXTRA'),
        ('Treinamento / Evento corporativo', 'HORA_EXTRA'),
        # Folga
        ('Folga Compensatória (Banco de Horas)', 'FOLGA'),
        ('Feriado Ponte', 'FOLGA'),
        ('Licença Casamento / Óbito', 'FOLGA'),
        ('Licença Médica / Tratamento', 'FOLGA'),
        # Ambos
        ('Outros', 'AMBOS'),
    ]
    
    for nome, tipo in motivos_padrao:
        MotivoPlanejamento.objects.get_or_create(nome=nome, defaults={'tipo': tipo})


def remove_motivos(apps, schema_editor):
    MotivoPlanejamento = apps.get_model('rh', 'MotivoPlanejamento')
    MotivoPlanejamento.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_motivoplanejamento_planejamentohoraextra_motivos'),
    ]

    operations = [
        migrations.RunPython(seed_motivos, remove_motivos),
    ]
