# Generated by Django 5.0.14 on 2026-07-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_seed_motivos_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='posto_lideranca',
            field=models.CharField(choices=[('NAO_APLICA', 'Não se aplica'), ('LIDER', 'Líder'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente')], default='NAO_APLICA', max_length=20, verbose_name='Posto de Liderança'),
        ),
    ]
