# Generated by Django 5.0.14 on 2026-07-28 11:44

from django.db import migrations


def lowercase_usernames(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        if user.username != user.username.lower():
            user.username = user.username.lower()
            user.save(update_fields=['username'])

class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_colaborador_posto_lideranca'),
    ]

    operations = [
        migrations.RunPython(lowercase_usernames),
    ]
