# Generated by Django 5.0.14 on 2026-08-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_lowercase_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='VencimentoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_aquisitivo', models.DateField(verbose_name='Início do Período Aquisitivo')),
                ('data_fim_aquisitivo', models.DateField(verbose_name='Fim do Período Aquisitivo')),
                ('data_limite_gozo', models.DateField(verbose_name='Data Limite para Gozo (Vencimento)')),
                ('dias_direito', models.IntegerField(default=30, verbose_name='Dias de Direito')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimentos_ferias', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Vencimento de Férias',
                'verbose_name_plural': 'Vencimentos de Férias',
                'ordering': ['data_limite_gozo'],
            },
        ),
    ]
