# Generated by Django 5.0.14 on 2026-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_vencimentoferias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_abono_salarial', models.JSONField(default=list, help_text='Lista dos meses (1 a 12) onde Abono Salarial é permitido.', verbose_name='Meses permitidos para Abono Salarial')),
                ('meses_adiantamento_13', models.JSONField(default=list, help_text='Lista dos meses (1 a 12) onde Adiantamento de 13º é permitido.', verbose_name='Meses permitidos para Adiantamento de 13º')),
            ],
            options={
                'verbose_name': 'Configuração de Férias',
                'verbose_name_plural': 'Configurações de Férias',
            },
        ),
        migrations.AddField(
            model_name='ferias',
            name='abono_salarial',
            field=models.BooleanField(default=False, verbose_name='Abono Salarial (10 dias)'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='adiantamento_13',
            field=models.BooleanField(default=False, verbose_name='Adiantamento de 13º Salário'),
        ),
    ]
