# Generated by Django 5.0.14 on 2026-08-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_configuracaoferias_ferias_abono_salarial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaDiariaFalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data da Ocorrência')),
                ('jornada_prevista', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jornada Prevista (TxtPL.hrs.TrabDiário)')),
                ('e1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Entrada 1')),
                ('s1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Saída 1')),
                ('e2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Entrada 2')),
                ('s2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Saída 2')),
                ('e3', models.CharField(blank=True, max_length=10, null=True, verbose_name='Entrada 3')),
                ('s3', models.CharField(blank=True, max_length=10, null=True, verbose_name='Saída 3')),
                ('status_tratativa', models.CharField(choices=[('PENDENTE', 'Pendente de Tratativa'), ('EM_ANALISE', 'Em Análise pelo Gestor'), ('JUSTIFICADO', 'Justificado / Ajustado'), ('REJEITADO', 'Rejeitado / Invalidadas')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status da Tratativa')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa do Colaborador/Líder')),
                ('observacao_lider', models.TextField(blank=True, null=True, verbose_name='Observações do Líder')),
                ('tratado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas_ponto', to='rh.colaborador', verbose_name='Colaborador')),
                ('tratado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tratado Por')),
            ],
            options={
                'verbose_name': 'Jornada Diária com Falha',
                'verbose_name_plural': 'Jornadas Diárias com Falhas',
            },
        ),
        migrations.CreateModel(
            name='ItemFalhaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_erro', models.CharField(max_length=50, verbose_name='Código do Erro (Err)')),
                ('descricao_notificacao', models.TextField(verbose_name='Descrição da Notificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to='rh.jornadadiariafalha', verbose_name='Jornada Diária')),
            ],
            options={
                'verbose_name': 'Item de Falha de Ponto',
                'verbose_name_plural': 'Itens de Falha de Ponto',
            },
        ),
        migrations.CreateModel(
            name='MapeamentoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_planilha', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Matrícula na Planilha/Relatório')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos_matricula', to='rh.colaborador', verbose_name='Colaborador Global')),
            ],
            options={
                'verbose_name': 'Mapeamento de Matrícula (De-Para)',
                'verbose_name_plural': 'Mapeamentos de Matrículas',
            },
        ),
        migrations.AddIndex(
            model_name='jornadadiariafalha',
            index=models.Index(fields=['colaborador', 'data'], name='rh_jornadad_colabor_e5dcea_idx'),
        ),
        migrations.AddIndex(
            model_name='jornadadiariafalha',
            index=models.Index(fields=['status_tratativa', 'data'], name='rh_jornadad_status__89bfb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadadiariafalha',
            unique_together={('colaborador', 'data')},
        ),
    ]
