# Generated by Django 5.0.14 on 2026-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_jornadadiariafalha_itemfalhaponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='matricula_global',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Matrícula Global'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='posto_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto de Trabalho'),
        ),
    ]
