# Generated by Django 5.0.14 on 2026-08-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_colaborador_matricula_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadadiariafalha',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_como_lider', to='rh.colaborador', verbose_name='Líder (Planilha)'),
        ),
        migrations.AddField(
            model_name='jornadadiariafalha',
            name='matricula_lider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Líder (Planilha)'),
        ),
        migrations.AddField(
            model_name='jornadadiariafalha',
            name='nome_lider',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Líder (Planilha)'),
        ),
    ]
