# Generated by Django 5.0.14 on 2026-08-12 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_jornadadiariafalha_lider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaFalhaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Demanda')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo Importado')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora da Importação')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa / Em Tratativa'), ('ARQUIVADA', 'Arquivada')], db_index=True, default='ATIVA', max_length=20, verbose_name='Status da Demanda')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações / Anotações')),
            ],
            options={
                'verbose_name': 'Demanda de Falha de Ponto',
                'verbose_name_plural': 'Demandas de Falhas de Ponto',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.RemoveIndex(
            model_name='jornadadiariafalha',
            name='rh_jornadad_colabor_e5dcea_idx',
        ),
        migrations.AddField(
            model_name='demandafalhaponto',
            name='importado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importado Por'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadadiariafalha',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jornadadiariafalha',
            name='demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='rh.demandafalhaponto', verbose_name='Demanda de Origem'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadadiariafalha',
            unique_together={('demanda', 'colaborador', 'data')},
        ),
        migrations.AddIndex(
            model_name='jornadadiariafalha',
            index=models.Index(fields=['demanda', 'colaborador', 'data'], name='rh_jornadad_demanda_c6f72e_idx'),
        ),
    ]
