# Generated by Django 5.0.14 on 2026-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0030_demandafalhaponto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='posto_lideranca',
            field=models.CharField(choices=[('NAO_APLICA', 'Não se aplica'), ('LIDER', 'Líder'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('QUALIDADE', 'Qualidade'), ('PROCESSOS', 'Processos'), ('MANUTENCAO', 'Manutenção'), ('EHS', 'EHS')], default='NAO_APLICA', max_length=20, verbose_name='Posto de Liderança'),
        ),
    ]
