# Generated by Django 5.0.14 on 2026-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_colaborador_posto_lideranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_colaboradores/', verbose_name='Foto do Colaborador'),
        ),
    ]
