# Generated by Django 5.0.14 on 2026-10-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_colaborador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.TextField(blank=True, null=True, verbose_name='Foto do Colaborador (Base64)'),
        ),
    ]
