# Generated by Django 5.0.14 on 2026-03-02 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('objeto_auditoria', models.TextField(verbose_name='Objeto do Insumo')),
                ('link_sharepoint', models.URLField(blank=True, verbose_name='Link SharePoint')),
                ('periodicidade', models.CharField(choices=[('UNICA', 'Aplicação Única'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20)),
                ('dia_semana', models.CharField(blank=True, choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Para periodicidade semanal', max_length=10, null=True, verbose_name='Dia da Semana')),
                ('dias_quinzenal', models.CharField(blank=True, help_text='Dois dias do mês separados por vírgula (ex: 1,16)', max_length=10, null=True, verbose_name='Dias da Quinzena')),
                ('dia_mes', models.IntegerField(blank=True, help_text='Dia do mês para execução (1-31)', null=True, verbose_name='Dia do Mês')),
                ('preenchimento_grid', models.BooleanField(default=False, help_text='Habilita preenchimento em tabela para repetir as mesmas perguntas por múltiplos itens.', verbose_name='Preenchimento em GRID')),
                ('grid_rotulo_item', models.CharField(blank=True, default='Item', help_text='Ex.: Equipamento, Serviço, Item, Ativo.', max_length=60, verbose_name='Rótulo do item (GRID)')),
                ('grid_colunas', models.TextField(blank=True, default='', help_text='Uma coluna por linha. Se vazio, as colunas serão informadas no registro.', verbose_name='Colunas do GRID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsaveis', models.ManyToManyField(blank=True, help_text='Usuários autorizados a preencher/atualizar acompanhamentos deste modelo.', related_name='modelos_insumos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Usuário responsável pela realização do acompanhamento de insumos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_insumos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Modelo de Insumos',
                'verbose_name_plural': 'Modelos de Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('tipo_resposta', models.CharField(choices=[('SIM_NAO', 'Sim/Não'), ('LISTA', 'Lista (opções)'), ('NUMERO', 'Número inteiro'), ('DECIMAL', 'Número decimal')], default='SIM_NAO', max_length=20)),
                ('preenchimento_semanal', models.CharField(choices=[('UNICO', 'Uma resposta (sem detalhar por dia)'), ('POR_DIA', 'Responder para cada dia da semana')], default='UNICO', help_text='Apenas para modelos com periodicidade semanal.', max_length=10, verbose_name='Preenchimento (semanal)')),
                ('opcoes_resposta', models.TextField(blank=True, default='', help_text="Apenas para tipo 'Lista (opções)'. Use uma opção por linha.", verbose_name='Opções de resposta')),
                ('aplicar_no_grid', models.BooleanField(default=True, help_text='Se marcado, esta pergunta aparece no preenchimento em GRID (quando habilitado no modelo).', verbose_name='Aplicar no GRID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='insumos.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Pergunta de Insumos',
                'verbose_name_plural': 'Perguntas de Insumos',
                'ordering': ['modelo__nome', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_auditoria', models.DateField(verbose_name='Data')),
                ('periodo_inicio', models.DateField(verbose_name='Período Inicial')),
                ('periodo_fim', models.DateField(verbose_name='Período Final')),
                ('item_os', models.CharField(blank=True, default='', help_text='Preencher se necessário para identificar ordens de serviço ou pontos específicos.', max_length=120, verbose_name='ITEM/O.S.')),
                ('grid_itens', models.TextField(blank=True, default='', help_text='Use uma linha por item quando o modelo estiver em modo GRID.', verbose_name='Itens (GRID)')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_realizados', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='insumos.modeloauditoria', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Registro de Insumos',
                'verbose_name_plural': 'Registros de Insumos',
                'ordering': ['-data_auditoria', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(blank=True, choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], help_text='Usado quando a pergunta exige resposta por dia (semanal).', max_length=10, null=True, verbose_name='Dia da Semana')),
                ('grid_item', models.CharField(blank=True, default='', help_text='Identifica o item quando o preenchimento é em GRID.', max_length=120, verbose_name='Item (GRID)')),
                ('valor', models.TextField(blank=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='insumos.perguntaauditoria')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='insumos.registroauditoria')),
            ],
            options={
                'verbose_name': 'Resposta de Insumos',
                'verbose_name_plural': 'Respostas de Insumos',
                'ordering': ['registro', 'pergunta__ordem', 'dia_semana', 'id'],
                'unique_together': {('registro', 'pergunta', 'dia_semana', 'grid_item')},
            },
        ),
    ]
