# Generated by Django 5.0.14 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insumos", "0002_comentarioinsumos"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeloauditoria",
            name="subcategorias",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Uma sub-categoria por linha (ex.: Segurança, Qualidade, 5S).",
                verbose_name="Sub-categorias",
            ),
        ),
    ]
