# Generated by Django 5.0.14 on 2026-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_pergunta_descricao_detalhada_comentario_resposta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentariorespostainsumos',
            unique_together=set(),
        ),
    ]
