# Generated by Django 5.0.14 on 2026-05-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insumos", "0005_alter_comentariorespostainsumos_unique_together"),
        ("maquinas", "0004_alter_maquina_options_maquina_fabricante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descricao"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria de Insumo",
                "verbose_name_plural": "Categorias de Insumos",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="modeloauditoria",
            name="maquinas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Maquinas que utilizam ou consomem este insumo.",
                related_name="modelos_insumos",
                to="maquinas.maquina",
                verbose_name="Maquinas associadas",
            ),
        ),
        migrations.AddField(
            model_name="modeloauditoria",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modelos",
                to="insumos.categoriainsumo",
                verbose_name="Categoria do insumo",
            ),
        ),
    ]
