# Generated by Django 5.0.14 on 2025-12-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=255)),
                ("nome_fantasia", models.CharField(max_length=255)),
                ("endereco", models.CharField(max_length=255)),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("siret", models.CharField(blank=True, max_length=20, null=True)),
                ("ein", models.CharField(blank=True, max_length=20, null=True)),
                ("telefone", models.CharField(blank=True, max_length=30, null=True)),
                ("uf", models.CharField(max_length=2)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CRITICO", "Crítico"),
                            ("NAO_CRITICO", "Não Crítico"),
                            ("TERCEIRIZADO", "Terceirizado"),
                        ],
                        default="NAO_CRITICO",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PerguntaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SELECAO", "Seleção"),
                            ("REAVALIACAO", "Reavaliação"),
                            ("MONITORAMENTO", "Monitoramento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos_fornecedores/")),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fornecedores.categoriadocumento",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvaliacaoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SELECAO", "Seleção"),
                            ("REAVALIACAO", "Reavaliação"),
                            ("MONITORAMENTO", "Monitoramento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nota_fiscal", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tipo_nota",
                    models.CharField(
                        blank=True,
                        choices=[("PRODUTO", "Produto"), ("SERVICO", "Serviço")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pontuacao_ano", models.FloatField(default=100)),
                ("resultado", models.CharField(blank=True, max_length=20)),
                ("observacao", models.TextField(blank=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OcorrenciaNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("pontuacao_perdida", models.FloatField(default=0.5)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="fornecedores.avaliacaofornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta", models.BooleanField()),
                ("observacao", models.TextField(blank=True)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="fornecedores.avaliacaofornecedor",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fornecedores.perguntaavaliacao",
                    ),
                ),
            ],
        ),
    ]
