# Generated by Django for produto_servico field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaavaliacao',
            name='produto_servico',
            field=models.CharField(
                max_length=10,
                choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço'), ('AMBOS', 'Ambos')],
                blank=True,
                null=True,
                help_text='Obrigatório para perguntas de Monitoramento',
            ),
        ),
    ]
