# Generated by Django 5.0.14 on 2025-12-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0002_perguntaavaliacao_produto_servico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaofornecedor",
            name="data",
            field=models.DateField(),
        ),
    ]
