# Generated by Django 5.0.14 on 2025-12-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0003_alter_avaliacaofornecedor_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="autorizacao_funcionamento",
            field=models.BooleanField(
                default=False, verbose_name="Autorização de funcionamento"
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="certificado_iso",
            field=models.BooleanField(
                default=False,
                verbose_name="Certificado ISO 9001, ISO 13485 ou ISO 17025",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="licenca_funcionamento",
            field=models.BooleanField(
                default=False, verbose_name="Licença de funcionamento"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaofornecedor",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SELECAO", "Avaliação"),
                    ("REAVALIACAO", "Reavaliação"),
                    ("MONITORAMENTO", "Monitoramento"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="perguntaavaliacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SELECAO", "Avaliação"),
                    ("REAVALIACAO", "Reavaliação"),
                    ("MONITORAMENTO", "Monitoramento"),
                ],
                max_length=20,
            ),
        ),
    ]
