# Generated by Django 5.0.14 on 2025-12-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0004_fornecedor_autorizacao_funcionamento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaMatrizAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PRODUTO", "Produto"), ("SERVICO", "Serviço")],
                        max_length=10,
                    ),
                ),
                (
                    "requisito",
                    models.CharField(
                        choices=[
                            ("A", "A - Certificado ISO 9001, ISO 13485 ou ISO 17025"),
                            (
                                "B",
                                "B - Outros (AFE - Autorização de Funcionamento ou Licença)",
                            ),
                            (
                                "C",
                                "C - Documentos legais (Contrato Social, CNPJ, Inscrição Estadual/Municipal)",
                            ),
                            ("D", "D - Referência de mercado"),
                        ],
                        max_length=1,
                    ),
                ),
                ("respondido", models.BooleanField(default=False)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_matriz",
                        to="fornecedores.avaliacaofornecedor",
                    ),
                ),
            ],
            options={
                "unique_together": {("avaliacao", "tipo", "requisito")},
            },
        ),
    ]
