# Generated by Django 5.0.14 on 2025-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0005_respostamatrizavaliacao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="respostamatrizavaliacao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="respostamatrizavaliacao",
            name="nome_item",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="respostamatrizavaliacao",
            unique_together={("avaliacao", "tipo", "nome_item", "requisito")},
        ),
    ]
