# Generated by Django 5.0.14 on 2026-02-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('corretiva', 'Ação Corretiva'), ('preventiva', 'Ação Preventiva')], default='corretiva', max_length=20, verbose_name='Tipo de Ação')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('origem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem (Ex: Auditoria, Não Conformidade, etc.)')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='Meta/Objetivo')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado Obtido')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_criadas', to='rh.colaborador', verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsavel', to='rh.colaborador', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ação Corretiva/Preventiva',
                'verbose_name_plural': 'Ações Corretivas/Preventivas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AcaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Autor')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='acoes.acaocorretiva', verbose_name='Ação')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='acaocorretiva',
            index=models.Index(fields=['-data_criacao'], name='acoes_acaoc_data_cr_7a5701_idx'),
        ),
        migrations.AddIndex(
            model_name='acaocorretiva',
            index=models.Index(fields=['status'], name='acoes_acaoc_status_ea7dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='acaocorretiva',
            index=models.Index(fields=['responsavel'], name='acoes_acaoc_respons_241369_idx'),
        ),
        migrations.AddIndex(
            model_name='acaocorretiva',
            index=models.Index(fields=['prioridade'], name='acoes_acaoc_priorid_ee30db_idx'),
        ),
    ]
