# Generated by Django 5.0.14 on 2026-02-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaocorretiva',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Ação Corretiva/Preventiva', 'verbose_name_plural': 'Ações Corretivas/Preventivas'},
        ),
        migrations.RemoveIndex(
            model_name='acaocorretiva',
            name='acoes_acaoc_data_cr_7a5701_idx',
        ),
        migrations.RemoveField(
            model_name='acaocorretiva',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='causa_raiz',
            field=models.TextField(blank=True, null=True, verbose_name='Causa Raiz'),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='link_registro',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Registro'),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº do Registro'),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='tipo_solucao',
            field=models.CharField(blank=True, choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('melhoria', 'Melhoria')], max_length=20, null=True, verbose_name='Tipo de Solução'),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='acaocorretiva',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='acaocorretiva',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Fechamento Programada'),
        ),
        migrations.AlterField(
            model_name='acaocorretiva',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da NC e/ou Melhoria'),
        ),
        migrations.AlterField(
            model_name='acaocorretiva',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='acaocorretiva',
            name='origem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem do Problema'),
        ),
        migrations.AddIndex(
            model_name='acaocorretiva',
            index=models.Index(fields=['-data_abertura'], name='acoes_acaoc_data_ab_9c722d_idx'),
        ),
        migrations.AddIndex(
            model_name='acaocorretiva',
            index=models.Index(fields=['numero_registro'], name='acoes_acaoc_numero__649c87_idx'),
        ),
    ]
