# Generated by Django 5.0.14 on 2026-02-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_alter_acaocorretiva_options_and_more'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plano_acao', 'Plano de Ação'), ('a3', 'A3'), ('8d', '8D'), ('rnc', 'RNC'), ('gestao_mudanca', 'Gestão de Mudança'), ('revisao_gerencial', 'Revisão Gerencial')], max_length=20, verbose_name='Tipo de Solução')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Solução')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('analise', 'Análise'), ('implementacao', 'Implementação'), ('validacao', 'Validação'), ('encerrada', 'Encerrada')], default='planejamento', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('acao_corretiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucoes', to='acoes.acaocorretiva', verbose_name='Ação Corretiva')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solucoes_responsavel', to='rh.colaborador', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Solução',
                'verbose_name_plural': 'Soluções',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RevisaoGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao_descricao', models.TextField(verbose_name='Descrição da Revisão')),
                ('escopo', models.TextField(verbose_name='Escopo da Revisão')),
                ('achados_principais', models.TextField(verbose_name='Achados Principais')),
                ('oportunidades_melhoria', models.TextField(verbose_name='Oportunidades de Melhoria')),
                ('recomendacoes', models.TextField(verbose_name='Recomendações')),
                ('prioridade_implementacao', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=20, verbose_name='Prioridade de Implementação')),
                ('plano_acao', models.TextField(verbose_name='Plano de Ação')),
                ('data_alvo_implementacao', models.DateField(verbose_name='Data Alvo de Implementação')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('responsavel_implementacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_gerenciais', to='rh.colaborador', verbose_name='Responsável pela Implementação')),
                ('solucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisao_gerencial', to='acoes.solucao', verbose_name='Solução')),
            ],
            options={
                'verbose_name': 'Revisão Gerencial',
                'verbose_name_plural': 'Revisões Gerenciais',
            },
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_proposta', models.TextField(verbose_name='Ação Proposta')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_execucao', 'Em Execução'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20, verbose_name='Status')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('responsavel_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_acao', to='rh.colaborador', verbose_name='Responsável pela Ação')),
                ('solucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_acao', to='acoes.solucao', verbose_name='Solução')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
            },
        ),
        migrations.CreateModel(
            name='Solucao8D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1_time', models.TextField(verbose_name='D1 - Time Responsável')),
                ('d2_descricao', models.TextField(verbose_name='D2 - Descrição do Problema')),
                ('d2_especificacoes', models.TextField(verbose_name='D2 - Especificações Afetadas')),
                ('d3_contencao', models.TextField(blank=True, null=True, verbose_name='D3 - Plano de Contenção')),
                ('d4_causas', models.TextField(blank=True, null=True, verbose_name='D4 - Análise de Causas')),
                ('d4_causa_raiz', models.TextField(blank=True, null=True, verbose_name='D4 - Causa Raiz')),
                ('d5_contramedidas', models.TextField(blank=True, null=True, verbose_name='D5 - Contramedidas Propostas')),
                ('d6_implementacao', models.TextField(blank=True, null=True, verbose_name='D6 - Plano de Implementação')),
                ('d7_verificacao', models.TextField(blank=True, null=True, verbose_name='D7 - Verificação de Efetividade')),
                ('d7_resultado', models.TextField(blank=True, null=True, verbose_name='D7 - Resultado')),
                ('d8_padronizacao', models.TextField(blank=True, null=True, verbose_name='D8 - Padronização')),
                ('d8_encerramento', models.TextField(blank=True, null=True, verbose_name='D8 - Encerramento')),
                ('solucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oito_d', to='acoes.solucao', verbose_name='Solução')),
            ],
            options={
                'verbose_name': 'Solução 8D',
                'verbose_name_plural': 'Soluções 8D',
            },
        ),
        migrations.CreateModel(
            name='SolucaoA3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('problema_impacto', models.TextField(verbose_name='Impacto do Problema')),
                ('situacao_atual', models.TextField(verbose_name='Situação Atual')),
                ('analise_causas', models.TextField(verbose_name='Análise de Causas')),
                ('causa_raiz', models.TextField(verbose_name='Causa Raiz Identificada')),
                ('contramedidas', models.TextField(verbose_name='Contramedidas Propostas')),
                ('resultados_esperados', models.TextField(verbose_name='Resultados Esperados')),
                ('plano_verificacao', models.TextField(blank=True, null=True, verbose_name='Plano de Verificação')),
                ('resultado_verificacao', models.TextField(blank=True, null=True, verbose_name='Resultado da Verificação')),
                ('solucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a3', to='acoes.solucao', verbose_name='Solução')),
            ],
            options={
                'verbose_name': 'Solução A3',
                'verbose_name_plural': 'Soluções A3',
            },
        ),
        migrations.CreateModel(
            name='SolucaoGestaoDeMudanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudanca_descricao', models.TextField(verbose_name='Descrição da Mudança')),
                ('motivacao', models.TextField(verbose_name='Motivação/Justificativa')),
                ('impacto_processos', models.TextField(verbose_name='Impacto em Processos')),
                ('impacto_sistemas', models.TextField(blank=True, null=True, verbose_name='Impacto em Sistemas')),
                ('impacto_pessoas', models.TextField(blank=True, null=True, verbose_name='Impacto em Pessoas')),
                ('plano_implementacao', models.TextField(verbose_name='Plano de Implementação')),
                ('data_implementacao', models.DateField(verbose_name='Data de Implementação')),
                ('status', models.CharField(choices=[('proposta', 'Proposta'), ('analise', 'Análise'), ('aprovada', 'Aprovada'), ('implementada', 'Implementada'), ('rejeitada', 'Rejeitada')], default='proposta', max_length=20, verbose_name='Status')),
                ('plano_validacao', models.TextField(blank=True, null=True, verbose_name='Plano de Validação')),
                ('resultado_validacao', models.TextField(blank=True, null=True, verbose_name='Resultado da Validação')),
                ('solucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestao_mudanca', to='acoes.solucao', verbose_name='Solução')),
            ],
            options={
                'verbose_name': 'Gestão de Mudança',
                'verbose_name_plural': 'Gestões de Mudança',
            },
        ),
        migrations.CreateModel(
            name='SolucaoRNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_descricao', models.TextField(verbose_name='Descrição da Não Conformidade')),
                ('nc_tipo', models.CharField(choices=[('maior', 'Maior'), ('menor', 'Menor')], max_length=50, verbose_name='Tipo de NC')),
                ('analise_causas', models.TextField(verbose_name='Análise de Causas')),
                ('causa_raiz', models.TextField(verbose_name='Causa Raiz')),
                ('acao_imediata', models.TextField(verbose_name='Ação Imediata')),
                ('acao_corretiva', models.TextField(verbose_name='Ação Corretiva')),
                ('acao_preventiva', models.TextField(blank=True, null=True, verbose_name='Ação Preventiva')),
                ('plano_verificacao', models.TextField(verbose_name='Plano de Verificação')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('solucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rnc', to='acoes.solucao', verbose_name='Solução')),
            ],
            options={
                'verbose_name': 'Solução RNC',
                'verbose_name_plural': 'Soluções RNC',
            },
        ),
    ]
