# Generated by Django 5.0.14 on 2026-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_solucao_revisaogerencial_planoacao_solucao8d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plano_acao', 'Plano de Ação'), ('a3', 'A3'), ('8d', '8D'), ('rnc', 'RNC'), ('gestao_mudanca', 'Gestão de Mudança'), ('revisao_gerencial', 'Revisão Gerencial')], max_length=20, unique=True, verbose_name='Tipo de Solução')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('arquivo_pdf', models.FileField(upload_to='templates_solucoes/', verbose_name='Arquivo PDF')),
                ('data_upload', models.DateTimeField(auto_now=True, verbose_name='Data de Upload')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Template de Solução',
                'verbose_name_plural': 'Templates de Soluções',
            },
        ),
    ]
