# Generated by Django 5.0.14 on 2026-02-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_templatesolucao'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoacao',
            options={'ordering': ['numero_acao'], 'verbose_name': 'Plano de Ação', 'verbose_name_plural': 'Planos de Ação'},
        ),
        migrations.AlterModelOptions(
            name='solucao8d',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Solução 8D', 'verbose_name_plural': 'Soluções 8D'},
        ),
        migrations.AlterModelOptions(
            name='solucaogestaodemudanca',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Gestão de Mudança', 'verbose_name_plural': 'Gestões de Mudança'},
        ),
        migrations.AlterModelOptions(
            name='solucaornc',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Registro de Não Conformidade', 'verbose_name_plural': 'Registros de Não Conformidade'},
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='acao_proposta',
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='solucao8d',
            name='d1_time',
        ),
        migrations.RemoveField(
            model_name='solucao8d',
            name='d4_causas',
        ),
        migrations.RemoveField(
            model_name='solucaogestaodemudanca',
            name='data_implementacao',
        ),
        migrations.RemoveField(
            model_name='solucaogestaodemudanca',
            name='impacto_processos',
        ),
        migrations.RemoveField(
            model_name='solucaogestaodemudanca',
            name='impacto_sistemas',
        ),
        migrations.RemoveField(
            model_name='solucaogestaodemudanca',
            name='motivacao',
        ),
        migrations.RemoveField(
            model_name='solucaogestaodemudanca',
            name='mudanca_descricao',
        ),
        migrations.RemoveField(
            model_name='solucaogestaodemudanca',
            name='plano_implementacao',
        ),
        migrations.RemoveField(
            model_name='solucaornc',
            name='nc_descricao',
        ),
        migrations.RemoveField(
            model_name='solucaornc',
            name='nc_tipo',
        ),
        migrations.AddField(
            model_name='planoacao',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('melhoria', 'Melhoria')], max_length=20, null=True, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='data_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline Final'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='data_primeira_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='1º Deadline'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição / Descripción'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='input_origem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Input/Origem'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='kpi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KPI'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='laboratorio_area_projeto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Laboratório, Área ou Projeto'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='numero_acao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Ação'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Registro'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='prioridade',
            field=models.BooleanField(default=False, verbose_name='Prioridade (Y/N)'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='problema',
            field=models.TextField(blank=True, null=True, verbose_name='Problema'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='analise_causas',
            field=models.TextField(blank=True, null=True, verbose_name='Análise de Causas'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='causa_raiz',
            field=models.TextField(blank=True, null=True, verbose_name='Causa Raiz'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d3_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='D3 - Deadline'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d3_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d8_d3_responsavel', to='rh.colaborador', verbose_name='D3 - Responsável'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d4_analise_causas',
            field=models.TextField(blank=True, null=True, verbose_name='D4 - Análise de Causas'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d4_ferramentas_qualidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='D4 - Ferramentas de Qualidade Utilizadas'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d5_criterios_selecao',
            field=models.TextField(blank=True, null=True, verbose_name='D5 - Critérios de Seleção'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d6_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='D6 - Deadline de Implementação'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d6_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d8_d6_responsavel', to='rh.colaborador', verbose_name='D6 - Responsável'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d6_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='D6 - Status de Implementação'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d7_efetivo',
            field=models.BooleanField(blank=True, null=True, verbose_name='D7 - Resultado Efetivo?'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d8_documentos_atualizados',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='D8 - Documentos Atualizados'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='d8_treinamento',
            field=models.TextField(blank=True, null=True, verbose_name='D8 - Plano de Treinamento'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='equipe',
            field=models.TextField(blank=True, null=True, verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='lider_8d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d8_lider', to='rh.colaborador', verbose_name='Líder 8D'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='numero_formulario',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Formulário'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='patrocinador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Patrocinador'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='prazo_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo Projeto 8D'),
        ),
        migrations.AddField(
            model_name='solucao8d',
            name='problema_identificado',
            field=models.TextField(blank=True, null=True, verbose_name='Problema Identificado'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='area_avaliadora',
            field=models.TextField(blank=True, null=True, verbose_name='Área Avaliadora (setores/departamentos)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='area_impactada',
            field=models.TextField(blank=True, null=True, verbose_name='Área(s) Impactada(s)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='areas_implantacao',
            field=models.TextField(blank=True, null=True, verbose_name='Áreas envolvidas na implantação'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='beneficios',
            field=models.TextField(blank=True, null=True, verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='como_afeta_processo',
            field=models.TextField(blank=True, null=True, verbose_name='Como a mudança afeta o processo atual'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='consequencia_nao_mudanca',
            field=models.TextField(blank=True, null=True, verbose_name='Consequência de não realizar a mudança'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Abertura'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='data_area1',
            field=models.DateField(blank=True, null=True, verbose_name='Data (Área 1)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='data_area2',
            field=models.DateField(blank=True, null=True, verbose_name='Data (Área 2)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='data_informada',
            field=models.DateField(blank=True, null=True, verbose_name='Data Informada'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='data_mudanca',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Mudança/Projeto'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='evidencia',
            field=models.TextField(blank=True, null=True, verbose_name='Evidência (imagens e/ou informações antes da mudança)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='gerar_plano_acao',
            field=models.BooleanField(default=False, verbose_name='Gerar Plano de Ação'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='impacto_ambiente',
            field=models.TextField(blank=True, null=True, verbose_name='Impacto - Meio Ambiente (Emissões, Resíduos, Energia)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='impacto_ativos',
            field=models.TextField(blank=True, null=True, verbose_name='Impacto - Propriedades e Ativos (Instalações, Equipamentos)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='impacto_compliance',
            field=models.TextField(blank=True, null=True, verbose_name='Impacto - Compliance (Regulamentos)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='justificativa_area1',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa/Parecer (Área 1)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='justificativa_area2',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa/Parecer (Área 2)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='modulos_sistema_afetados',
            field=models.TextField(blank=True, null=True, verbose_name='Quais módulos do sistema serão afetados'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº do Registro'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='percentual_conclusao_plano',
            field=models.FloatField(default=0, verbose_name='Percentual de Conclusão do Plano'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='plano_acao_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestoes_mudanca_relacionadas', to='acoes.planoacao', verbose_name='Plano de Ação Relacionado'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='plano_contingencia',
            field=models.TextField(blank=True, null=True, verbose_name='Plano de Contingência em caso de riscos'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='prioridade_mudanca',
            field=models.CharField(blank=True, choices=[('urgente', 'Urgente'), ('alto', 'Alto'), ('medio', 'Médio')], max_length=20, null=True, verbose_name='Prioridade da Mudança'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='processos_afetados',
            field=models.TextField(blank=True, null=True, verbose_name='Quais processos serão afetados pela mudança'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='referencia_ambiente',
            field=models.CharField(blank=True, choices=[('nao_aplica', 'Não Aplica'), ('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, null=True, verbose_name='Referência Necessária - Ambiente'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='referencia_ativos',
            field=models.CharField(blank=True, choices=[('nao_aplica', 'Não Aplica'), ('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, null=True, verbose_name='Referência Necessária - Ativos'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='referencia_compliance',
            field=models.CharField(blank=True, choices=[('nao_aplica', 'Não Aplica'), ('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, null=True, verbose_name='Referência Necessária - Compliance'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='referencia_pessoas',
            field=models.CharField(blank=True, choices=[('nao_aplica', 'Não Aplica'), ('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, null=True, verbose_name='Referência Necessária - Pessoas'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='responsavel_decisao_area1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pela Decisão (Área 1)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='responsavel_decisao_area2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pela Decisão (Área 2)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='riscos_identificados',
            field=models.TextField(blank=True, null=True, verbose_name='Riscos Identificados'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='sera_implantada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mudança será implantada'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='situacao_antes',
            field=models.TextField(blank=True, null=True, verbose_name='Situação (Antes da Mudança)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='situacao_depois',
            field=models.TextField(blank=True, null=True, verbose_name='Situação Projetada (Após Mudança)'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='solicitante_informado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Solicitante Informado'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='tipo_mudanca',
            field=models.CharField(blank=True, choices=[('regulatorio', 'Regulatório'), ('qms_sgi', 'QMS/SGI'), ('projetos', 'Projetos')], max_length=20, null=True, verbose_name='Tipo de Mudança'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='tratamento_riscos',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamento dos Riscos'),
        ),
        migrations.AddField(
            model_name='solucaogestaodemudanca',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='acao_contencao',
            field=models.TextField(blank=True, null=True, verbose_name='Ação de Contenção'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='acao_nc',
            field=models.CharField(blank=True, choices=[('aprovar_concessao', 'Aprovar sob Concessão'), ('rejeitar', 'Rejeitar'), ('corrigir', 'Corrigir')], max_length=30, null=True, verbose_name='Ação sobre Não Conformidade'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='classificacao',
            field=models.CharField(choices=[('critica', 'Crítica'), ('maior', 'Maior'), ('menor', 'Menor'), ('oportunidade_melhoria', 'Oportunidade de Melhoria')], default='maior', max_length=30, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Abertura'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Fechamento'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='descricao_nc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Não Conformidade'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='eficacia',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz')], max_length=20, null=True, verbose_name='Análise Crítica da Eficácia'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='evidencia_implementacao',
            field=models.TextField(blank=True, null=True, verbose_name='Evidência da Implementação'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='evidencia_nc',
            field=models.TextField(blank=True, null=True, verbose_name='Evidência da Não Conformidade'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('rara', 'Rara'), ('ocasional', 'Ocasional'), ('frequente', 'Frequente')], max_length=20, null=True, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='gerar_plano_acao',
            field=models.BooleanField(default=False, verbose_name='Gerar Plano de Ação'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='numero_rnc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº da RNC'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='origem',
            field=models.CharField(blank=True, choices=[('insumo', 'Insumo'), ('produto', 'Produto'), ('indicador', 'Indicador'), ('auditoria', 'Auditoria'), ('equipamento_medicao', 'Equipamento de Medição'), ('processo', 'Processo'), ('fornecedor', 'Fornecedor'), ('testes_qualidade', 'Testes de Qualidade'), ('outros', 'Outros')], max_length=30, null=True, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='plano_acao_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rncs_relacionadas', to='acoes.planoacao', verbose_name='Plano de Ação Relacionado'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='requerimento_requisito',
            field=models.TextField(blank=True, null=True, verbose_name='Requerimento/Requisito'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rncs_responsavel', to='rh.colaborador', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='risco',
            field=models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=20, null=True, verbose_name='Nível de Risco'),
        ),
        migrations.AddField(
            model_name='solucaornc',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='responsavel_acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_acao', to='rh.colaborador', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado Obtido'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='status',
            field=models.CharField(choices=[('planejada', 'Planejada'), ('em_curso', 'Em Curso/Andamento'), ('completa', 'Completa/Concluído'), ('retardo', 'Retardo/Atrasada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='solucao8d',
            name='d2_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='D2 - Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='solucao8d',
            name='d2_especificacoes',
            field=models.TextField(blank=True, null=True, verbose_name='D2 - Especificações Afetadas'),
        ),
        migrations.AlterField(
            model_name='solucao8d',
            name='d7_resultado',
            field=models.TextField(blank=True, null=True, verbose_name='D7 - Resultado da Verificação'),
        ),
        migrations.AlterField(
            model_name='solucao8d',
            name='d7_verificacao',
            field=models.TextField(blank=True, null=True, verbose_name='D7 - Plano de Verificação'),
        ),
        migrations.AlterField(
            model_name='solucaogestaodemudanca',
            name='impacto_pessoas',
            field=models.TextField(blank=True, null=True, verbose_name='Impacto - Pessoas (Saúde, Segurança Química/Elétrica, Ergonomia)'),
        ),
        migrations.AlterField(
            model_name='solucaornc',
            name='acao_corretiva',
            field=models.TextField(blank=True, null=True, verbose_name='Ação Corretiva'),
        ),
        migrations.AlterField(
            model_name='solucaornc',
            name='acao_imediata',
            field=models.TextField(blank=True, null=True, verbose_name='Ação Imediata'),
        ),
        migrations.AlterField(
            model_name='solucaornc',
            name='analise_causas',
            field=models.TextField(blank=True, null=True, verbose_name='Análise de Causas'),
        ),
        migrations.AlterField(
            model_name='solucaornc',
            name='causa_raiz',
            field=models.TextField(blank=True, null=True, verbose_name='Causa Raiz'),
        ),
        migrations.AlterField(
            model_name='solucaornc',
            name='plano_verificacao',
            field=models.TextField(blank=True, null=True, verbose_name='Plano de Verificação'),
        ),
        migrations.AddIndex(
            model_name='planoacao',
            index=models.Index(fields=['numero_acao'], name='acoes_plano_numero__fae9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='planoacao',
            index=models.Index(fields=['status'], name='acoes_plano_status_6a9d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='planoacao',
            index=models.Index(fields=['prioridade'], name='acoes_plano_priorid_1ca812_idx'),
        ),
        migrations.AddIndex(
            model_name='solucao8d',
            index=models.Index(fields=['numero_formulario'], name='acoes_soluc_numero__87663a_idx'),
        ),
        migrations.AddIndex(
            model_name='solucao8d',
            index=models.Index(fields=['lider_8d'], name='acoes_soluc_lider_8_37d3af_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaogestaodemudanca',
            index=models.Index(fields=['numero_registro'], name='acoes_soluc_numero__bf2d58_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaogestaodemudanca',
            index=models.Index(fields=['status'], name='acoes_soluc_status_2ce10a_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaogestaodemudanca',
            index=models.Index(fields=['prioridade_mudanca'], name='acoes_soluc_priorid_b4f3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaornc',
            index=models.Index(fields=['numero_rnc'], name='acoes_soluc_numero__f0662b_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaornc',
            index=models.Index(fields=['classificacao'], name='acoes_soluc_classif_eb5e29_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaornc',
            index=models.Index(fields=['risco'], name='acoes_soluc_risco_23a237_idx'),
        ),
    ]
