# Generated by Django 5.0.14 on 2026-02-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0005_alter_planoacao_options_alter_solucao8d_options_and_more'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisaogerencial',
            options={'ordering': ['-data_realizacao'], 'verbose_name': 'Revisão Gerencial', 'verbose_name_plural': 'Revisões Gerenciais'},
        ),
        migrations.AlterModelOptions(
            name='solucaoa3',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Solução A3', 'verbose_name_plural': 'Soluções A3'},
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='achados_principais',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='data_alvo_implementacao',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='escopo',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='oportunidades_melhoria',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='plano_acao',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='prioridade_implementacao',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='recomendacoes',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='responsavel_implementacao',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='revisaogerencial',
            name='revisao_descricao',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='contramedidas',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='plano_verificacao',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='problema_descricao',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='problema_impacto',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='resultado_verificacao',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='resultados_esperados',
        ),
        migrations.RemoveField(
            model_name='solucaoa3',
            name='situacao_atual',
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='analises_criticas',
            field=models.TextField(blank=True, null=True, verbose_name='Análises Críticas Realizadas'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='data_realizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da realização desta reunião'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_acompanhamento',
            field=models.TextField(blank=True, null=True, verbose_name='1. Ações de acompanhamento de análises críticas anteriores'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_auditorias',
            field=models.TextField(blank=True, null=True, verbose_name='2. Resultados de auditorias'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_desempenho',
            field=models.TextField(blank=True, null=True, verbose_name='Desempenho de processos e conformidade'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_fornecedores',
            field=models.TextField(blank=True, null=True, verbose_name='Desempenho de fornecedores'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_mudancas',
            field=models.TextField(blank=True, null=True, verbose_name='Alterações e mudanças'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_oportunidades',
            field=models.TextField(blank=True, null=True, verbose_name='Oportunidades de melhoria'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_pessoal',
            field=models.TextField(blank=True, null=True, verbose_name='Adequação de recursos (pessoal)'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_risco',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação de risco'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='entradas_satisfacao',
            field=models.TextField(blank=True, null=True, verbose_name='3. Satisfação de clientes'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Laboratório'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='numero_rg',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Registro'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='participantes',
            field=models.TextField(blank=True, null=True, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='percentual_conclusao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Percentual de Conclusão'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='periodo_fim',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Período desta Revisão Gerencial (Fim)'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='periodo_inicio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Período desta Revisão Gerencial (Início)'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='plano_acao_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_gerenciais', to='acoes.planoacao', verbose_name='Plano de Ação Relacionado'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='representante_direcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Representante da Direção'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='responsavel_unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pela Unidade'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='saidas_eficacia_sgq',
            field=models.TextField(blank=True, null=True, verbose_name='1. Melhoria da eficácia do SGQ e de seus processos'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='saidas_melhoria_produto',
            field=models.TextField(blank=True, null=True, verbose_name='2. Melhoria do produto em relação aos requisitos'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='saidas_necessidade_recurso',
            field=models.TextField(blank=True, null=True, verbose_name='4. Necessidade de recursos'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='saidas_necessidades_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='3. Atendimento de necessidades de partes interessadas'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='status',
            field=models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='total_acoes_andamento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações em Andamento'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='total_acoes_completas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações Completas'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='total_acoes_planejadas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações Planejadas'),
        ),
        migrations.AddField(
            model_name='revisaogerencial',
            name='total_acoes_prioridade_andamento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações Prioridade em Andamento'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='a3_numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='A3 Nº'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='estado_atual',
            field=models.TextField(blank=True, null=True, verbose_name='M. MEDIR (Estado Atual / Anterior)'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_5_porques',
            field=models.BooleanField(default=False, verbose_name='5 Porquês'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_antes_depois',
            field=models.BooleanField(default=False, verbose_name='Antes x Depois'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_brainstorming',
            field=models.BooleanField(default=False, verbose_name='Brainstorming'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_carta_tendencia',
            field=models.BooleanField(default=False, verbose_name='Carta de Tendência'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_checklist',
            field=models.BooleanField(default=False, verbose_name='Check List'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_fluxograma',
            field=models.BooleanField(default=False, verbose_name='Fluxograma'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_grafico_geral',
            field=models.BooleanField(default=False, verbose_name='Gráfico Geral'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_grafico_pareto',
            field=models.BooleanField(default=False, verbose_name='Gráfico de Pareto'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='ferramenta_ishikawa',
            field=models.BooleanField(default=False, verbose_name='Diagrama de Ishikawa'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='historico_importancia',
            field=models.TextField(blank=True, null=True, verbose_name='HISTÓRICO / IMPORTÂNCIA'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Laboratório'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='lider_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3_lider', to='rh.colaborador', verbose_name='Líder do Projeto'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo (D.DEFINIR)'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='observacoes_importantes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Importantes'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='participantes',
            field=models.TextField(blank=True, null=True, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='plano_acao_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3s_relacionados', to='acoes.planoacao', verbose_name='Plano de Ação (Implementação)'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='problema',
            field=models.TextField(blank=True, null=True, verbose_name='Problema'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='resultados',
            field=models.TextField(blank=True, null=True, verbose_name='C. CONTROLE (Resultados)'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='total_acoes_andamento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações em Andamento'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='total_acoes_completas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações Completas'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='total_acoes_planejadas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações Planejadas'),
        ),
        migrations.AddField(
            model_name='solucaoa3',
            name='total_acoes_prioridade_andamento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Ações Prioridade em Andamento'),
        ),
        migrations.AlterField(
            model_name='solucaoa3',
            name='analise_causas',
            field=models.TextField(blank=True, null=True, verbose_name='Análise de Causas'),
        ),
        migrations.AlterField(
            model_name='solucaoa3',
            name='causa_raiz',
            field=models.TextField(blank=True, null=True, verbose_name='Causa Raiz Identificada'),
        ),
        migrations.AddIndex(
            model_name='revisaogerencial',
            index=models.Index(fields=['numero_rg'], name='acoes_revis_numero__6b2129_idx'),
        ),
        migrations.AddIndex(
            model_name='revisaogerencial',
            index=models.Index(fields=['data_realizacao'], name='acoes_revis_data_re_136db0_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaoa3',
            index=models.Index(fields=['a3_numero'], name='acoes_soluc_a3_nume_1b4f56_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaoa3',
            index=models.Index(fields=['lider_projeto'], name='acoes_soluc_lider_p_cf5214_idx'),
        ),
    ]
