# Generated by Django 5.0.14 on 2026-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0012_revisaogerencial_standard_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Origem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Origem de Problema',
                'verbose_name_plural': 'Origens de Problema',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='acoes_orige_nome_d966a4_idx'), models.Index(fields=['ativo'], name='acoes_orige_ativo_51f545_idx')],
            },
        ),
    ]
