# Generated by Django 5.0.14 on 2026-02-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0013_origemproblema'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acao', models.IntegerField(verbose_name='Nº Ação')),
                ('input_origem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Input/Origem')),
                ('problema', models.TextField(blank=True, null=True, verbose_name='Problema')),
                ('kpi', models.CharField(blank=True, max_length=100, null=True, verbose_name='KPI')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('classificacao', models.CharField(blank=True, choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('melhoria', 'Melhoria')], max_length=20, null=True, verbose_name='Classificação')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_curso', 'Em Curso/Andamento'), ('completa', 'Completa/Concluído'), ('retardo', 'Retardo/Atrasada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('prioridade', models.BooleanField(default=False, verbose_name='Prioridade (Y/N)')),
                ('data_primeira_deadline', models.DateField(blank=True, null=True, verbose_name='1º Deadline')),
                ('data_deadline', models.DateField(blank=True, null=True, verbose_name='Deadline Final')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('acao_eficaz', models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plano_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_acao', to='acoes.planoacao', verbose_name='Plano de Ação')),
                ('responsaveis_multiplos', models.ManyToManyField(blank=True, related_name='linhas_acao_multiplos', to='rh.colaborador', verbose_name='Responsáveis (Múltiplos)')),
                ('responsavel_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_acao_responsavel', to='rh.colaborador', verbose_name='Responsável Principal')),
            ],
            options={
                'verbose_name': 'Linha de Ação',
                'verbose_name_plural': 'Linhas de Ação',
                'ordering': ['plano_acao', 'numero_acao'],
                'indexes': [models.Index(fields=['plano_acao', 'numero_acao'], name='acoes_linha_plano_a_0ca5ca_idx'), models.Index(fields=['status'], name='acoes_linha_status_e4138e_idx'), models.Index(fields=['prioridade'], name='acoes_linha_priorid_480fb2_idx')],
                'unique_together': {('plano_acao', 'numero_acao')},
            },
        ),
    ]
