# Generated by Django 5.0.14 on 2026-02-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0014_linhaacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do KPI')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Opção de KPI',
                'verbose_name_plural': 'Opções de KPI',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='acoes_kpiop_nome_620c9c_idx'), models.Index(fields=['ativo'], name='acoes_kpiop_ativo_2e4960_idx')],
            },
        ),
    ]
