# Generated by Django 5.0.14 on 2026-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0015_kpiopcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaocorretiva',
            name='link_registro',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link do Registro'),
        ),
        migrations.AlterField(
            model_name='acaocorretiva',
            name='tipo_solucao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Solução'),
        ),
    ]
