# Generated by Django 5.0.14 on 2026-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0016_alter_acaocorretiva_link_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaocorretiva',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], default='aberta', max_length=20, verbose_name='Status'),
        ),
    ]
