# Generated by Django 5.0.14 on 2026-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0019_linhaacao_responsaveis_externos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tiposolucao',
            new_name='acoes_tipos_nome_16a01a_idx',
            old_name='acoes_tipo_nome_idx',
        ),
        migrations.RenameIndex(
            model_name='tiposolucao',
            new_name='acoes_tipos_ativo_f50c46_idx',
            old_name='acoes_tipo_ativo_idx',
        ),
        migrations.AlterField(
            model_name='linhaacao',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AlterField(
            model_name='revisaogerencial',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AlterField(
            model_name='solucao8d',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AlterField(
            model_name='solucaoa3',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AlterField(
            model_name='solucaogestaodemudanca',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
        migrations.AlterField(
            model_name='solucaornc',
            name='acao_eficaz',
            field=models.CharField(blank=True, choices=[('eficaz', 'Eficaz'), ('nao_eficaz', 'Não Eficaz'), ('parcialmente_eficaz', 'Parcialmente Eficaz')], max_length=20, null=True, verbose_name='Ação Eficaz?'),
        ),
    ]
