# Generated by Django 5.0.14 on 2026-05-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maquinas", "0002_categoriamaquina_maquina_categoria"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriamaquina",
            options={
                "ordering": ("nome",),
                "verbose_name": "categoria de maquina",
                "verbose_name_plural": "categorias de maquinas",
            },
        ),
        migrations.AlterModelOptions(
            name="maquina",
            options={
                "ordering": ("nome", "codigo"),
                "verbose_name": "maquina",
                "verbose_name_plural": "maquinas",
            },
        ),
    ]
