# Generated by Django 5.0.14 on 2026-05-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maquinas", "0003_alter_categoriamaquina_options_alter_maquina_options"),
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maquina",
            options={
                "ordering": ("codigo", "numero_serie", "fabricante"),
                "verbose_name": "maquina",
                "verbose_name_plural": "maquinas",
            },
        ),
        migrations.AddField(
            model_name="maquina",
            name="fabricante",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="maquina",
            name="numero_serie",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="maquina",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maquinas",
                to="organization.setor",
            ),
        ),
        migrations.AlterField(
            model_name="maquina",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
