# Generated by Django 5.0.14 on 2025-12-08 22:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArquivoPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("arquivo", models.FileField(upload_to="padroes/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Arquivo Padrão",
                "verbose_name_plural": "Arquivos Padrões",
            },
        ),
        migrations.CreateModel(
            name="OrdemCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fornecedor",
                    models.CharField(
                        help_text="Nome do Laboratório/Empresa", max_length=100
                    ),
                ),
                (
                    "tipo_local",
                    models.CharField(
                        choices=[
                            ("EXTERNO", "Laboratório Externo"),
                            ("IN_LOCO", "Calibração In Loco (Na Empresa)"),
                        ],
                        default="EXTERNO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADO", "Agendado"),
                            ("ENVIADO", "Enviado ao Fornecedor"),
                            ("EM_CALIBRACAO", "Em Calibração"),
                            ("RETORNOU", "Retornou do Fornecedor"),
                            ("FINALIZADO", "Finalizado e Aprovado"),
                        ],
                        default="AGENDADO",
                        max_length=20,
                    ),
                ),
                ("data_prevista", models.DateField()),
                (
                    "data_envio",
                    models.DateField(
                        blank=True, help_text="Data de saída da empresa", null=True
                    ),
                ),
                (
                    "data_retorno",
                    models.DateField(
                        blank=True, help_text="Data de chegada na empresa", null=True
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "certificado_arquivo",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoFaixaCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_maximo", models.DecimalField(decimal_places=4, max_digits=10)),
                ("valor_minimo", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "nominal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "erro_max",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "erro_min",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "incerteza",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[("OK", "OK"), ("FORA", "Fora da Faixa")],
                        default="OK",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Faixa",
                "verbose_name_plural": "Resultados por Faixa",
            },
        ),
        migrations.CreateModel(
            name="CategoriaInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "unidade_padrao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.unidademedida",
                        verbose_name="Unidade Padrão",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorias de Instrumentos",
            },
        ),
        migrations.CreateModel(
            name="FaixaMedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_minimo", models.DecimalField(decimal_places=4, max_digits=10)),
                ("valor_maximo", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor central/nominal do processo",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tolerancia_mais_menos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Variação aceitável (+/-)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unidademedida",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Faixas de Medição",
            },
        ),
        migrations.CreateModel(
            name="HistoricoCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_calibracao", models.DateField()),
                ("data_aprovacao", models.DateField(default=datetime.date.today)),
                ("numero_certificado", models.CharField(default="S/N", max_length=100)),
                (
                    "tem_selo_rbc",
                    models.BooleanField(default=False, verbose_name="Possui Selo RBC?"),
                ),
                (
                    "tipo_calibracao",
                    models.CharField(
                        choices=[
                            ("EXTERNA", "Externa (Fornecedor)"),
                            ("INTERNA", "Interna (Equipe Própria)"),
                        ],
                        default="EXTERNA",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Responsável Técnica",
                    ),
                ),
                (
                    "fornecedor",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Laboratório/Fornecedor",
                    ),
                ),
                (
                    "erro_encontrado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Erro (E)",
                    ),
                ),
                (
                    "incerteza",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Incerteza (U)",
                    ),
                ),
                (
                    "tolerancia_usada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Tol. Processo (+/-)",
                    ),
                ),
                ("proxima_calibracao", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                ("certificado_validado", models.BooleanField(default=False)),
                (
                    "certificado_carimbado",
                    models.FileField(
                        blank=True, null=True, upload_to="certificados/carimbados/"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("APROVADO_SEM_CORRECAO", "Aprovado sem correção"),
                            ("APROVADO_COM_CORRECAO", "Aprovado com Correção"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="APROVADO_SEM_CORRECAO",
                        max_length=50,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "arquivos_padroes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="historicos",
                        to="metrologia.arquivopadrao",
                        verbose_name="Arquivos de Padrões (PDF)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico Calibração",
                "verbose_name_plural": "Históricos de Calibração",
                "ordering": ["-data_calibracao"],
            },
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tolerancia_processo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Tolerância do processo (+/-), associada ao instrumento",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="TAG / Identificação"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Interno",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("fabricante", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("serie", models.CharField(blank=True, max_length=100, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("data_ultima_calibracao", models.DateField(blank=True, null=True)),
                ("data_proxima_calibracao", models.DateField(blank=True, null=True)),
                ("frequencia_meses", models.IntegerField(default=12)),
                (
                    "localizacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metrologia.categoriainstrumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
            },
        ),
    ]
