# Generated by Django 5.0.14 on 2025-12-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metrologia", "0001_initial"),
        ("organization", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumento",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="instrumento",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.setor",
            ),
        ),
        migrations.AddField(
            model_name="historicocalibracao",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historicos",
                to="metrologia.instrumento",
                verbose_name="Instrumento",
            ),
        ),
        migrations.AddField(
            model_name="faixamedicao",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faixas",
                to="metrologia.instrumento",
            ),
        ),
        migrations.AddField(
            model_name="ordemcalibracao",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calibracoes",
                to="metrologia.instrumento",
            ),
        ),
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="faixa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metrologia.faixamedicao",
            ),
        ),
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="historico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados_faixa",
                to="metrologia.historicocalibracao",
            ),
        ),
    ]
