# Generated by Django 5.0.14 on 2025-12-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("metrologia", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="faixamedicao",
            unique_together={
                ("instrumento", "unidade", "valor_minimo", "valor_maximo")
            },
        ),
    ]
