# Generated by Django 5.0.14 on 2025-12-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("metrologia", "0003_add_faixamedicao_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaixaMedicaoPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_minimo", models.DecimalField(decimal_places=4, max_digits=10)),
                ("valor_maximo", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor central/nominal do processo",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tolerancia_mais_menos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Variação aceitável (+/-)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Faixa Ativa"),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unidademedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faixa de Medição Padrão",
                "verbose_name_plural": "Faixas de Medição Padrão",
                "ordering": ["referencia_instrumento", "valor_minimo"],
            },
        ),
        migrations.AddField(
            model_name="faixamedicao",
            name="faixa_padrao",
            field=models.ForeignKey(
                blank=True,
                help_text="Referência à faixa padrão para reutilização",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faixas_instancia",
                to="metrologia.faixamedicaopadrao",
                verbose_name="Faixa Padrão",
            ),
        ),
        migrations.CreateModel(
            name="InstrumentoReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_referencia",
                    models.CharField(
                        help_text="Código único que permanece mesmo com substituições",
                        max_length=50,
                        unique=True,
                        verbose_name="Código de Referência",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição Geral"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metrologia.categoriainstrumento",
                        verbose_name="Categoria Padrão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento Referência",
                "verbose_name_plural": "Instrumentos Referências",
            },
        ),
        migrations.AddField(
            model_name="faixamedicaopadrao",
            name="referencia_instrumento",
            field=models.ForeignKey(
                help_text="Instrumento de referência para esta faixa padrão",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faixas_padrao",
                to="metrologia.instrumentoreferencia",
                verbose_name="Referência de Instrumento",
            ),
        ),
        migrations.AddField(
            model_name="instrumento",
            name="referencia",
            field=models.ForeignKey(
                blank=True,
                help_text="Instrumento anterior (em caso de substituição)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrumentos_substituidos",
                to="metrologia.instrumentoreferencia",
                verbose_name="Referência de Instrumento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="faixamedicaopadrao",
            unique_together={
                ("referencia_instrumento", "unidade", "valor_minimo", "valor_maximo")
            },
        ),
    ]
