# Generated by Django 5.0.14 on 2025-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0004_faixamedicaopadrao_faixamedicao_faixa_padrao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadofaixacalibracao",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("APROVADO_SEM_CORRECAO", "Aprovado sem Correção"),
                    ("APROVADO_COM_CORRECAO", "Aprovado com Correção"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="APROVADO_SEM_CORRECAO",
                max_length=50,
            ),
        ),
    ]
