# Generated by Django 5.0.14 on 2025-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0005_alter_resultadofaixacalibracao_resultado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadofaixacalibracao",
            name="erro_max",
        ),
        migrations.RemoveField(
            model_name="resultadofaixacalibracao",
            name="erro_min",
        ),
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="erro",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="tolerancia",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
