# Generated by Django 5.0.14 on 2025-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0006_remove_resultadofaixacalibracao_erro_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="ema",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Calculado como 2*Tolerância/4",
                max_digits=10,
                null=True,
                verbose_name="EMA (Erro Máximo Admissível)",
            ),
        ),
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="eme",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Calculado como Erro + Incerteza",
                max_digits=10,
                null=True,
                verbose_name="EME (Erro Máximo do Equipamento)",
            ),
        ),
        migrations.AlterField(
            model_name="resultadofaixacalibracao",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("APROVADO_SEM_CORRECAO", "Aprovado sem Correção"),
                    ("APROVADO_COM_CORRECAO", "Aprovado com Correção"),
                    ("REPROVADO", "Reprovado / Restrição"),
                ],
                default="APROVADO_SEM_CORRECAO",
                max_length=50,
            ),
        ),
    ]
