# Generated by Django 5.0.14 on 2025-12-13 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0003_alter_avaliacaofornecedor_data"),
        ("metrologia", "0007_resultadofaixacalibracao_ema_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "data_proposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Recebimento Proposta"
                    ),
                ),
                (
                    "data_decisao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Aprovação/Reprovação"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Orçado (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CRIADA", "Criada"),
                            ("ENVIADA", "Enviada para Fornecedor"),
                            ("PROPOSTA_RECEBIDA", "Proposta Recebida"),
                            ("APROVADA", "Aprovada"),
                            ("REPROVADA", "Reprovada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="CRIADA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes",
                        to="fornecedores.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "instrumentos",
                    models.ManyToManyField(
                        help_text="Selecione um ou mais instrumentos para calibração",
                        related_name="cotacoes",
                        to="metrologia.instrumento",
                        verbose_name="Instrumentos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotação",
                "verbose_name_plural": "Cotações",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ATRASO", "Atraso no Envio"),
                            ("FALTA_RESPOSTA", "Falta de Resposta"),
                            ("VALOR_ALTO", "Valor Orçado Alto"),
                            ("VALOR_BAIXO", "Valor Orçado Baixo"),
                            ("PRAZO", "Prazo de Entrega"),
                            ("QUALIDADE", "Dúvida sobre Qualidade"),
                            ("COMUNICACAO", "Problemas de Comunicação"),
                            ("DOCUMENTACAO", "Falta de Documentação"),
                            ("RECURSO", "Recurso/Reclamação"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ocorrência",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Ocorrência"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Detalhe sobre a ocorrência", verbose_name="Descrição"
                    ),
                ),
                (
                    "acao_tomada",
                    models.TextField(
                        blank=True,
                        help_text="Qual ação foi tomada em resposta",
                        null=True,
                        verbose_name="Ação Tomada",
                    ),
                ),
                (
                    "resolvida",
                    models.BooleanField(
                        default=False, verbose_name="Ocorrência Resolvida"
                    ),
                ),
                (
                    "data_resolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Resolução"
                    ),
                ),
                (
                    "cotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="metrologia.cotacao",
                        verbose_name="Cotação",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pelo Registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência de Cotação",
                "verbose_name_plural": "Ocorrências de Cotação",
                "ordering": ["-data"],
            },
        ),
    ]
