# Generated by Django 5.0.14 on 2025-12-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0003_alter_avaliacaofornecedor_data"),
        ("metrologia", "0008_cotacao_ocorrenciacotacao"),
        ("organization", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Auto-gerado: COT-YYYY-####-FOR###",
                        max_length=20,
                        unique=True,
                        verbose_name="Número da Cotação",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_envio_para_fornecedor",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Envio para Fornecedor",
                    ),
                ),
                (
                    "data_proposta_recebida",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Recebimento da Proposta",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ENVIADA", "Enviada para Fornecedor"),
                            ("RESPONDIDA", "Proposta Respondida"),
                            ("ACEITA", "Aceita"),
                            ("REJEITADA", "Rejeitada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observações Gerais da Cotação",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotacoes_fornecedor_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes_novo_fluxo",
                        to="fornecedores.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotação do Fornecedor",
                "verbose_name_plural": "Cotações de Fornecedores",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ItemSolicitacaoCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "necessidade",
                    models.CharField(
                        help_text='Ex: "Calibração de precisão", "Verificação de função"',
                        max_length=500,
                        verbose_name="Necessidade / Tipo de Serviço",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        default=1, verbose_name="Quantidade de Instrumentos Iguais"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Adicionais"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes_itens",
                        to="metrologia.instrumento",
                        verbose_name="Instrumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Solicitação de Cotação",
                "verbose_name_plural": "Itens da Solicitação de Cotação",
                "ordering": ["instrumento__tag"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pode_atender",
                    models.BooleanField(
                        default=False, verbose_name="Pode Atender esta Necessidade?"
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("CALIBRACAO", "Calibração de Instrumento Existente"),
                            ("AQUISICAO", "Aquisição de Instrumento Novo"),
                        ],
                        default="CALIBRACAO",
                        max_length=20,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor Unitário (R$)",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculado automaticamente: valor_unitário × quantidade",
                        max_digits=10,
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "prazo_dias",
                    models.IntegerField(
                        blank=True,
                        help_text="Quantos dias para executar o serviço?",
                        null=True,
                        verbose_name="Prazo (dias)",
                    ),
                ),
                (
                    "descricao_servico",
                    models.TextField(
                        blank=True,
                        help_text="Detalhe do que será feito, normas aplicáveis, etc.",
                        null=True,
                        verbose_name="Descrição do Serviço",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cotacao_fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="metrologia.cotacaofornecedor",
                        verbose_name="Cotação do Fornecedor",
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes_itens",
                        to="metrologia.instrumento",
                        verbose_name="Instrumento",
                    ),
                ),
                (
                    "item_solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes_itens",
                        to="metrologia.itemsolicitacaocotacao",
                        verbose_name="Item da Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Cotação",
                "verbose_name_plural": "Itens de Cotação",
                "ordering": ["instrumento__tag"],
                "unique_together": {("cotacao_fornecedor", "instrumento")},
            },
        ),
        migrations.CreateModel(
            name="AtendimentoSolicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_escolha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Escolha"
                    ),
                ),
                (
                    "data_prevista_atendimento",
                    models.DateField(
                        help_text="Quando será executado o serviço?",
                        verbose_name="Data Prevista de Atendimento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXECUTANDO", "Executando"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos_definidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pela Escolha",
                    ),
                ),
                (
                    "item_cotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="metrologia.itemcotacao",
                        verbose_name="Item da Cotação (Fornecedor)",
                    ),
                ),
                (
                    "item_solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="metrologia.itemsolicitacaocotacao",
                        verbose_name="Item da Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendimento de Solicitação",
                "verbose_name_plural": "Atendimentos de Solicitação",
                "ordering": ["-data_escolha"],
            },
        ),
        migrations.CreateModel(
            name="ProcessoAutomatizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_processo",
                    models.CharField(
                        choices=[
                            ("AQUISICAO", "Aquisição de Instrumento"),
                            ("CALIBRACAO", "Calibração"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Processo",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "id_objeto_criado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Objeto Criado"
                    ),
                ),
                (
                    "nome_modelo_objeto",
                    models.CharField(
                        blank=True,
                        help_text="Ex: RegistroCalibracao, ProcessoSubstituicao",
                        max_length=100,
                        null=True,
                        verbose_name="Modelo do Objeto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("CONCLUIDA", "Concluída"),
                            ("ERRO", "Erro"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ATIVA",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Registrar erros ou detalhes do processo",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos_automatizacao",
                        to="metrologia.atendimentosolicitacao",
                        verbose_name="Atendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo de Automatização",
                "verbose_name_plural": "Processos de Automatização",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Auto-gerado: SOL-YYYY-####",
                        max_length=20,
                        unique=True,
                        verbose_name="Número da Solicitação",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_inicio_vencimento",
                    models.DateField(
                        help_text="Data a partir da qual queremos atender instrumentos vencidos",
                        verbose_name="Início do Período de Vencimento",
                    ),
                ),
                (
                    "data_fim_vencimento",
                    models.DateField(
                        help_text="Data até quando queremos atender (ex: próximos 30/60/90 dias)",
                        verbose_name="Fim do Período de Vencimento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("AGUARDANDO_COTACOES", "Aguardando Cotações"),
                            ("COTACOES_RECEBIDAS", "Cotações Recebidas"),
                            ("ENCERRADA", "Encerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Por que precisa? Contexto geral?",
                        null=True,
                        verbose_name="Descrição da Solicitação",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.setor",
                        verbose_name="Departamento / Setor",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_cotacao_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Cotação",
                "verbose_name_plural": "Solicitações de Cotação",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.AddField(
            model_name="itemsolicitacaocotacao",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="metrologia.solicitacaocotacao",
                verbose_name="Solicitação",
            ),
        ),
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cotacoes_fornecedores",
                to="metrologia.solicitacaocotacao",
                verbose_name="Solicitação",
            ),
        ),
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendimentos",
                to="metrologia.solicitacaocotacao",
                verbose_name="Solicitação",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemsolicitacaocotacao",
            unique_together={("solicitacao", "instrumento")},
        ),
        migrations.AlterUniqueTogether(
            name="cotacaofornecedor",
            unique_together={("solicitacao", "fornecedor")},
        ),
    ]
