# Generated by Django 5.0.14 on 2025-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrologia",
            "0009_cotacaofornecedor_itemsolicitacaocotacao_itemcotacao_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaocotacao",
            name="data_fim_vencimento",
        ),
        migrations.RemoveField(
            model_name="solicitacaocotacao",
            name="data_inicio_vencimento",
        ),
        migrations.AddField(
            model_name="solicitacaocotacao",
            name="dias_vencimento",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Quantos dias no futuro buscar instrumentos vencidos ou vencendo",
                verbose_name="Dias no Futuro",
            ),
        ),
    ]
