# Generated by Django 5.0.14 on 2025-12-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0010_remove_solicitacaocotacao_data_fim_vencimento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaocotacao",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="solicitacaocotacao",
            name="prioridade",
        ),
    ]
