# Generated by Django 5.0.14 on 2025-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0011_remove_solicitacaocotacao_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumento",
            name="tratativa_calibracao",
            field=models.CharField(
                choices=[("INTERNA", "Interna"), ("EXTERNA", "Externa")],
                default="INTERNA",
                help_text="Indica se a calibração é feita internamente ou com fornecedor externo",
                max_length=10,
                verbose_name="Tratativa de Calibração",
            ),
        ),
    ]
