# Generated by Django 5.0.14 on 2025-12-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0012_instrumento_tratativa_calibracao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsolicitacaocotacao",
            name="quantidade",
        ),
    ]
