# Generated by Django 5.0.14 on 2025-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0013_remove_itemsolicitacaocotacao_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsolicitacaocotacao",
            name="necessidade",
        ),
        migrations.AddField(
            model_name="itemsolicitacaocotacao",
            name="faixa_centro",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Faixa Centro",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaocotacao",
            name="faixa_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Faixa Máxima",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaocotacao",
            name="faixa_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Faixa Mínima",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaocotacao",
            name="tipo_pontos",
            field=models.CharField(
                choices=[("3", "3 Pontos"), ("6", "6 Pontos"), ("9", "9 Pontos")],
                default="3",
                max_length=1,
                verbose_name="Tipo de Pontos de Calibração",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaocotacao",
            name="unidade_pontos",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Unidade dos Pontos"
            ),
        ),
    ]
