# Generated by Django 5.0.14 on 2025-12-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0014_remove_itemsolicitacaocotacao_necessidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSolicitacaoFaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Mínimo (Override)",
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Máximo (Override)",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "faixa_medicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_solicitacao",
                        to="metrologia.faixamedicao",
                        verbose_name="Faixa de Medição",
                    ),
                ),
                (
                    "item_solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faixas_selecionadas",
                        to="metrologia.itemsolicitacaocotacao",
                        verbose_name="Item da Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faixa de Item de Solicitação",
                "verbose_name_plural": "Faixas de Itens de Solicitação",
                "ordering": ["faixa_medicao__valor_minimo"],
                "unique_together": {("item_solicitacao", "faixa_medicao")},
            },
        ),
    ]
