# Generated by Django 5.0.14 on 2025-12-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0015_itemsolicitacaofaixa"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="numero_pontos",
            field=models.IntegerField(
                choices=[(3, "3 Pontos"), (5, "5 Pontos"), (7, "7 Pontos")],
                default=3,
                verbose_name="Número de Pontos de Calibração",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 1",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 2",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 3",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_4",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 4",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_5",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 5",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_6",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 6",
            ),
        ),
        migrations.AddField(
            model_name="itemsolicitacaofaixa",
            name="ponto_7",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Ponto 7",
            ),
        ),
    ]
