# Generated by Django 5.0.14 on 2025-12-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0016_itemsolicitacaofaixa_numero_pontos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocotacao",
            name="data_solicitacao_orcamento",
            field=models.DateField(
                blank=True,
                help_text="Data em que o orçamento foi solicitado",
                null=True,
                verbose_name="Data de Solicitação de Orçamento",
            ),
        ),
    ]
