# Generated by Django 5.0.14 on 2025-12-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0017_solicitacaocotacao_data_solicitacao_orcamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="data_retorno_fornecedor",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Retorno do Fornecedor"
            ),
        ),
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="data_solicitacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Solicitação"
            ),
        ),
        migrations.AddField(
            model_name="itemcotacao",
            name="local_atendimento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_LOCAL", "No local (Cliente)"),
                    ("NO_LABORATORIO", "No Laboratório (Fornecedor)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Local de Atendimento",
            ),
        ),
    ]
