# Generated by Django 5.0.14 on 2025-12-16 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0018_cotacaofornecedor_data_retorno_fornecedor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="aprovada",
            field=models.BooleanField(
                default=False, verbose_name="Cotação Aprovada para Planejamento"
            ),
        ),
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotacoes_fornecedor_aprovadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Aprovação"
            ),
        ),
        migrations.AlterField(
            model_name="itemcotacao",
            name="local_atendimento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_LOCAL", "No local (Cliente)"),
                    ("NO_LABORATORIO", "No Laboratório (Fornecedor)"),
                    ("COMPRAR_NOVO", "Comprar Novo"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Atendimento",
            ),
        ),
    ]
