# Generated by Django 5.0.14 on 2025-12-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0019_cotacaofornecedor_aprovada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="data_chegada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Chegada (Compra Novo)"
            ),
        ),
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="data_envio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Envio (Lab)"
            ),
        ),
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="data_realizada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Realizada (No Local)"
            ),
        ),
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="data_retorno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Retorno (Lab)"
            ),
        ),
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="data_retorno_previsto",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Retorno Previsto"
            ),
        ),
        migrations.AddField(
            model_name="atendimentosolicitacao",
            name="tecnico_responsavel",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Técnico Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="cotacaofornecedor",
            name="aprovada",
            field=models.BooleanField(default=False, verbose_name="Cotação Aprovada"),
        ),
    ]
