# Generated by Django 5.0.14 on 2025-12-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0020_atendimentosolicitacao_data_chegada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacaofornecedor",
            name="observacoes_execucao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações de Execução/Entrega"
            ),
        ),
    ]
