# Generated by Django 5.0.14 on 2025-12-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0021_cotacaofornecedor_observacoes_execucao"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicocalibracao",
            name="atendimento",
            field=models.ForeignKey(
                blank=True,
                help_text="Atendimento da cotação que originou esta calibração",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historicos_calibracao",
                to="metrologia.atendimentosolicitacao",
                verbose_name="Atendimento da Solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocotacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTA", "Aberta"),
                    ("INSTRUMENTOS_SELECIONADOS", "Instrumentos Selecionados"),
                    ("COTACAO_SOLICITADA", "Cotação Solicitada"),
                    ("AGUARDANDO_PLANEJAMENTO", "Aguardando Planejamento"),
                    ("PARCIALMENTE_PLANEJADA", "Parcialmente Planejada"),
                    ("PLANEJADA", "Planejada"),
                    ("PARCIALMENTE_REALIZADO", "Parcialmente Realizado"),
                    ("REALIZADO", "Realizado"),
                    ("CONCLUIDA", "Concluída"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="ABERTA",
                max_length=25,
                verbose_name="Status",
            ),
        ),
    ]
