# Generated by Django 5.0.14 on 2025-12-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("metrologia", "0022_historicocalibracao_atendimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaixaMedicaoPadraoCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_minimo", models.DecimalField(decimal_places=4, max_digits=10)),
                ("valor_maximo", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor central/nominal do processo",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tolerancia_mais_menos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Variação aceitável (+/-)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Faixa Ativa"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Categoria de instrumento para esta faixa padrão",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faixas_padrao_medicao",
                        to="metrologia.categoriainstrumento",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unidademedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faixa de Medição Padrão de Categoria",
                "verbose_name_plural": "Faixas de Medição Padrão de Categorias",
                "ordering": ["categoria", "valor_minimo"],
                "unique_together": {
                    ("categoria", "unidade", "valor_minimo", "valor_maximo")
                },
            },
        ),
    ]
