# Generated by Django 5.0.14 on 2025-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0024_remove_categoriainstrumento_unidade_padrao"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriainstrumento",
            name="sigla",
            field=models.CharField(
                blank=True,
                help_text="Prefixo padrão para códigos de instrumentos (Ex: TH para termohigrômetros)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="categoriainstrumento",
            name="tratativa_calibracao",
            field=models.CharField(
                choices=[("INTERNA", "Interna"), ("EXTERNA", "Externa")],
                default="INTERNA",
                help_text="Tipo de calibração padrão para instrumentos desta categoria",
                max_length=20,
            ),
        ),
    ]
