# Generated by Django 5.0.14 on 2025-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0025_add_sigla_tratativa_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriainstrumento",
            name="sigla",
            field=models.CharField(
                blank=True,
                help_text="Prefixo padrão para códigos de instrumentos (Ex: TH para termohigrômetros)",
                max_length=3,
                null=True,
            ),
        ),
    ]
