# Generated by Django 5.0.14 on 2025-12-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0026_update_sigla_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriainstrumento",
            name="frequencia_calibracao_meses",
            field=models.IntegerField(
                blank=True,
                default=12,
                help_text="Intervalo em meses entre as calibrações para instrumentos desta categoria",
                null=True,
                verbose_name="Frequência de Calibração (Meses)",
            ),
        ),
    ]
