# Generated by Django 5.0.14 on 2025-12-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0027_categoriainstrumento_frequencia_calibracao_meses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arquivopadrao",
            options={
                "ordering": ["-data_upload"],
                "verbose_name": "Arquivo Padrão",
                "verbose_name_plural": "Arquivos Padrões",
            },
        ),
        migrations.RemoveField(
            model_name="historicocalibracao",
            name="arquivos_padroes",
        ),
        migrations.AddField(
            model_name="arquivopadrao",
            name="historico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="padroes_arquivo",
                to="metrologia.historicocalibracao",
                verbose_name="Histórico de Calibração",
            ),
        ),
    ]
