# Generated by Django 5.0.14 on 2026-01-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0028_refactor_arquivo_padrao_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadofaixacalibracao",
            name="tabela_correcao",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tabela com valores de correção a aplicar nas medições quando resultado é APROVADO_COM_CORRECAO",
                null=True,
                verbose_name="Tabela de Correção",
            ),
        ),
    ]
