# Generated by Django 5.0.14 on 2026-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0029_add_tabela_correcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainstrumento',
            name='acao',
            field=models.CharField(choices=[('CALIBRACAO', 'Calibração'), ('VERIFICACAO', 'Verificação')], default='CALIBRACAO', max_length=20, verbose_name='Ação'),
        ),
    ]
