# Generated by Django 5.0.14 on 2026-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0030_categoriainstrumento_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriainstrumento',
            name='acao',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='acao',
            field=models.CharField(choices=[('CALIBRACAO', 'Calibração'), ('VERIFICACAO', 'Verificação')], default='CALIBRACAO', max_length=20, verbose_name='Ação'),
        ),
    ]
