# Generated by Django 5.0.14 on 2026-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0031_remove_categoriainstrumento_acao_instrumento_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainstrumento',
            name='acao',
            field=models.CharField(choices=[('CALIBRACAO', 'Calibração'), ('VERIFICACAO', 'Verificação')], default='CALIBRACAO', help_text='Define se os instrumentos desta categoria sofrem Calibração ou Verificação por padrão.', max_length=20, verbose_name='Ação Padrão'),
        ),
    ]
