# Generated by Django 5.0.14 on 2026-09-01 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0034_recalcular_ema_eme_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEtiquetaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: ETQ-IND-01, ETQ-MULTI-A4, ETQ-GRADE-2X5', max_length=50, unique=True, verbose_name='Código do Modelo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template / Variação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Instruções')),
                ('tipo_variacao', models.CharField(choices=[('INDIVIDUAL', 'Individual (1 Instrumento por Arquivo)'), ('MULTI_ABA', 'Múltiplas Abas (1 Aba por Instrumento)'), ('GRADE_TABELA', 'Grade / Tabela (Múltiplos Instrumentos na mesma Folha)')], default='INDIVIDUAL', max_length=30, verbose_name='Tipo de Variação da Etiqueta')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='templates_etiquetas_metrologia/', verbose_name='Arquivo do Template (.xlsx)')),
                ('arquivo_base64', models.TextField(blank=True, default='', help_text='Persistência do binário em banco de dados para ambiente serverless/nuvem', verbose_name='Conteúdo em Base64')),
                ('nome_arquivo_original', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome Original do Arquivo')),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Template Padrão da Variação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Etiqueta de Instrumento',
                'verbose_name_plural': 'Templates de Etiquetas de Instrumentos',
                'ordering': ['tipo_variacao', '-padrao', 'nome'],
            },
        ),
    ]
