# Generated by Django 5.0.14 on 2025-12-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0001_initial"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Disciplina"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="PerfilTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Perfil"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Perfil de Treinamento",
                "verbose_name_plural": "Perfis de Treinamento",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="MatrizHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Matriz"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Setor"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "disciplinas",
                    models.ManyToManyField(
                        related_name="matrizes",
                        to="procedures.disciplina",
                        verbose_name="Disciplinas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz de Habilidade",
                "verbose_name_plural": "Matrizes de Habilidades",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="GrupoTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Grupo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "ordem",
                    models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="procedures.perfiltreinamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Treinamento",
                "verbose_name_plural": "Grupos de Treinamento",
                "ordering": ["perfil", "ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="PlanejamentoTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título do Treinamento"
                    ),
                ),
                ("data_prevista", models.DateField(verbose_name="Data Prevista")),
                (
                    "data_realizada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Realizada"
                    ),
                ),
                (
                    "carga_horaria",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Carga Horária (minutos)"
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Local"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADO", "Planejado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("REALIZADO", "Realizado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PLANEJADO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaboradores",
                    models.ManyToManyField(
                        related_name="treinamentos_planejados",
                        to="rh.colaborador",
                        verbose_name="Colaboradores",
                    ),
                ),
                (
                    "instrutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treinamentos_ministrados",
                        to="rh.colaborador",
                        verbose_name="Instrutor",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planejamentos",
                        to="procedures.procedimento",
                        verbose_name="Procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planejamento de Treinamento",
                "verbose_name_plural": "Planejamentos de Treinamentos",
                "ordering": ["-data_prevista"],
            },
        ),
        migrations.CreateModel(
            name="SubGrupoTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Sub-Grupo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "ordem",
                    models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgrupos",
                        to="procedures.grupotreinamento",
                    ),
                ),
                (
                    "procedimentos",
                    models.ManyToManyField(
                        related_name="subgrupos_treinamento",
                        to="procedures.procedimento",
                        verbose_name="Procedimentos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Grupo de Treinamento",
                "verbose_name_plural": "Sub-Grupos de Treinamento",
                "ordering": ["grupo", "ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (0, "0 - Sem conhecimento"),
                            (1, "1 - Básico"),
                            (2, "2 - Intermediário"),
                            (3, "3 - Avançado/Instrutor"),
                        ],
                        default=0,
                        verbose_name="Nível de Competência",
                    ),
                ),
                ("data_avaliacao", models.DateField(verbose_name="Data da Avaliação")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes_realizadas",
                        to="rh.colaborador",
                        verbose_name="Avaliador",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_habilidade",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="procedures.disciplina",
                    ),
                ),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="procedures.matrizhabilidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Habilidade",
                "verbose_name_plural": "Avaliações de Habilidades",
                "ordering": ["-data_avaliacao"],
                "unique_together": {("colaborador", "disciplina", "matriz")},
            },
        ),
        migrations.CreateModel(
            name="ColaboradorPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_atribuicao",
                    models.DateField(verbose_name="Data de Atribuição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfis_treinamento",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboradores",
                        to="procedures.perfiltreinamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador-Perfil",
                "verbose_name_plural": "Colaboradores-Perfis",
                "ordering": ["colaborador", "perfil"],
                "unique_together": {("colaborador", "perfil")},
            },
        ),
    ]
