# Generated by Django 5.0.14 on 2025-12-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0002_disciplina_perfiltreinamento_matrizhabilidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matrizhabilidade",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="matrizhabilidade",
            name="disciplinas",
        ),
        migrations.RemoveField(
            model_name="matrizhabilidade",
            name="setor",
        ),
        migrations.AddField(
            model_name="disciplina",
            name="matriz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinas_matriz",
                to="procedures.matrizhabilidade",
                verbose_name="Matriz",
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="codigo",
            field=models.CharField(max_length=50, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="matrizhabilidade",
            name="codigo",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Código"
            ),
        ),
    ]
