# Generated by Django 5.0.14 on 2025-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0003_ajuste_matriz_disciplina"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="codigo",
            field=models.CharField(
                editable=False, max_length=50, verbose_name="Código"
            ),
        ),
    ]
