# Generated by Django 5.0.14 on 2025-12-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0004_disciplina_codigo_automatico"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="obrigatoriedade_legal",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Obrigatoriedade Legal",
            ),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="prioridade",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Prioridade"
            ),
        ),
    ]
