# Generated by Django 5.0.14 on 2025-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0005_adicionar_prioridade_obrigatoriedade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfiltreinamento",
            name="codigo",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Código"
            ),
        ),
    ]
