# Generated by Django 5.0.14 on 2025-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0006_perfil_codigo_automatico"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaboradorperfil",
            name="grupos_selecionados",
            field=models.JSONField(
                blank=True,
                help_text="Estrutura: {'grupos': [id1, id2], 'subgrupos': [id1, id2]}",
                null=True,
                verbose_name="Grupos/Subgrupos Selecionados",
            ),
        ),
    ]
