# Generated by Django 5.0.14 on 2025-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0007_adicionar_grupos_selecionados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrotreinamento",
            name="data_treinamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
