# Generated by Django 5.0.14 on 2025-12-27 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0008_data_treinamento_nullable"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Sessão"),
                ),
                ("data_sessao", models.DateField(verbose_name="Data da Sessão")),
                (
                    "hora_inicio",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Início"),
                ),
                (
                    "hora_fim",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Fim"),
                ),
                (
                    "carga_horaria",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Carga Horária (h)",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Local"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listas_presenca_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listas_presenca_como_instrutor",
                        to="rh.colaborador",
                        verbose_name="Instrutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Presença",
                "verbose_name_plural": "Listas de Presença",
                "ordering": ["-data_sessao", "-codigo"],
            },
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="lista_presenca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros",
                to="procedures.listapresenca",
                verbose_name="Lista de Presença",
            ),
        ),
    ]
