# Generated by Django 5.0.14 on 2025-12-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0009_listapresenca_registrotreinamento_lista_presenca"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipanteExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Empresa/Instituição",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Participante Externo",
                "verbose_name_plural": "Participantes Externos",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição/Conteúdo"
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PROCEDIMENTO", "Treinamento em Procedimento"),
                    ("ALINHAMENTO", "Alinhamento Interno"),
                    ("REUNIAO", "Reunião"),
                    ("CAPACITACAO", "Capacitação/Curso"),
                    ("OUTRO", "Outro"),
                ],
                default="PROCEDIMENTO",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="titulo_treinamento",
            field=models.CharField(
                blank=True,
                help_text="Obrigatório quando não há procedimento vinculado",
                max_length=200,
                null=True,
                verbose_name="Título do Treinamento/Reunião",
            ),
        ),
        migrations.AlterField(
            model_name="registrotreinamento",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treinamentos",
                to="rh.colaborador",
                verbose_name="Colaborador",
            ),
        ),
        migrations.AlterField(
            model_name="registrotreinamento",
            name="procedimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros_treinamento",
                to="procedures.procedimento",
                verbose_name="Procedimento",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="participante_externo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treinamentos",
                to="procedures.participanteexterno",
                verbose_name="Participante Externo",
            ),
        ),
    ]
