# Generated by Django 5.0.14 on 2025-12-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "procedures",
            "0010_participanteexterno_registrotreinamento_descricao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimento",
            name="area_conhecimento",
            field=models.CharField(
                blank=True,
                help_text="Área de conhecimento do procedimento para classificação de treinamentos",
                max_length=200,
                null=True,
                verbose_name="Área de Conhecimento",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="area_conhecimento",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Área de Conhecimento",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="carga_horaria",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Carga Horária (hh:mm)",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="categoria_comunicacao",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Categoria - Forma de Comunicação",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="custo_treinamento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Custo do Treinamento (R$ por pessoa)",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="data_final_treinamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Final do Treinamento"
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="data_limite_avaliacao_eficacia",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data Limite para Avaliação de Eficácia",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="facilitador_fornecedor",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nome do Facilitador ou Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="mes_referencia",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mês de Referência"
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="metodologia_treinamento",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Metodologia de Treinamento",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="necessita_avaliacao_eficacia",
            field=models.BooleanField(
                default=False, verbose_name="Necessidade de Avaliação de Eficácia"
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="resultado_avaliacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Resultado da Avaliação"
            ),
        ),
    ]
