# Generated by Django 5.0.14 on 2025-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0011_procedimento_area_conhecimento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrotreinamento",
            name="revisao_treinada",
            field=models.CharField(blank=True, default="01", max_length=10, null=True),
        ),
    ]
