# Generated by Django 5.0.14 on 2025-12-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0012_alter_registrotreinamento_revisao_treinada"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="instrutor_nome",
            field=models.CharField(
                blank=True,
                help_text="Digite o nome do instrutor. Será vinculado automaticamente se encontrado na base.",
                max_length=200,
                null=True,
                verbose_name="Nome do Instrutor (Texto Livre)",
            ),
        ),
        migrations.AddField(
            model_name="registrotreinamento",
            name="colaborador_nome",
            field=models.CharField(
                blank=True,
                help_text="Digite o nome do colaborador. Será vinculado automaticamente se encontrado na base.",
                max_length=200,
                null=True,
                verbose_name="Nome do Colaborador (Texto Livre)",
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="instrutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listas_presenca_como_instrutor",
                to="rh.colaborador",
                verbose_name="Instrutor (Base de Dados)",
            ),
        ),
        migrations.AlterField(
            model_name="registrotreinamento",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treinamentos",
                to="rh.colaborador",
                verbose_name="Colaborador (Base de Dados)",
            ),
        ),
    ]
