# Generated by Django 5.0.14 on 2025-12-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0013_add_flexible_names"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColaboradorMatrizHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_atribuicao",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atribuição"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrizes_habilidade",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboradores",
                        to="procedures.matrizhabilidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador em Matriz de Habilidade",
                "verbose_name_plural": "Colaboradores em Matrizes de Habilidade",
                "ordering": ["colaborador__nome_completo"],
                "unique_together": {("colaborador", "matriz")},
            },
        ),
    ]
