# Generated by Django 5.0.14 on 2025-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0014_colaboradormatrizhabilidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaohabilidade",
            name="nivel",
            field=models.IntegerField(
                choices=[
                    (-1, "N/A - Não se Aplica"),
                    (0, "0 - Há Intenção de Treinar"),
                    (1, "1 - Colaborador em Treinamento"),
                    (2, "2 - Treinado"),
                    (3, "3 - Treinado na Plataforma LOFT"),
                ],
                default=0,
                verbose_name="Nível de Competência",
            ),
        ),
    ]
