# Generated by Django 5.0.14 on 2025-12-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0015_alter_avaliacaohabilidade_nivel"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAvaliacaoHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_anterior",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nível Anterior"
                    ),
                ),
                ("nivel_novo", models.IntegerField(verbose_name="Nível Novo")),
                (
                    "data_avaliacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data da Avaliação (anterior)",
                    ),
                ),
                (
                    "data_avaliacao_nova",
                    models.DateField(verbose_name="Data da Avaliação (nova)"),
                ),
                (
                    "observacoes_anterior",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Anteriores"
                    ),
                ),
                (
                    "observacoes_nova",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Novas"
                    ),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora da Alteração"
                    ),
                ),
                (
                    "tipo_alteracao",
                    models.CharField(
                        choices=[
                            ("criacao", "Criação"),
                            ("atualizacao", "Atualização"),
                        ],
                        default="atualizacao",
                        max_length=20,
                        verbose_name="Tipo de Alteração",
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="procedures.avaliacaohabilidade",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_avaliacoes",
                        to="rh.colaborador",
                        verbose_name="Avaliador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Avaliação de Habilidade",
                "verbose_name_plural": "Históricos de Avaliações de Habilidades",
                "ordering": ["-alterado_em"],
            },
        ),
    ]
