# Generated by Django 5.0.14 on 2025-12-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0016_historicoavaliacaohabilidade"),
        ("rh", "0014_colaborador_pacotes_treinamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoValidacaoMassa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_avaliacoes",
                    models.IntegerField(verbose_name="Total de Avaliações"),
                ),
                (
                    "avaliacoes_atualizadas",
                    models.IntegerField(verbose_name="Avaliações Atualizadas"),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                ("executado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacoes_massa",
                        to="procedures.matrizhabilidade",
                    ),
                ),
                (
                    "validador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validacoes_massa_realizadas",
                        to="rh.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Validação em Massa",
                "verbose_name_plural": "Históricos de Validação em Massa",
                "ordering": ["-executado_em"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoValidacaoMatriz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("validada", "Validada"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("motivo_solicitacao", models.TextField(blank=True, null=True)),
                ("motivo_rejeicao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("validado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacoes_solicitadas",
                        to="procedures.matrizhabilidade",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validacoes_solicitadas",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "validador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validacoes_para_fazer",
                        to="rh.colaborador",
                        verbose_name="Designado para Validar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Validação de Matriz",
                "verbose_name_plural": "Solicitações de Validação de Matrizes",
                "ordering": ["-criado_em"],
            },
        ),
    ]
