# Generated by Django 5.0.14 on 2025-12-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0017_historicovalidacaomassa_solicitacaovalidacaomatriz"),
    ]

    operations = [
        migrations.AddField(
            model_name="planejamentotreinamento",
            name="disciplina",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido automaticamente quando origem é MATRIZ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planejamentos",
                to="procedures.disciplina",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AddField(
            model_name="planejamentotreinamento",
            name="origem",
            field=models.CharField(
                choices=[
                    ("DEMANDA", "Demanda Existente"),
                    ("MATRIZ", "Matriz de Habilidades"),
                    ("LIVRE", "Planejamento Livre"),
                ],
                default="LIVRE",
                max_length=20,
                verbose_name="Origem/Tipo de Planejamento",
            ),
        ),
        migrations.AlterField(
            model_name="planejamentotreinamento",
            name="procedimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planejamentos",
                to="procedures.procedimento",
                verbose_name="Procedimento",
            ),
        ),
        migrations.CreateModel(
            name="DisciplinaProcedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obrigatorio",
                    models.BooleanField(
                        default=True,
                        help_text="Se o procedimento é obrigatório para esta disciplina",
                        verbose_name="Obrigatório",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de execução do procedimento",
                        verbose_name="Ordem",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedimentos_associados",
                        to="procedures.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinas_associadas",
                        to="procedures.procedimento",
                        verbose_name="Procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associação Disciplina-Procedimento",
                "verbose_name_plural": "Associações Disciplina-Procedimento",
                "ordering": ["disciplina", "ordem"],
                "unique_together": {("disciplina", "procedimento")},
            },
        ),
    ]
