# Generated by Django 5.0.14 on 2025-12-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0018_planejamentotreinamento_disciplina_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planejamentotreinamento",
            name="procedimento",
        ),
        migrations.AddField(
            model_name="planejamentotreinamento",
            name="procedimentos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Procedimentos incluídos neste planejamento",
                related_name="planejamentos",
                to="procedures.procedimento",
                verbose_name="Procedimentos",
            ),
        ),
    ]
