# Generated by Django 5.0.14 on 2026-01-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0019_planejamento_multiplos_procedimentos"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Template"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_arquivo",
                    models.CharField(
                        choices=[
                            ("docx", "Word (.docx)"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel (.xlsx)"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="templates_lista_presenca/",
                        verbose_name="Arquivo Template",
                    ),
                ),
                (
                    "tem_cabecalho",
                    models.BooleanField(
                        default=True, verbose_name="Tem Cabeçalho na 1ª Página?"
                    ),
                ),
                (
                    "tem_listagem_procedimentos",
                    models.BooleanField(
                        default=True, verbose_name="Tem Listagem de Procedimentos?"
                    ),
                ),
                (
                    "num_paginas",
                    models.IntegerField(
                        default=2, verbose_name="Número de Páginas Esperadas"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Template Ativo?"),
                ),
            ],
            options={
                "verbose_name": "Template de Lista de Presença",
                "verbose_name_plural": "Templates de Listas de Presença",
                "ordering": ["-ativo", "-atualizado_em"],
            },
        ),
        migrations.CreateModel(
            name="MapeamentoCampoListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_campo",
                    models.CharField(
                        choices=[
                            ("titulo_treinamento", "Título do Treinamento"),
                            ("data", "Data"),
                            ("hora_inicio", "Hora de Início"),
                            ("hora_fim", "Hora de Fim"),
                            ("instrutor", "Instrutor"),
                            ("local", "Local"),
                            ("carga_horaria", "Carga Horária"),
                            ("objetivo", "Objetivo"),
                            ("publico_alvo", "Público-alvo"),
                            ("assinatura_instrutor", "Assinatura do Instrutor"),
                            ("empresa", "Empresa"),
                            ("departamento", "Departamento"),
                            ("numero_participantes", "Número de Participantes"),
                            ("outro", "Outro (Texto Livre)"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Campo",
                    ),
                ),
                ("pagina", models.IntegerField(verbose_name="Página")),
                (
                    "localizacao_descrita",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Localização Descrita (ex: Linha 3, Coluna 5)",
                    ),
                ),
                (
                    "valor_padrao",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Valor Padrão (para campos 'Outro')",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeamentos",
                        to="procedures.templatelistapresenca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Campo",
                "verbose_name_plural": "Mapeamentos de Campos",
                "ordering": ["pagina", "tipo_campo"],
                "unique_together": {("template", "tipo_campo")},
            },
        ),
    ]
