# Generated by Django 5.0.14 on 2026-01-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0020_templatelistapresenca_mapeamentocampolistapresenca"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="arquivo_assinado",
            field=models.FileField(
                blank=True,
                help_text="Upload da lista de presença assinada pelos participantes",
                null=True,
                upload_to="listas_presenca_assinadas/",
                verbose_name="Arquivo Assinado (PDF/Imagem)",
            ),
        ),
        migrations.AddField(
            model_name="listapresenca",
            name="data_upload_assinado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Upload"
            ),
        ),
    ]
