# Generated by Django 5.0.14 on 2026-01-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0021_listapresenca_arquivo_assinado_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapeamentocampolistapresenca",
            options={
                "ordering": ["tipo_campo"],
                "verbose_name": "Mapeamento de Campo",
                "verbose_name_plural": "Mapeamentos de Campos",
            },
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="localizacao",
            field=models.CharField(
                default="A1",
                help_text="Referência de célula (ex: A1) ou coordenadas (ex: 100,50)",
                max_length=50,
                verbose_name="Localização (A1 ou x,y)",
            ),
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("clique", "Clique na Célula"),
                    ("referencia", "Referência de Célula (A1, B2)"),
                ],
                default="referencia",
                max_length=20,
                verbose_name="Método de Mapeamento para Este Campo",
            ),
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="obrigatorio",
            field=models.BooleanField(
                default=True,
                help_text="Se deve ser validado se está mapeado",
                verbose_name="Campo Obrigatório?",
            ),
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="permite_imagem_marcacao",
            field=models.BooleanField(
                default=False,
                help_text="Se este campo pode ser preenchido por imagem ou marcação",
                verbose_name="Permite Imagem/Marcação?",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="arquivo_excel_template",
            field=models.FileField(
                blank=True,
                help_text="Upload do Excel em branco que será mapeado",
                null=True,
                upload_to="templates_excel_mapeamento/",
                verbose_name="Arquivo Excel para Mapeamento",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="mapeamento_campos",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON com as posições dos campos mapeadas",
                verbose_name="Mapeamento de Campos Configurado",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="mapeamento_completo",
            field=models.BooleanField(
                default=False,
                help_text="Todos os campos obrigatórios foram mapeados?",
                verbose_name="Mapeamento Completo?",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="metodo_mapeamento",
            field=models.CharField(
                choices=[
                    ("clique", "Clique na Célula"),
                    ("referencia", "Referência de Célula (A1, B2, etc)"),
                    ("ambos", "Ambos - Admin Escolhe por Campo"),
                ],
                default="ambos",
                help_text="Como o admin vai definir as posições dos campos",
                max_length=20,
                verbose_name="Método de Mapeamento",
            ),
        ),
        migrations.AlterField(
            model_name="mapeamentocampolistapresenca",
            name="pagina",
            field=models.IntegerField(default=1, verbose_name="Página"),
        ),
        migrations.AlterField(
            model_name="mapeamentocampolistapresenca",
            name="tipo_campo",
            field=models.CharField(
                choices=[
                    ("titulo_treinamento", "Título do Treinamento"),
                    ("categoria_treinamento", "Categoria do Treinamento"),
                    ("metodologia", "Metodologia"),
                    ("area_conhecimento", "Área de Conhecimento"),
                    ("necessita_avaliacao", "Necessita de Avaliação"),
                    ("facilitador_fornecedor", "Nome do Facilitador ou Fornecedor"),
                    ("data_hora", "Data e Hora"),
                    ("carga_horaria", "Carga Horária"),
                    ("procedimentos_assuntos", "Procedimentos/Assuntos/Temas"),
                    ("hora_inicio", "Hora de Início"),
                    ("hora_fim", "Hora de Fim"),
                    ("instrutor", "Instrutor"),
                    ("local", "Local"),
                    ("objetivo", "Objetivo"),
                    ("publico_alvo", "Público-alvo"),
                    ("assinatura_instrutor", "Assinatura do Instrutor"),
                    ("empresa", "Empresa"),
                    ("departamento", "Departamento"),
                    ("numero_participantes", "Número de Participantes"),
                    ("outro", "Outro (Texto Livre)"),
                ],
                max_length=50,
                verbose_name="Tipo de Campo",
            ),
        ),
    ]
