# Generated by Django 5.0.14 on 2026-01-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0022_alter_mapeamentocampolistapresenca_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template Excel que define o layout e colunas dessa lista de presença",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listas_presenca",
                to="procedures.templatelistapresenca",
                verbose_name="Template de Layout",
            ),
        ),
    ]
