# Generated by Django 5.0.14 on 2026-01-05 12:46

from django.db import migrations, models


def clear_old_data(apps, schema_editor):
    """Limpar dados antigos antes de aplicar constraints"""
    MapeamentoCampoListaPresenca = apps.get_model('procedures', 'MapeamentoCampoListaPresenca')
    # Deletar todos os mapeamentos antigos que têm placeholder vazio
    MapeamentoCampoListaPresenca.objects.filter(placeholder='').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0023_listapresenca_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapeamentocampolistapresenca",
            options={
                "ordering": ["placeholder"],
                "verbose_name": "Mapeamento de Placeholder",
                "verbose_name_plural": "Mapeamentos de Placeholders",
            },
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="arquivo",
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="arquivo_excel_template",
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="mapeamento_campos",
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="metodo_mapeamento",
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="num_paginas",
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="tem_cabecalho",
        ),
        migrations.RemoveField(
            model_name="templatelistapresenca",
            name="tem_listagem_procedimentos",
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="campo_dados",
            field=models.CharField(
                blank=True,
                choices=[
                    ("titulo", "Título do Treinamento"),
                    ("facilitador", "Facilitador/Fornecedor"),
                    ("data", "Data"),
                    ("hora_inicio", "Hora de Início"),
                    ("hora_fim", "Hora de Fim"),
                    ("carga_horaria", "Carga Horária"),
                    ("local", "Local"),
                    ("procedimentos", "Procedimentos/Assuntos"),
                    ("empresa", "Empresa"),
                    ("departamento", "Departamento"),
                    ("instrutoria", "Instrutoria"),
                    ("observacoes", "Observações"),
                ],
                help_text="Qual campo da lista de presença alimentará este placeholder",
                max_length=50,
                null=True,
                verbose_name="Campo de Dados",
            ),
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="formato",
            field=models.CharField(
                blank=True,
                help_text="Ex: dd/mm/yyyy para datas, moeda para valores, etc",
                max_length=100,
                null=True,
                verbose_name="Formato de Exibição",
            ),
        ),
        migrations.AddField(
            model_name="mapeamentocampolistapresenca",
            name="placeholder",
            field=models.CharField(
                default="",
                help_text="Placeholder exato encontrado no PDF (ex: {{titulo}})",
                max_length=100,
                verbose_name="Placeholder",
            ),
        ),
        migrations.RunPython(clear_old_data),
        migrations.AlterUniqueTogether(
            name="mapeamentocampolistapresenca",
            unique_together={("template", "placeholder")},
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="arquivo_pdf_template",
            field=models.FileField(
                blank=True,
                help_text="PDF base com placeholders como {{titulo}}, {{data_hora}}, {{facilitador}}, etc.",
                null=True,
                upload_to="templates_pdf_lista_presenca/",
                verbose_name="Arquivo PDF Template",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="num_linhas_assinatura",
            field=models.IntegerField(
                default=20,
                help_text="Quantas linhas de participantes caberão na página de assinatura",
                verbose_name="Número de Linhas para Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="placeholders_mapeados",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dicionário com placeholder → label",
                verbose_name="Placeholders Mapeados",
            ),
        ),
        migrations.AddField(
            model_name="templatelistapresenca",
            name="tem_pagina_assinatura",
            field=models.BooleanField(
                default=True,
                help_text="Se sim, será adicionada página extra para assinaturas",
                verbose_name="Tem Página de Assinatura?",
            ),
        ),
        migrations.AlterField(
            model_name="mapeamentocampolistapresenca",
            name="obrigatorio",
            field=models.BooleanField(
                default=True,
                help_text="Se deve ser validado se está preenchido",
                verbose_name="Campo Obrigatório?",
            ),
        ),
        migrations.AlterField(
            model_name="templatelistapresenca",
            name="tipo_arquivo",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("docx", "Word (.docx)")],
                default="pdf",
                max_length=10,
                verbose_name="Tipo de Arquivo",
            ),
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="localizacao",
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="localizacao_descrita",
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="metodo",
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="pagina",
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="permite_imagem_marcacao",
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="tipo_campo",
        ),
        migrations.RemoveField(
            model_name="mapeamentocampolistapresenca",
            name="valor_padrao",
        ),
    ]
