# Generated by Django 5.0.14 on 2026-01-05 17:02

from django.db import migrations, models


def clean_duplicates(apps, schema_editor):
    """
    Limpar dados duplicados/vazios que violam constraint UNIQUE
    Mantém apenas o primeiro de cada (template_id, placeholder)
    """
    MapeamentoCampoListaPresenca = apps.get_model('procedures', 'MapeamentoCampoListaPresenca')
    
    # Deletar registros com placeholder vazio
    vazios = MapeamentoCampoListaPresenca.objects.filter(placeholder='')
    if vazios.exists():
        count = vazios.count()
        vazios.delete()
        print(f"[OK] Deletados {count} registros com placeholder vazio")
    
    # Encontrar e remover duplicatas
    mapeamentos = MapeamentoCampoListaPresenca.objects.all().order_by('template_id', 'placeholder', 'id')
    
    seen_keys = set()
    ids_to_delete = []
    
    for m in mapeamentos:
        key = (m.template_id, m.placeholder)
        if key in seen_keys:
            ids_to_delete.append(m.id)
        else:
            seen_keys.add(key)
    
    if ids_to_delete:
        count = len(ids_to_delete)
        MapeamentoCampoListaPresenca.objects.filter(id__in=ids_to_delete).delete()
        print(f"[OK] Deletados {count} registros duplicados")
    
    print("[OK] Limpeza de dados concluída!")


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0024_refactor_template_to_pdf_placeholders"),
    ]

    operations = [
        migrations.RunPython(clean_duplicates, migrations.RunPython.noop),
    ]
