# Generated by Django 5.0.14 on 2026-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0025_clean_duplicate_placeholders"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimento",
            name="criticidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAIXA", "Baixa"),
                    ("MÉDIA", "Média"),
                    ("ALTA", "Alta"),
                    ("CRÍTICA", "Crítica"),
                ],
                help_text="Nível de criticidade do procedimento",
                max_length=20,
                null=True,
                verbose_name="Criticidade",
            ),
        ),
    ]
