# Generated by Django 5.0.14 on 2026-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0026_add_criticidade_to_procedimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedimento",
            name="criticidade",
            field=models.CharField(
                blank=True,
                choices=[("CRITICO", "Crítico"), ("NAO_CRITICO", "Não Crítico")],
                help_text="Nível de criticidade do procedimento",
                max_length=20,
                null=True,
                verbose_name="Criticidade",
            ),
        ),
    ]
