# Generated by Django 5.0.14 on 2026-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0028_registrotreinamento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentotreinamento',
            name='horario_previsto',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Previsto para Começar'),
        ),
    ]
