# Generated by Django 5.0.14 on 2026-01-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0029_planejamentotreinamento_horario_previsto'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrotreinamento',
            unique_together={('colaborador', 'procedimento', 'data_treinamento')},
        ),
    ]
