# Generated by Django 5.0.14 on 2026-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0030_allow_multiple_procedimento_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentotreinamento',
            name='status',
            field=models.CharField(choices=[('PLANEJADO', 'Planejado'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('ATRASADO', 'Atrasado')], default='PLANEJADO', max_length=20, verbose_name='Status'),
        ),
    ]
