# Generated by Django 5.0.14 on 2026-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0031_alter_planejamentotreinamento_status'),
        ('rh', '0017_colaborador_afastado_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['criticidade'], name='proc_criticidade_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['matriz'], name='proc_matriz_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['sub_area'], name='proc_sub_area_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotreinamento',
            index=models.Index(fields=['ativo', 'data_treinamento'], name='regtrein_ativo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotreinamento',
            index=models.Index(fields=['ativo', 'colaborador', 'procedimento'], name='regtrein_ativo_col_proc_idx'),
        ),
    ]
