# Generated by Django 5.0.14 on 2026-03-12 00:00

from django.db import migrations, models
import django.db.models.deletion


def popular_matrizes_e_subareas(apps, schema_editor):
    Procedimento = apps.get_model('procedures', 'Procedimento')
    MatrizProcedimento = apps.get_model('procedures', 'MatrizProcedimento')
    SubAreaProcedimento = apps.get_model('procedures', 'SubAreaProcedimento')

    matrizes_por_nome = {}

    for nome_matriz in Procedimento.objects.exclude(matriz__isnull=True).exclude(matriz__exact='').values_list('matriz', flat=True).distinct():
        matriz_obj, _ = MatrizProcedimento.objects.get_or_create(nome=nome_matriz)
        matrizes_por_nome[nome_matriz] = matriz_obj

    for proc in Procedimento.objects.exclude(sub_area__isnull=True).exclude(sub_area__exact='').only('matriz', 'sub_area'):
        nome_matriz = (proc.matriz or '').strip()
        if not nome_matriz:
            continue

        matriz_obj = matrizes_por_nome.get(nome_matriz)
        if not matriz_obj:
            matriz_obj, _ = MatrizProcedimento.objects.get_or_create(nome=nome_matriz)
            matrizes_por_nome[nome_matriz] = matriz_obj

        SubAreaProcedimento.objects.get_or_create(
            matriz=matriz_obj,
            nome=proc.sub_area,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0032_procedimento_proc_criticidade_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome da Matriz')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matriz de Procedimento',
                'verbose_name_plural': 'Matrizes de Procedimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SubAreaProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Sub-Área')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='procedures.matrizprocedimento', verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'Sub-Área de Procedimento',
                'verbose_name_plural': 'Sub-Áreas de Procedimentos',
                'ordering': ['matriz__nome', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'nome'), name='uniq_subarea_procedimento_por_matriz')],
            },
        ),
        migrations.RunPython(popular_matrizes_e_subareas, migrations.RunPython.noop),
    ]
