# Generated by Django 5.0.14 on 2026-05-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0033_matrizprocedimento_subareaprocedimento"),
        ("rh", "0018_colaborador_rh_colaborador_turno_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsavelTreinamentoMatriz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrativo"),
                            ("TURNO_1", "Turno 1"),
                            ("TURNO_2", "Turno 2"),
                            ("TURNO_3", "Turno 3"),
                            ("12X36", "12x36"),
                        ],
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsabilidades_treinamento",
                        to="rh.colaborador",
                        verbose_name="Colaborador Responsável",
                    ),
                ),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsaveis_treinamento",
                        to="procedures.matrizprocedimento",
                        verbose_name="Matriz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável de Treinamento por Matriz",
                "verbose_name_plural": "Responsáveis de Treinamento por Matriz",
                "ordering": ["matriz__nome", "turno"],
                "indexes": [
                    models.Index(fields=["turno"], name="resp_trein_matriz_turno_idx"),
                    models.Index(
                        fields=["colaborador"], name="resp_trein_matriz_colab_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="responsaveltreinamentomatriz",
            constraint=models.UniqueConstraint(
                fields=("matriz", "turno"),
                name="uniq_responsavel_treinamento_por_matriz_turno",
            ),
        ),
    ]
