# Generated by Django 5.0.14 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0034_responsaveltreinamentomatriz_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="responsaveltreinamentomatriz",
            options={
                "verbose_name": "Responsável de Treinamento por Matriz/Sub-Área",
                "verbose_name_plural": "Responsáveis de Treinamento por Matriz/Sub-Área",
                "ordering": ["matriz__nome", "sub_area__nome", "turno"],
            },
        ),
        migrations.AddField(
            model_name="responsaveltreinamentomatriz",
            name="sub_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsaveis_treinamento",
                to="procedures.subareaprocedimento",
                verbose_name="Sub-Área",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="responsaveltreinamentomatriz",
            name="uniq_responsavel_treinamento_por_matriz_turno",
        ),
        migrations.AddConstraint(
            model_name="responsaveltreinamentomatriz",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_area__isnull", True)),
                fields=("matriz", "turno"),
                name="uniq_resp_trein_matriz_turno_geral",
            ),
        ),
        migrations.AddConstraint(
            model_name="responsaveltreinamentomatriz",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_area__isnull", False)),
                fields=("matriz", "sub_area", "turno"),
                name="uniq_resp_trein_subarea_turno",
            ),
        ),
        migrations.AddIndex(
            model_name="responsaveltreinamentomatriz",
            index=models.Index(fields=["sub_area"], name="resp_trein_subarea_idx"),
        ),
    ]
