# Generated by Django 5.0.14 on 2026-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0035_responsaveltreinamento_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentotreinamento',
            name='horario_previsto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário Previsto para Começar'),
        ),
    ]
