# Generated by Django 5.0.14 on 2026-06-25 11:26

from django.db import migrations, models


def migrate_time_to_datetime(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                'ALTER TABLE procedures_planejamentotreinamento '
                'ALTER COLUMN horario_previsto TYPE timestamp with time zone '
                'USING (data_prevista + horario_previsto);'
            )

def reverse_time_to_datetime(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                'ALTER TABLE procedures_planejamentotreinamento '
                'ALTER COLUMN horario_previsto TYPE time without time zone '
                'USING horario_previsto::time;'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0035_responsaveltreinamento_subarea'),
    ]

    operations = [
        migrations.RunPython(migrate_time_to_datetime, reverse_code=reverse_time_to_datetime),
        migrations.AlterField(
            model_name='planejamentotreinamento',
            name='horario_previsto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário Previsto para Começar'),
        ),
    ]
