# Generated by Django 5.0.14 on 2026-07-01 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0036_alter_planejamentotreinamento_horario_previsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentotreinamento',
            name='origem',
            field=models.CharField(choices=[('DEMANDA', 'Demanda Existente'), ('MATRIZ', 'Matriz de Habilidades'), ('LIVRE', 'Planejamento Livre'), ('INTEGRACAO', 'Integração')], default='LIVRE', max_length=20, verbose_name='Origem/Tipo de Planejamento'),
        ),
        migrations.CreateModel(
            name='PacoteIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_integracao', to='procedures.perfiltreinamento', verbose_name='Perfil de Treinamento')),
                ('procedimentos', models.ManyToManyField(related_name='pacotes_integracao', to='procedures.procedimento', verbose_name='Procedimentos de Integração')),
            ],
            options={
                'verbose_name': 'Pacote de Integração',
                'verbose_name_plural': 'Pacotes de Integração',
            },
        ),
    ]
