# Generated by Django 5.0.14 on 2026-07-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0037_alter_planejamentotreinamento_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacoteintegracao',
            name='nome',
            field=models.CharField(default='Integração Geral', max_length=100, verbose_name='Nome do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacoteintegracao',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_integracao', to='procedures.perfiltreinamento', verbose_name='Perfil de Treinamento'),
        ),
    ]
