# Generated by Django 5.0.14 on 2026-07-09 12:19

from django.db import migrations, models


def populate_avaliacao_eficacia(apps, schema_editor):
    RegistroTreinamento = apps.get_model('procedures', 'RegistroTreinamento')
    import datetime
    
    # Fetch all RegistroTreinamento with critical procedures
    # In historical models, relationships can be traversed normally.
    for t in RegistroTreinamento.objects.filter(procedimento__criticidade='CRITICO'):
        t.necessita_avaliacao_eficacia = True
        if t.data_treinamento and not t.data_limite_avaliacao_eficacia:
            t.data_limite_avaliacao_eficacia = t.data_treinamento + datetime.timedelta(days=30)
        
        if not t.avaliacao_eficacia_status:
            if t.resultado_avaliacao:
                t.avaliacao_eficacia_status = 'EFICAZ'
            else:
                t.avaliacao_eficacia_status = 'PENDENTE'
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0038_pacoteintegracao_nome_alter_pacoteintegracao_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotreinamento',
            name='avaliacao_eficacia_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Avaliação de Eficácia'),
        ),
        migrations.AddField(
            model_name='registrotreinamento',
            name='avaliacao_eficacia_status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('EFICAZ', 'Eficaz'), ('INEFICAZ', 'Ineficaz')], help_text='Status da avaliação de eficácia para procedimentos críticos', max_length=20, null=True, verbose_name='Status da Avaliação de Eficácia'),
        ),
        migrations.RunPython(populate_avaliacao_eficacia, reverse_code=migrations.RunPython.noop),
    ]
