# Generated by Django 5.0.14 on 2026-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0039_registrotreinamento_avaliacao_eficacia_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotreinamento',
            name='avaliacao_eficacia_status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('EFICAZ', 'Eficaz'), ('INEFICAZ', 'Ineficaz'), ('NAO_APLICA', 'Não se Aplica')], help_text='Status da avaliação de eficácia para procedimentos críticos', max_length=20, null=True, verbose_name='Status da Avaliação de Eficácia'),
        ),
    ]
