# Generated by Django 5.0.14 on 2026-08-27 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0040_alter_registrotreinamento_avaliacao_eficacia_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumentoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('LISTA_PRESENCA', 'Lista de Presença (Excel/Word/PDF)'), ('AVALIACAO_EFICACIA', 'Avaliação de Eficácia de Treinamento'), ('CERTIFICADO', 'Certificado de Conclusão'), ('INTEGRACAO', 'Checklist de Integração'), ('OUTROS', 'Outros Templates e Formulários')], default='LISTA_PRESENCA', max_length=50, verbose_name='Função / Finalidade')),
                ('codigo', models.CharField(help_text='Ex: FOR.033.r07, FOR.143, etc.', max_length=50, verbose_name='Código do Formulário')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Instruções')),
                ('tipo_arquivo', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)'), ('pdf', 'PDF (.pdf)')], default='xlsx', max_length=10, verbose_name='Tipo de Arquivo')),
                ('arquivo', models.FileField(upload_to='templates_treinamento_docs/', verbose_name='Arquivo do Template')),
                ('ativo', models.BooleanField(default=True, help_text='Se ativado, será o template utilizado automaticamente na geração deste tipo de documento', verbose_name='Template Padrão/Ativo?')),
                ('tags_disponiveis', models.TextField(blank=True, help_text='Lista explicativa de tags dinâmicas aceitas neste template', null=True, verbose_name='Tags Suportadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_treinamento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Documento de Treinamento',
                'verbose_name_plural': 'Configuração de Templates de Treinamentos',
                'ordering': ['funcao', '-ativo', '-atualizado_em'],
            },
        ),
    ]
