# Generated by Django 5.0.14 on 2026-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0041_templatedocumentotreinamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocumentotreinamento',
            name='arquivo_base64',
            field=models.TextField(blank=True, default='', help_text='Persistência em banco de dados para compatibilidade serverless / nuvem', verbose_name='Conteúdo em Base64'),
        ),
        migrations.AddField(
            model_name='templatedocumentotreinamento',
            name='nome_arquivo_original',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome Original do Arquivo'),
        ),
        migrations.AlterField(
            model_name='templatedocumentotreinamento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='templates_treinamento_docs/', verbose_name='Arquivo do Template'),
        ),
    ]
