# Generated by Django 5.0.14 on 2026-08-31 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0044_set_default_nao_critico_procedimentos'),
        ('rh', '0030_demandafalhaponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotreinamento',
            name='gestor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Gestor customizado responsável pela avaliação de eficácia deste treinamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos_avaliados_gestor', to='rh.colaborador', verbose_name='Gestor / Avaliador Responsável'),
        ),
    ]
