# Generated by Django 5.0.14 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0045_registrotreinamento_gestor_responsavel'),
        ('rh', '0030_demandafalhaponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='instrutor_fixo',
            field=models.ForeignKey(
                blank=True,
                help_text='Se definido, este colaborador será sempre o instrutor responsável por este procedimento, ignorando liderança/matriz de setor.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='procedimentos_instrutor_fixo',
                to='rh.colaborador',
                verbose_name='Instrutor Fixo (Independente do Setor)',
            ),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['instrutor_fixo'], name='proc_instrutor_fixo_idx'),
        ),
    ]
