# Generated by Django 5.0.14 on 2026-10-02 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0046_procedimento_instrutor_fixo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Identificador único no QMS. Ex: DOC.071-FLX-001', max_length=60, unique=True, verbose_name='Código Documental')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Processo')),
                ('departamento', models.CharField(max_length=120, verbose_name='Departamento/Área')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Objetivo do Fluxo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagramas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Elaborador')),
                ('matriz_procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_associados', to='procedures.matrizprocedimento', verbose_name='Matriz de Procedimento')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_fluxo', to='procedures.procedimento', verbose_name='Procedimento Operacional Vinculado')),
            ],
            options={
                'verbose_name': 'Diagrama de Processo',
                'verbose_name_plural': 'Diagramas de Processos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DiagramaVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revisao', models.PositiveIntegerField(default=0, help_text='0 para R00, 1 para R01, etc.', verbose_name='Número da Revisão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADO', 'Aprovado'), ('OBSOLETO', 'Obsoleto')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status da Revisão')),
                ('dados_topologia', models.JSONField(blank=True, default=dict, help_text="Armazena { 'nodes': [...], 'edges': [...], 'grid_data': [...] }", verbose_name='Topologia do Grafo (xyflow JSON)')),
                ('motivo_revisao', models.TextField(blank=True, null=True, verbose_name='Motivo da Revisão / Alteração')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Aprovação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagramas_revisoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='procedures.diagrama', verbose_name='Diagrama Principal')),
            ],
            options={
                'verbose_name': 'Versão de Diagrama',
                'verbose_name_plural': 'Versões de Diagramas',
                'ordering': ['-revisao'],
                'indexes': [models.Index(fields=['diagrama', 'status'], name='procedures__diagram_d7b741_idx')],
                'unique_together': {('diagrama', 'revisao')},
            },
        ),
    ]
