# Generated by Django 5.0.14 on 2026-10-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0047_diagrama_diagramaversao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagrama',
            options={'ordering': ['numero', 'titulo'], 'verbose_name': 'Diagrama de Processo', 'verbose_name_plural': 'Diagramas de Processos'},
        ),
        migrations.AddField(
            model_name='diagrama',
            name='numero',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Numeração sequencial do diagrama (#001, #002...)', null=True, unique=True, verbose_name='Número do Diagrama'),
        ),
        migrations.AlterField(
            model_name='diagrama',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código opcional para identificação adicional', max_length=60, null=True, verbose_name='Código Documental / Referência'),
        ),
        migrations.AlterField(
            model_name='diagrama',
            name='departamento',
            field=models.CharField(default='Metrologia', max_length=120, verbose_name='Departamento/Área'),
        ),
        migrations.AlterField(
            model_name='diagrama',
            name='matriz_procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_associados', to='procedures.matrizprocedimento', verbose_name='Matriz de Procedimento (Opcional)'),
        ),
        migrations.AlterField(
            model_name='diagrama',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_fluxo', to='procedures.procedimento', verbose_name='Procedimento Vinculado (Opcional)'),
        ),
    ]
