# Generated by Django 5.0.14 on 2026-10-07 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0048_alter_diagrama_options_diagrama_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramaversao',
            name='data_submissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Submissão'),
        ),
        migrations.AddField(
            model_name='diagramaversao',
            name='motivo_devolucao',
            field=models.TextField(blank=True, help_text='Justificativa do aprovador quando a revisão é devolvida ao elaborador.', null=True, verbose_name='Motivo da Última Devolução'),
        ),
        migrations.AddField(
            model_name='diagramaversao',
            name='submetido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagramas_revisoes_submetidas', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por'),
        ),
    ]
