# Generated by Django 5.0.14 on 2026-10-08 17:39

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_unidade'),
        ('procedures', '0049_diagramaversao_submissao_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Raia')),
                ('cor', models.CharField(default='#334155', max_length=7, verbose_name='Cor da faixa')),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem padrão')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(blank=True, help_text='Colaboradores desse setor caem automaticamente nesta raia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raias_diagramas', to='organization.setor', verbose_name='Setor vinculado (RH)')),
            ],
            options={
                'verbose_name': 'Raia de Diagrama',
                'verbose_name_plural': 'Raias de Diagramas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='raiacatalogo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='uniq_raia_catalogo_nome_ci'),
        ),
    ]
