# Generated by Django 5.0.14 on 2026-10-08 19:09

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0050_raiacatalogo_raiacatalogo_uniq_raia_catalogo_nome_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaDiagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do tema')),
                ('definicao', models.JSONField(default=dict, verbose_name='Definição do tema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_diagramas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tema de Diagrama',
                'verbose_name_plural': 'Temas de Diagramas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='temadiagrama',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='uniq_tema_diagrama_nome_ci'),
        ),
    ]
