# Generated by Django 5.0.14 on 2026-10-08 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0051_tema_diagrama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemDiagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('content_type', models.CharField(max_length=40)),
                ('dados', models.BinaryField()),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_diagramas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem de Diagrama',
                'verbose_name_plural': 'Imagens de Diagramas',
            },
        ),
    ]
