# Generated by Django 5.0.14 on 2025-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoCarimbo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("posicao_x", models.FloatField(help_text="Posição X em mm")),
                ("posicao_y", models.FloatField(help_text="Posição Y em mm")),
                ("tamanho_fonte", models.IntegerField(default=12)),
                (
                    "formato_data",
                    models.CharField(
                        default="%d/%m/%Y", help_text="Formato strftime", max_length=50
                    ),
                ),
                ("texto_customizado", models.TextField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Configuração de Carimbo",
                "verbose_name_plural": "Configurações de Carimbo",
            },
        ),
        migrations.CreateModel(
            name="DocumentoGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=50, verbose_name="Tipo de Documento"),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("arquivo", models.FileField(upload_to="documentos_gerados/")),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Documento Gerado",
                "verbose_name_plural": "Documentos Gerados",
                "ordering": ["-data_geracao"],
            },
        ),
    ]
