from django.urls import path
from . import views

urlpatterns = [
    # Application module routes
    path("metrologia/", views.modulo_metrologia_view, name="modulo_metrologia"),
    path("instrumento/<int:instrumento_id>/", views.detalhe_instrumento_view, name="detalhe_instrumento"),
    path("instrumento/<int:instrumento_id>/editar/", views.novo_instrumento_view, name="editar_instrumento"),
    path("instrumento/<int:instrumento_id>/faixas/", views.gerenciar_faixas_instrumento_view, name="gerenciar_faixas_instrumento"),
    path("faixa/<int:faixa_id>/editar/", views.editar_faixa_view, name="editar_faixa"),
    path("instrumento/<int:instrumento_id>/registrar-historico/", views.registrar_historico_calibracao_view, name="registrar_historico_calibracao"),
    path("metrologia/historico/<int:historico_id>/preview/", views.preview_certificado_view, name="preview_certificado"),
    path("metrologia/historico/<int:historico_id>/download/", views.download_certificado_view, name="download_certificado"),
    path("metrologia/historico/<int:historico_id>/visualizar/", views.visualizar_historico_calibracao_view, name="visualizar_historico_calibracao"),
    path("metrologia/historico/<int:historico_id>/editar/", views.editar_historico_calibracao_view, name="editar_historico_calibracao"),
    path("metrologia/historico/<int:historico_id>/remover/", views.remover_historico_view, name="remover_historico"),
    path("metrologia/historico/<int:historico_id>/anexar-certificado/", views.anexar_certificado_historico_view, name="anexar_certificado_historico"),
    path("metrologia/historico/<int:historico_id>/remover-certificado/", views.remover_certificado_historico_view, name="remover_certificado_historico"),
    path("metrologia/historico/<int:historico_id>/aplicar-carimbo/", views.aplicar_carimbo_certificado_view, name="aplicar_carimbo_certificado"),
    path("renomear-arquivo-padrao/<int:arquivo_id>/", views.renomear_arquivo_padrao_view, name="renomear_arquivo_padrao"),
    path("remover-arquivo-padrao/<int:arquivo_id>/", views.remover_arquivo_padrao_view, name="remover_arquivo_padrao"),
    path("import-jobs/", views.import_jobs_view, name="import_jobs"),
    path("import-jobs/<uuid:job_id>/retry/", views.retry_import_job_view, name="retry_import_job"),
    path("faixa/<int:faixa_id>/", views.api_faixa_medicao_view, name="api_faixa_medicao"),
    path("imp-inst/", views.imp_instr_view, name="importar_instrumentos"),
    path("imp-historico/", views.imp_historico_view, name="importar_historico"),
    path("imp-colab/", views.imp_colab_view, name="importar_colaboradores"),
    path("imp-hierarquia/", views.imp_hierarquia_view, name="importar_hierarquia"),
    path("imp-ferias/", views.imp_ferias_view, name="importar_ferias"),
    path("novo/", views.novo_instrumento_view, name="novo_instrumento"),
    path("procedimentos/", views.procedimentos_list_view, name="procedimentos_lista"),
    path("procedimento/novo/", views.novo_procedimento_view, name="novo_procedimento"),
    path("procedimento/<int:procedimento_id>/", views.detalhe_procedimento_view, name="detalhe_procedimento"),
    path("procedimento/<int:procedimento_id>/editar/", views.editar_procedimento_view, name="editar_procedimento"),
    path("dl-template-hist/", views.dl_template_historico, name="dl_template_historico"),
]
