# Generated by Django 5.0.14 on 2025-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvaliacaoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_avaliacao", models.DateField(auto_now_add=True)),
                ("nota_tecnica", models.IntegerField(default=10)),
                ("nota_pontualidade", models.IntegerField(default=10)),
                ("nota_atendimento", models.IntegerField(default=10)),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=100)),
                (
                    "razao_social",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("cnpj", models.CharField(max_length=20, unique=True)),
                ("contato", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("escopo_servico", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HOMOLOGADO", "Homologado"),
                            ("BLOQUEADO", "Bloqueado"),
                            ("EM_ANALISE", "Em Análise"),
                        ],
                        default="EM_ANALISE",
                        max_length=20,
                    ),
                ),
                (
                    "nota_media",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
            ],
            options={
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prazo_execucao_dias", models.IntegerField()),
                ("arquivo_proposta", models.FileField(upload_to="orcamentos/")),
                ("vencedor", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessoCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("data_abertura", models.DateField(auto_now_add=True)),
                ("prazo_limite", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("FECHADO", "Fechado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Processos de Cotação",
            },
        ),
    ]
