# Generated by Django 5.0.14 on 2025-12-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metrologia", "0002_initial"),
        ("procurements", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="avaliador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaofornecedor",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="procurements.fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="procurements.fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="processocotacao",
            name="instrumentos",
            field=models.ManyToManyField(to="metrologia.instrumento"),
        ),
        migrations.AddField(
            model_name="processocotacao",
            name="responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orcamentos",
                to="procurements.processocotacao",
            ),
        ),
    ]
