# Generated by Django 5.0.14 on 2026-06-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0018_colaborador_rh_colaborador_turno_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Quadro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_criados', to='rh.colaborador')),
                ('membros', models.ManyToManyField(related_name='quadros_participa', to='rh.colaborador', verbose_name='Membros do Quadro')),
            ],
            options={
                'verbose_name': 'Quadro de Atividades',
                'verbose_name_plural': 'Quadros de Atividades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BoardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='boards.board')),
            ],
            options={
                'verbose_name': 'Log de Atividade do Quadro',
                'verbose_name_plural': 'Logs de Atividades do Quadro',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Coluna')),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='boards.board')),
            ],
            options={
                'verbose_name': 'Coluna do Quadro',
                'verbose_name_plural': 'Colunas do Quadro',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=10, verbose_name='Prioridade')),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='boards.boardcolumn')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_criados', to='rh.colaborador')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_atribuidos', to='rh.colaborador', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Cartão de Atividade',
                'verbose_name_plural': 'Cartões de Atividades',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='boards.card')),
            ],
            options={
                'verbose_name': 'Comentário do Cartão',
                'verbose_name_plural': 'Comentários do Cartão',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Item')),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='boards.card')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'ordering': ['criado_em'],
            },
        ),
    ]
