# Generated by Django 5.0.14 on 2026-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='periodicidade',
            field=models.CharField(choices=[('AVULSA', 'Nenhuma (Avulsa)'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='AVULSA', max_length=15, verbose_name='Periodicidade'),
        ),
    ]
