# Generated by Django 5.0.14 on 2026-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_card_periodicidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
