# Generated by Django 5.0.14 on 2026-06-16 19:07

from django.db import migrations, models

def copy_responsavel_to_responsaveis(apps, schema_editor):
    Card = apps.get_model('boards', 'Card')
    for card in Card.objects.all():
        if card.responsavel_id:
            card.responsaveis.add(card.responsavel_id)

def copy_responsaveis_to_responsavel(apps, schema_editor):
    Card = apps.get_model('boards', 'Card')
    for card in Card.objects.all():
        first_resp = card.responsaveis.first()
        if first_resp:
            card.responsavel = first_resp
            card.save()

class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_arquivado'),
        ('rh', '0018_colaborador_rh_colaborador_turno_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tipo',
            field=models.CharField(choices=[('PADRAO', 'Padrão')], default='PADRAO', max_length=20, verbose_name='Tipo de Quadro'),
        ),
        migrations.AddField(
            model_name='card',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='cartoes_atribuidos', to='rh.colaborador', verbose_name='Responsáveis'),
        ),
        migrations.RunPython(copy_responsavel_to_responsaveis, reverse_code=copy_responsaveis_to_responsavel),
        migrations.RemoveField(
            model_name='card',
            name='responsavel',
        ),
    ]
