# Generated by Django 5.0.14 on 2026-06-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_card_responsavel_board_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sub-sessão')),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsecoes', to='boards.boardcolumn')),
            ],
            options={
                'verbose_name': 'Sub-sessão da Coluna',
                'verbose_name_plural': 'Sub-sessões da Coluna',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='subsecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes', to='boards.boardsubsection', verbose_name='Sub-sessão'),
        ),
    ]
