# Generated by Django 5.0.14 on 2026-06-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_boardsubsection_card_subsecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='antecessora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucessoras', to='boards.card', verbose_name='Tarefa Antecessora'),
        ),
        migrations.CreateModel(
            name='BoardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Etiqueta')),
                ('cor', models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor (Hex)')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='boards.board')),
            ],
            options={
                'verbose_name': 'Etiqueta do Quadro',
                'verbose_name_plural': 'Etiquetas do Quadro',
                'unique_together': {('quadro', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='cartoes', to='boards.boardlabel', verbose_name='Etiquetas'),
        ),
    ]
