# Generated by Django 5.0.14 on 2026-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_card_antecessora_boardlabel_card_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='card',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fim'),
        ),
        migrations.AddField(
            model_name='card',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
    ]
