# Generated by Django 5.0.14 on 2026-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_card_data_conclusao_card_hora_fim_card_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
