# Generated by Django 5.0.14 on 2026-06-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_card_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPlanningDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='boards.card')),
            ],
            options={
                'verbose_name': 'Planejamento de Data/Hora',
                'verbose_name_plural': 'Planejamentos de Data/Hora',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
