# Generated by Django 5.0.14 on 2026-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_cardplanningdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='datetime_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fim'),
        ),
        migrations.AddField(
            model_name='card',
            name='datetime_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Início'),
        ),
    ]
