# Generated by Django 5.0.14 on 2026-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_card_datetime_fim_card_datetime_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardplanningdate',
            options={'ordering': ['datetime_inicio'], 'verbose_name': 'Planejamento de Data/Hora', 'verbose_name_plural': 'Planejamentos de Data/Hora'},
        ),
        migrations.RemoveField(
            model_name='cardplanningdate',
            name='data',
        ),
        migrations.RemoveField(
            model_name='cardplanningdate',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='cardplanningdate',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='cardplanningdate',
            name='datetime_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fim'),
        ),
        migrations.AddField(
            model_name='cardplanningdate',
            name='datetime_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Início'),
        ),
    ]
