# Generated by Django 5.0.14 on 2026-06-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_cardplanningdate_options_and_more'),
        ('rh', '0022_seed_motivos_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomment',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador'),
        ),
    ]
