# Generated by Django 5.0.14 on 2026-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_cardcomment_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link_anexo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link de Acesso'),
        ),
    ]
