# Generated by Django 5.0.14 on 2026-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_card_link_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('ALTA', 'Alta')], default='BAIXA', max_length=10, verbose_name='Prioridade'),
        ),
    ]
