# Generated by Django 5.0.14 on 2026-07-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_alter_card_prioridade'),
        ('rh', '0022_seed_motivos_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mencoes', to='boards.cardcomment')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mencoes_feitas', to='rh.colaborador')),
                ('mencionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mencoes_recebidas', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Menção no Quadro',
                'verbose_name_plural': 'Menções no Quadro',
                'ordering': ['-criado_em'],
            },
        ),
    ]
