# Generated by Django 5.0.14 on 2026-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_boardmention'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Coluna'),
        ),
    ]
