# Generated by Django 5.0.14 on 2026-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_boardcolumn_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='arquivada',
            field=models.BooleanField(default=False, verbose_name='Arquivada'),
        ),
    ]
