# Generated by Django 5.0.14 on 2026-07-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_boardcolumn_arquivada'),
        ('rh', '0023_colaborador_posto_lideranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Link')),
                ('url', models.URLField(max_length=800, verbose_name='URL')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_criados', to='rh.colaborador')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='boards.board')),
            ],
            options={
                'verbose_name': 'Link do Quadro',
                'verbose_name_plural': 'Links do Quadro',
                'ordering': ['-criado_em'],
            },
        ),
    ]
