# Generated by Django 5.0.14 on 2026-07-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_boardlink'),
        ('rh', '0023_colaborador_posto_lideranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='boards.card')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to='rh.colaborador')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_geradas', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Notificação do Quadro',
                'verbose_name_plural': 'Notificações do Quadro',
                'ordering': ['-criado_em'],
            },
        ),
    ]
