# Generated by Django 5.0.14 on 2026-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_boardnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='todos_colaboradores',
            field=models.BooleanField(default=False, verbose_name='Todos os Colaboradores'),
        ),
    ]
