

from .views import (
    modulo_rh_view,
    detalhe_colaborador_view,
    editar_colaborador_view,
    registrar_ocorrencia_view,
    editar_ocorrencia_view,
    deletar_ocorrencia_view,
    listar_ocorrencias_view,
    registrar_ferias_view,
    editar_ferias_view,
    excluir_ferias_view,
    planejamento_hora_extra_list_view,
    planejamento_hora_extra_create_view,
    planejamento_hora_extra_update_view,
    planejamento_hora_extra_delete_view,
    motivo_planejamento_list_view,
    motivo_planejamento_create_view,
    motivo_planejamento_update_view,
    motivo_planejamento_delete_view,
    api_create_motivo,
    # API endpoints
    api_colaboradores,
    api_setores,
    api_cargos,
    api_grupos,
    api_lideres,
    api_supervisores,
)

__all__ = [
    'modulo_rh_view',
    'detalhe_colaborador_view',
    'editar_colaborador_view',
    'registrar_ocorrencia_view',
    'editar_ocorrencia_view',
    'deletar_ocorrencia_view',
    'listar_ocorrencias_view',
    'registrar_ferias_view',
    'editar_ferias_view',
    'excluir_ferias_view',
    'planejamento_hora_extra_list_view',
    'planejamento_hora_extra_create_view',
    'planejamento_hora_extra_update_view',
    'planejamento_hora_extra_delete_view',
    'motivo_planejamento_list_view',
    'motivo_planejamento_create_view',
    'motivo_planejamento_update_view',
    'motivo_planejamento_delete_view',
    'api_create_motivo',
    # API endpoints
    'api_colaboradores',
    'api_setores',
    'api_cargos',
    'api_grupos',
    'api_lideres',
    'api_supervisores',
]

