# Generated by Django 5.0.14 on 2025-12-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Área"
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas (Macro)",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome/Título do Documento",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição/Objetivo/Função"
                    ),
                ),
                (
                    "pasta",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Pasta (Local no Qualiex)",
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Classificação (Tipo de Procedimento)",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Autor (Texto Livre)",
                    ),
                ),
                (
                    "numero_revisao",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Número da Revisão",
                    ),
                ),
                (
                    "ultima_revisao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Revisão"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "proxima_revisao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Revisão"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "documentos_controlados",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Documentos Controlados",
                    ),
                ),
                (
                    "matriz",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Matriz"
                    ),
                ),
                (
                    "sub_area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Sub-Área"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento",
                "verbose_name_plural": "Procedimentos (GED)",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="PacoteTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Pacote"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "procedimentos",
                    models.ManyToManyField(
                        related_name="pacotes",
                        to="training.procedimento",
                        verbose_name="Procedimentos Incluídos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pacote de Treinamento",
                "verbose_name_plural": "Pacotes de Treinamento",
            },
        ),
        migrations.CreateModel(
            name="ProcedimentoRevisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revisao", models.CharField(max_length=10)),
                ("data_revisao", models.DateField(blank=True, null=True)),
                ("data_aprovacao", models.DateField(blank=True, null=True)),
                (
                    "arquivo_prev",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="procedimentos/rev/",
                        verbose_name="Arquivo Revisão Anterior",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aprovador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_aprovadas",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "elaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_elaboradas",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_revisoes",
                        to="training.procedimento",
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_revisadas",
                        to="rh.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Revisão de Procedimento",
                "verbose_name_plural": "Histórico de Revisões",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RegistroTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revisao_treinada", models.CharField(max_length=10)),
                ("data_treinamento", models.DateField()),
                ("validade_treinamento", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treinamentos",
                        to="rh.colaborador",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_treinamento",
                        to="training.procedimento",
                    ),
                ),
                (
                    "revisor_qualidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_qualidade",
                        to="rh.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matriz de Treinamentos",
                "unique_together": {("colaborador", "procedimento")},
            },
        ),
    ]
