# Generated by Django 5.0.14 on 2026-02-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_colaborador_afastado_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentorevisao',
            name='aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_revisoes_aprovadas', to='rh.colaborador'),
        ),
        migrations.AlterField(
            model_name='procedimentorevisao',
            name='elaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_revisoes_elaboradas', to='rh.colaborador'),
        ),
        migrations.AlterField(
            model_name='procedimentorevisao',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_revisoes_revisadas', to='rh.colaborador'),
        ),
        migrations.AlterField(
            model_name='registrotreinamento',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_treinamentos', to='rh.colaborador'),
        ),
        migrations.AlterField(
            model_name='registrotreinamento',
            name='revisor_qualidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_revisoes_qualidade', to='rh.colaborador'),
        ),
    ]
